### ISSUE TITLE
docs: Running a webapp offline

### ISSUE THREAD

**Issue by rmortes** [vite-pwa/vite-plugin-pwa#140]
Hey, I'm struggling a bit with caching a SPA with this plugin, to run it offline. I get a page that says "Oops, you appear to be offline, this app requires an internet connection.", but I can't get any further.

Could you please point me in the right direction to reach this goal? I'd love to write docs about this (and about running solidjs with this plugin, although it's pretty easy)

Thanks!

**Comment by userquin** [comment]
You need to check failing resources  on offline from network tab in dev on your browser.

You need yo check each page collecting all missing resources not ibcluded on the pwa manifest.

Once collected all failing resourceson all your pages, should be images and assets, you need to add all to the sw manifest using the include assets entry on the plugin: https://vite-plugin-pwa.netlify.app/guide/static-assets.html

**Comment by rmortes** [comment]
Since I'm currently trying to create a template, I'm not really working with any external or internal data, just a basic number counter.

The problem I'm facing is: Whenever I go offline, the service worker serves a page named "/offline.html" that only contains the text I wrote in my first message. I'm pretty sure the glob that comes by default (`"**\/*.{js,css,html}"`) sufices to cache my `index.html`, `index.js` and `index.css`

Is there a way to tell Workbox "Yeah, this route IS valid and you should serve it from cache"?

**Comment by userquin** [comment]
To test the pwa on offline you MUST build and preview the build, on dev there is no sw, this plugin will no register/generate it.

If the problem is using the build preview, can you provide a repo with your template? Maybe tmr I can take a look...

**Comment by rmortes** [comment]
Sure, here it is: https://github.com/rmortes/solid-pwa

I'm using `yarn build && yarn serve` to test it

**Comment by userquin** [comment]
The pattern is a glob pattern not a regex pattern, see generated sw.js on the dist folder or in the source tab on browser, you dont have the index.html on the sw cache manifest.

Just try comment out the workbox entry from the plugin, should work as expected.

**Comment by rmortes** [comment]
Same error with the workbox config commented out. This is the HTML I get displayed

```html
```

**Comment by userquin** [comment]
the branch can be found here: https://github.com/userquin/solid-pwa/tree/chore/register-pwa-sw
