### ISSUE TITLE
Build failed to export the 'base' path in the Vue configuration file

### ISSUE THREAD

**Issue by wuxiuran** [vite-pwa/vite-plugin-pwa#236]
Hello, my problem is that static resource files such as JS or CSS and HTML files are in servers with different domain names, so I'm in `vite.config.js` is configured with 'base' to modify the public path of static resources, but `vite-plugin-pwa` seems unable to package this' base ' path into' `service-worker.js` The final output is `{"revision": null, "URL": "assets / index. 17337179. JS"}`. How can I change it to `{"revision": null, "URL":“ https://www.xxx.com/assets/index.17337179.js "}`

**Comment by userquin** [comment]
@wuxiuran this plugin will use the `base` from `vite` not from `vue` configuration

**Comment by wuxiuran** [comment]
@userquin You are right. My problem description is wrong. But the problem does exist, The `base` in `vite-config.js` will not be built into the final file. What should I do

**Comment by userquin** [comment]
@wuxiuran just remove scope from plugin options and from workbox/injectManifest option, you can check src/options.ts module how we configure it.

If you dont have the scope configured, please provide a repro.

**Comment by userquin** [comment]
@wuxiuran try using pwa plugin `base` option

**Comment by cutsin** [comment]
> @wuxiuran try using pwa plugin `base` option

This doesn't work inside `sw.js`, the bundle's fileName doesn't have a prefixed-path define by `base`:
```json
'assets/column.esm.9e87e6e7.js': {..., type: 'chunk'}
```

**Comment by daniel-nagy** [comment]
I discovered there is an option in Workbox to prefix the asset URLs. The following plugin config will allow you to prefix the URLs with your base URL.

```javascript
const baseUrl = "/foo/bar/"

pluginPWA({
  workbox: { modifyURLPrefix: { "": baseUrl } }
})
```

However, even with this configuration the service worker is still not serving pre-cached files, it's always going to the network. I can see in the dev-tools that the service worker is installed and that it is caching the assets. It just doesn't seem to be able to get them from the cache on request.

**Comment by userquin** [comment]
@daniel-nagy can you try just adding `base: '/foo/bar/'` on vite config?

**Comment by daniel-nagy** [comment]
@userquin I tried using Vite's `base` option and just about every combination of the HTML `<base />` tag and absolute/relative asset paths. I can't seem to get it to work. I think the issue may actually be in Workbox. I couldn't find any explicit documentation in Workbox for using base URLs.

**Comment by daniel-nagy** [comment]
@userquin So I deployed my code to a CDN using only Vite's `base` option to test and the service worker is serving the cached assets. So I wonder if this has something to do with Vite's `preview` command, which is how I was testing before.

**Comment by userquin** [comment]
@daniel-nagy I'm checking it rn...

**Comment by userquin** [comment]
@daniel-nagy it is working, it seems there is a bug on the manifest icons, not using the `base`, for example using `vitesse (vue 3)`:

![imagen](https://user-images.githubusercontent.com/6311119/161840072-e4dd836d-42fa-477b-9c9a-dcb7448bfd60.png)

Here the requests:

![imagen](https://user-images.githubusercontent.com/6311119/161839948-ec57800e-77bc-4005-8d04-cda30b395cce.png)

and the sw:

![imagen](https://user-images.githubusercontent.com/6311119/161840209-ba5f99ad-3952-415e-ae18-79ca232ab771.png)

**Comment by userquin** [comment]
Previous example just adding `base: '/foo/'` to the vite config file. I'll check it without ssg on a plain one example to check if working.

**Comment by userquin** [comment]
> @userquin So I deployed my code to a CDN using only Vite's `base` option to test and the service worker is serving the cached assets. So I wonder if this has something to do with Vite's `preview` command, which is how I was testing before.

I was writing this on vite build:

![imagen](https://user-images.githubusercontent.com/6311119/161843292-6b0e25b0-ae4c-4aa8-892a-a782026c9779.png)

**Comment by userquin** [comment]
@daniel-nagy the icons now working, maybe I had an older sw installed, so it seems workbox is ok when using base and the assets relative and the pwa is also ok.

**Comment by daniel-nagy** [comment]
I think I figured out the issue. If you omit the trailing `/` in the URL when using Vite's base option then the assets will not be served from the service worker proxy. If you include the trailing `/` or any path then the assets are served from the proxy.

For example, if your base bath is `/foo/`, your host is `localhost`, and your port is `3000` then if you load `http://localhost:300/foo` you will see content but the service worker will not function properly. However, if you load `http://localhost:300/foo/` or `http://localhost:300/foo/bar` then the service worker will function properly.

**Comment by userquin** [comment]
@daniel-nagy can you test with latest version of vite (2.9.8)?

**Comment by sciyoshi** [comment]
I am also running into this issue. The `modifyURLPrefix` option to `injectManifest` seems to help, but does not prefix the entries added by `additionalManifestEntries` (workbox applies the additional entries last and does not transform them).

**Comment by userquin** [comment]
clsing this since there is a workaround
