### ISSUE TITLE
is support mpa?

### ISSUE THREAD

**Issue by luozhihua** [vite-pwa/vite-plugin-pwa#249]
A Multiple page app has multiple html page, how ever, `vite-plugin-pwa` generate only one route for `index.html`:

```
workbox.registerRoute(new workbox.NavigationRoute(workbox.createHandlerBoundToURL("index.html"), {
    denylist: [/^\/backoffice/]
  }));
```

Is there a way to generating multipe route for multiple pages? 

- foo/index.html
- bar/index.html

```
workbox.registerRoute(
    new workbox.NavigationRoute(
        workbox.createHandlerBoundToURL("foo/index.html"), 
    )
);
workbox.registerRoute(
    new workbox.NavigationRoute(
        workbox.createHandlerBoundToURL("bar/index.html"), 
    )
);
```

**Comment by userquin** [comment]
@luozhihua I have this repo for a vitesse clone using a custom sw: https://github.com/userquin/test-pwa-ts-4.5.5/blob/main/src/sw.ts, you can check the result here [optimistic-cray-38ef22.netlify.app](https://optimistic-cray-38ef22.netlify.app/)

You should also configure your serverfor serving the pages instead acting as a SPA, just check `netlify.toml` with the redirects for each route.

**Comment by userquin** [comment]
@luozhihua you have some hints here: https://github.com/antfu/vitesse/issues/252#issuecomment-1046085093

**Comment by userquin** [comment]
check https://github.com/vite-pwa/sveltekit/issues/65#issuecomment-1734213190
