### ISSUE TITLE
Unable to use latest version with Astro

### ISSUE THREAD

**Issue by kasperstorgaard** [vite-pwa/vite-plugin-pwa#276]
_somewhat related to #199_

# Unable to use latest version with Astro

When using the latest version with astro starter templates, I get the following error:

```
Cannot read properties of undefined (reading 'disable')
```

This leads back to this line
https://github.com/antfu/vite-plugin-pwa/blob/c0f92a7de068780c1183215c97d9966db95b1264/src/index.ts#L85-L87

## Steps to reproduce
1. create astro solution by running `npm init astro -- --template with-vite-plugin-pwa`
2. upgrade vite-plugin-pwa to latest (astro example template is still on `0.11.11` as of this writing)
3. start dev server by running `npm run dev`

_test repo: https://github.com/kasperstorgaard/astro-vite-pwa-bug_

## Possible solution
From debugging node, it looks like `resolveOptions` is never called before the options are accessed.
https://github.com/antfu/vite-plugin-pwa/blob/c0f92a7de068780c1183215c97d9966db95b1264/src/options.ts#L34

That could point to a race condition.
I could solve it locally by guarding the getter (`options && options.disable`), but I don't have enough knowledge of this repo, so creating a PR with that code change seemed a little optimistic.

**Comment by userquin** [comment]
@kasperstorgaard check this https://github.com/withastro/rfcs/discussions/198#discussioncomment-2800143

I have it working with 2 routes, I need to finish the docs and the mapping from the hook.

You will be able to use built-in support, just import the hook and configure it, on previous comment I add it manually for testing.

**Comment by userquin** [comment]
Released initial version of astro integration: https://vite-pwa-org.netlify.app/frameworks/astro.html
