### ISSUE TITLE
How to listen for the "controlling" event in the main window

### ISSUE THREAD

**Issue by ZYinMD** [vite-pwa/vite-plugin-pwa#296]
I found some example code from the official doc [here](https://developer.chrome.com/docs/workbox/handling-service-worker-updates/#the-code-to-put-in-your-page) about listening for the "controlling" event in the main window, it's something like this:
```js
import { Workbox } from 'https://storage.googleapis.com/workbox-cdn/releases/6.4.1/workbox-window.prod.mjs';
const wb = new Workbox('/sw.js');
wb.addEventListener('controlling', () => {
   //...
});
```
How can I listen for this event in a vite-plugin-pwa app? I'm using injectManifest. Thanks!

**Comment by ZYinMD** [comment]
I was looking for a way to know when sw is ready to intercept web requests. I created [a question on stackoverlow](https://stackoverflow.com/questions/72468047/which-service-worker-event-indicates-it-is-ready-to-and-will-intercept-web-tra). Maybe you could give some advices? Either in here or over there. Thanks!

**Comment by viniciusknob** [comment]
@ZYinMD I was looking for the same answer and I saw the question on stackoverflow already answered and accepted. I tested the solution and really worked.

```js
navigator.serviceWorker.addEventListener('controllerchange', (...) => {...});
```
More info: https://web.dev/learn/pwa/update/#force-override

I think this issue could be closed.

**Comment by ZYinMD** [comment]
Close because the question has been answered both in the stackoverflow post in https://github.com/vite-pwa/vite-plugin-pwa/issues/296#issuecomment-1144228063 and also in viniciusknob's reply.
