### ISSUE TITLE
Adding support for fallback responses

### ISSUE THREAD

**Issue by reorx** [vite-pwa/vite-plugin-pwa#388]
I have a simple vanilla JS app integrated with vite-plugin-pwa: https://github.com/reorx/sui2, my vite config is shown below:

```js
VitePWA({
      injectRegister: 'auto',
      registerType: 'prompt',
      workbox: {
        globPatterns: ['**/*.{js,css,html,ico,png,svg}']
      },
      manifest,
    })
```

My goal is to make the app work offline, which has been achieved properly, but when I open the app with a non-existing url like https://reorx.github.io/sui2/foo (after opening the [homepage](https://reorx.github.io/sui2) for the first time), it shows the home page other than the [404 page](https://reorx.github.io/sui2/404.html).

I want vite-plugin-pwa to handle the fallback or 404 page in a way that is simple and easy. The idea comes from [Managing fallback responses - Chrome Developers](https://developer.chrome.com/docs/workbox/managing-fallback-responses/),
but I'm not able to understand how to use workbox very clearly. That's why this issue was created. Please consider adding this feature.

Appreciate your work as always!

**Comment by userquin** [comment]
@reorx just add `workbox: { navigationFallback: '404.html' }`

**Comment by reorx** [comment]
Thanks for the reply, it works as expected! Now I understand more about the Workbox APIs :)

I searched the document and found that `navigateFallback` is only documented in "Development" section, maybe it's better to also mention it in "Service Worker Precache" or "Static assets handling", just saying.

**Comment by userquin** [comment]
@reorx PR welcome, if you want to send a PR send it to the New docs repository
