### ISSUE TITLE
Workbox is precaching URLs without revision info: index.html This is generally NOT safe.

### ISSUE THREAD

**Issue by stefanhoelzl** [vite-pwa/vite-plugin-pwa#392]
Hi,

I tried to follow [this example](https://vite-pwa-org.netlify.app/workbox/inject-manifest.html#exclude-routes) in the docs to make my PWA available offline.

But I get the following warning from workbox
```
Workbox is precaching URLs without revision info: index.html
This is generally NOT safe
```

This piece of code introduces the warning
```javascript
registerRoute(new NavigationRoute(
  createHandlerBoundToURL('index.html')
))
```

What exactly does this warning mean? And how can I get rid of it?

**Comment by userquin** [comment]
@stefanhoelzl the warning comes when dev options enabled: we only include the entry point to be intercepted, but we don't add the revision and so the warning, you can ignore it (will be only shown on dev with devOptions.enabled set to true)

**Comment by stefanhoelzl** [comment]
Thanks @userquin
