### ISSUE TITLE
Service worker returns index.html for sub-URLs

### ISSUE THREAD

**Issue by qminds** [vite-pwa/vite-plugin-pwa#398]
## Setup

- ~~Vue.js app~~
- ~~Netlify deployment~~
- `generateSW` strategy

## Description

My app ~~is using the dynamic routing, so in fact it~~ consists of one *actual* page (`index.html`) and a couple assets. When I'm requesting the non-existent sub-URL, service worker for some reason returns the pre-cached root page instead of the expected 404 error.

## Question

Is this behavior intended, or maybe there is something wrong with my config?
How do I properly handle this situation?

**Comment by userquin** [comment]
@qminds since your app is a Vue SPA you should add a catch all page to your router: for example, I use `vite-plugin-pages` and so I just add `[...all].vue` to my pages folder, if you're not using this plugin, check this link: https://router.vuejs.org/guide/essentials/dynamic-matching.html#catch-all-404-not-found-route

In your server configuration you should forward to your entry point when any requested entry is not found: check an example here https://github.com/antfu/vitesse/blob/main/netlify.toml#L8

**Comment by qminds** [comment]
Hi @userquin,
Thanks for your reply.

Actually, now I believe this issue has nothing to do with Vue routing itself, since both **HTML5 mode** (with a proper server redirects configuration) and **Hash mode** don't work. Seems that I'm getting the same response even for the *existing* assets which are not present in the `includeAssets` array.

So let me show my steps to reproduce:

- I unregister service worker in my browser to return to an initial state.
- I open `https://example.com/non-existent-url` and get the 404 error from server (which is expected).
- I open `https://example.com`, so now the service worker is registered in my browser.
- I open `https://example.com/non-existent-url` *again*. And now the service worker gives me the root page from the previous step, however I was expecting the 404 error.

**Comment by userquin** [comment]
@qminds your app is a SPA not a MPA so your routes are missing (this is the reason you're getting the same reponse), you can try SSG (vite-ssg for example: fork or use Vitesse template in a new project to test it, running the build script will generate the html for each routes, except dynamic ones) and so your routes should be there (I mean the html pages will be generated).

**Comment by userquin** [comment]
> * I open `https://example.com/non-existent-url` and get the 404 error from server (which is expected).

Just add the entry to your netlify configuration to redirect/forward to your entry point when missing: do not use 404 if you want to avoid this

**Comment by qminds** [comment]
@userquin I think there is a little misunderstanding.

> your app is a SPA not a MPA so your routes are missing

As I wrote before, the issue has nothing do with the Vue.js routing.
This also happens even on the default Vite setup for vanilla JS.
Sorry and forget that I mentioned Vue in my first message :)

> Just add the entry to your netlify configuration to redirect/forward to your entry point when missing: do not use 404 if you want to avoid this

I **do** want the 404 error for missing paths, but the service worker (*not* Vue.js or *Netlify*) returns the initial page for these paths. I tested this setup locally, and the same issue happens even without Netlify.

**Comment by userquin** [comment]
@qminds can you provide a minimal repro?

**Comment by qminds** [comment]
Here is the [ZIP](https://github.com/vite-pwa/vite-plugin-pwa/files/9846908/sw.zip) to avoid any conflicts, since StackBlitz already provides some kind of service worker.

This archive contains the default Vite setup for vanilla JS. I just added the PWA plugin and `http-server` package in order to serve the page locally without relying on the Vite dev server.

- Run `npm i` to install dependencies.
- Run `npm run serve` command to build the project and serve it locally.
- Open `http://localhost` with the specified port in your browser.
- Proceed to any sub-URL, e.g. `http://localhost/hello`.

Due to the service worker, you'll still see the main page instead of the expected 404 error.

**Comment by userquin** [comment]
@qminds  so, you want this? you can disable fallback using `workbox: { navigationFallback: undefined }`

![imagen](https://user-images.githubusercontent.com/6311119/197402705-08bc405a-e0c6-44bd-9801-80c8b2243975.png)

**Comment by qminds** [comment]
Perfect, thanks a lot!
