### ISSUE TITLE
An error was reported when I packaged the vue3+ts + pwa project

### ISSUE THREAD

**Issue by lmq352489099** [vite-pwa/vite-plugin-pwa#399]
![image](https://user-images.githubusercontent.com/37898934/197703811-20707e41-66d3-422b-9609-5f43557afea1.png)

**Comment by userquin** [comment]
@lmq352489099 using 0.13.0+ requires Vite 3.1+, if you're still using Vite 2 you will need to use 0.12 version of the plugin
