### ISSUE TITLE
non-precached-url :: [{"url":"/"}] on SvelteKit

### ISSUE THREAD

**Issue by Cluster2a** [vite-pwa/vite-plugin-pwa#400]
Hey, I am using the following configuration:

```TypeScript
import { sveltekit } from '@sveltejs/kit/vite';
import { VitePWA } from 'vite-plugin-pwa';
import type { UserConfig } from 'vite';

const mode = process.env.NODE_ENV as 'development' | 'production';

console.log(mode)

const config: UserConfig = {
	server: {
		hmr: {
			clientPort: 80
		}
	},
	define: {
		__DATE__: `'${new Date().toISOString()}'`,
		__RELOAD_SW__: false
	},
	plugins: [
		sveltekit(),
		VitePWA({
			srcDir: './src',
			mode,
			strategies: 'injectManifest',
			filename: 'service-worker.ts',
			scope: '/',
			base: '/',
			manifest: {
				short_name: 'Example PWA',
				name: 'Example PWA',
				start_url: '/',
				scope: '/',
				display: 'standalone',
				theme_color: '#ffffff',
				background_color: '#ffffff',
				icons: [
					{
						src: '/img/pwa-192x192.png',
						sizes: '192x192',
						type: 'image/png'
					},
					{
						src: '/img/pwa-512x512.png',
						sizes: '512x512',
						type: 'image/png'
					},
					{
						src: '/img/pwa-512x512.png',
						sizes: '512x512',
						type: 'image/png',
						purpose: 'any maskable'
					}
				]
			},
			devOptions: {
				enabled: mode === 'development',
				type: 'module',
				navigateFallback: '/'
			}
		})
	]
};

export default config;

```

service-worker.ts:
```TypeScript
import {
	cleanupOutdatedCaches,
	createHandlerBoundToURL,
	precacheAndRoute
} from 'workbox-precaching';
import { NavigationRoute, registerRoute } from 'workbox-routing';

declare let self: ServiceWorkerGlobalScope;

self.addEventListener('message', (event) => {
	if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

// self.__WB_MANIFEST is default injection point
precacheAndRoute(self.__WB_MANIFEST);

// clean old assets
cleanupOutdatedCaches();

let allowlist: undefined | RegExp[];
if (import.meta.env.DEV) allowlist = [/^\/$/];

// to allow work offline
registerRoute(new NavigationRoute(createHandlerBoundToURL('/'), { allowlist }));
```

As long as I am running in dev mode, everything seems to be okay - the worker is running, and I am not getting any errors.

As soon as I build & preview, I get this error:
`
service-worker.js:2 Uncaught non-precached-url: non-precached-url :: [{"url":"/"}]
    at V.createHandlerBoundToURL (http://xxx.io/service-worker.js:2:1255)
    at ne (http://xxx.io/service-worker.js:2:5578)
    at http://xxx.io/service-worker.js:2:28886
`

![image](https://user-images.githubusercontent.com/84905165/198276482-a9d1612c-928b-4cc8-89f0-e594464eaa10.png)

I included everything in the root +layout.svelte, regarding your example.
In the +page.server.ts I am doing a redirect - user logged in -> /dashboard / not logged in -> /auth/login

I don't think the redirect is the problem since everything is running smoothly in dev.

I already checked the other issues for this topic (https://github.com/vite-pwa/vite-plugin-pwa/issues/120), but I could not find any solution for this problem.

Thanks in advanced - Alex

`px envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"`
```
  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900KS CPU @ 4.00GHz
    Memory: 5.36 GB / 15.54 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.4.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.99 => 1.0.0-next.99 
    @sveltejs/kit: 1.0.0-next.525 => 1.0.0-next.525 
    svelte: ^3.52.0 => 3.52.0 
    vite: ^3.2.0 => 3.2.0 
```

**Comment by userquin** [comment]
@Cluster2a the problem here is kit, and how it works: the current version is not yet ready to work with latest kit changes (from 358+ version IIRC)

We have a new custom plugin for kit here but not yet released: https://github.com/vite-pwa/sveltekit

To make this plugin working again with the latest kit (358+) we need Vite 3.1+ with the new sequential hook (Rollup): the problem is kit prerender process will be triggered in the `writeBundle` hook and this plugin need access to generated html pages once this process finish (this is why we need Vite 3.1+) but before the kit `closeBundle` hook runs (it will run the adapter to copy files to the corresponding build folder).

This plugin will run on its own `closeBundle` hook but it is running in parallel with the kit ones and so pwa plugin will not have access to the pages generated by the kit prerender process (it is running in parallel with the kit `writeBundle` and it is finishing before it)

**Comment by Cluster2a** [comment]
@userquin, thanks for the input - I thought I am doing something wrong since I am not that familiar with service worker.

Is there any ETA for your custom plugin?

**Comment by ahhshm** [comment]
Any update on this? I'm using vite `3.2.2` and your sveltekit plugin but get the same error.
