### ISSUE TITLE
Docs are at v0.12.3

### ISSUE THREAD

**Issue by piotr-cz** [vite-pwa/vite-plugin-pwa#403]
The docs at <https://vite-plugin-pwa.netlify.app/> are for *v0.12.3* while [latest](https://github.com/vite-pwa/vite-plugin-pwa/releases/latest) is *v0.13.1*

There are few changes that I've found:
- onRegistered -> onRegisteredSW
- virtual module virtual:pwa-info

It looks like docs for latest version are ready, just not published

**Comment by piotr-cz** [comment]
Okay, it seems that new url for docs is https://vite-pwa-org.netlify.app/ which is at *v0.13.1*
however the [README.md](../blob/main/README.md) and repo's about are linking to the other url

**Comment by userquin** [comment]
> however the [README.md](../blob/main/README.md) and repo's about are linking to the other url

We're preparing the change to remove old docs, rn if you just do a hard refresh on old docs, you'll be redirected to the new ones (don't do the hard refresh, do it in a private window if you want to see the redirect, we're going to add the `selfDestroying` sw  to the old docs soon and so uninstalling the pwa from clients, on refresh will be redirected, it requires some testing)

**Comment by userquin** [comment]
virtual pwa info module from v0.12.8+: https://github.com/vite-pwa/vite-plugin-pwa/releases/tag/v0.12.8

**Comment by userquin** [comment]
From version v0.13.0+ you'll also need Vite 3.1+: https://github.com/vite-pwa/vite-plugin-pwa/blob/main/README.md#-install

**Comment by piotr-cz** [comment]
Thank you,
indeed when I try hard refresh or `curl -I https://vite-plugin-pwa.netlify.app/` I get 301 response 👍
