### ISSUE TITLE
SW update does not work when another service worker is registered in same domain (svelte)

### ISSUE THREAD

**Issue by Tommertom** [vite-pwa/vite-plugin-pwa#412]
Hi

I need to register firebase's service worker (firebase-messaging-sw.js) next to Vite's routine for service worker registration. 

I currently register the firebase sw in index.html.

When there is a needRefresh event, and I use updateServiceWorker, then the page reloads but the needRefresh event is fired again - I assume because the service worker is not updated.

I use the registration code as per svelte documentation in my sveltekit project (static and outdir=build)

Without the firebase sw  all works perfect (update).

Kindly advise - either how to register another service worker without disrupting the update routine, or maybe indicate if this is a bug?

Interestingly - navigator.serviceWorker.getRegistrations() only shows 1 registration, and this is sw.js (from the bundle generation)

**Comment by userquin** [comment]
Maybe you can try importing/adding the firebase sw logic inside your sw

**Comment by Tommertom** [comment]
Thx-  I think I will be able to solve using different scopes for the registrations. Still testing.  I am not fluent enough in this space so need some examples how to deal with this by having a single registration handlnig two scripts (like with importScripts).

For now issue closed.
