### ISSUE TITLE
injected sw.js ends up precaching additional folders because of vite.config.js outDir param

### ISSUE THREAD

**Issue by vesper8** [vite-pwa/vite-plugin-pwa#414]
Not sure if this is the intended behaviour but it's causing me some issues.

My outDir param is set to build the dist files inside a folder that already contain other folders unrelated to the Vite build. And those folders end up being precached inside sw.js which I want to avoid.

I tried excluding them via the `workboxOptions` options (not entirely sure I'm appending these in the right place) to no avail.

```
  VitePWA({
    mode: process.env.NODE_MODE,
    srcDir: 'src',
    // filename: 'sw.js',
    filename: 'sw.ts',
    base: '/',
    strategies: 'injectManifest',
    includeAssets: ['/favicon.ico'],
    manifest: {
      name: 'redacted',
      short_name: 'redacted',
      theme_color: '#4338ca',
      background_color: '#4338ca',
      display: 'standalone',
      icons: [
        {
          src: '/icons/android-chrome-192x192.png',
          sizes: '192x192',
          type: 'image/png',
        },
        {
          src: '/icons/android-chrome-512x512.png',
          sizes: '512x512',
          type: 'image/png',
        },
      ],
    },
    
    workboxOptions: {
        exclude: [
          /^.*folder-to-exclude\/.*$/,
        ]
      }
  }),
```

Is that where you put workboxOptions ?

Why is sw.js adding folders to the precaching that aren't part of the "Build" command? A quirk surrounding the mixing of `self.__WB_MANIFEST` and `outDir` maybe?

**Comment by vesper8** [comment]
@userquin thank you very much for trying to help.

I still can't get it to filter out those files and folders.

I know I must include everything for my app to work offline, however as I mentioned above, the files that I want filtered out of my sw.js are files that my app does not at all depend on. It just so happens that the sw.js, and my app's assets, are being generated in a folder that already contains other files and folders that my app is not dependent on. Because of a complicated reason, I can't really change that, so I have to figure out a way to have my sw.js not include those files (I don't fully understand why it's including those files anyway, but it has to do with the `outDir` parameter somehow.

Anyway I just tried multiple variations of using the `globIgnores` and none of them worked.

Here's what I tried:

```
  VitePWA({
    mode: process.env.NODE_MODE,
    srcDir: 'src',
    // filename: 'sw.js',
    filename: 'sw.ts',
    base: '/',
    strategies: 'injectManifest',
    includeAssets: ['/favicon.ico'],
    manifest: {
      name: 'redacted',
      short_name: 'redacted',
      theme_color: '#4338ca',
      background_color: '#4338ca',
      display: 'standalone',
      icons: [
        {
          src: '/icons/android-chrome-192x192.png',
          sizes: '192x192',
          type: 'image/png',
        },
        {
          src: '/icons/android-chrome-512x512.png',
          sizes: '512x512',
          type: 'image/png',
        },
      ],
    },

    workbox: {
      globIgnores: [
        'chess',
        '*chess*',
        '*/chess/*',
        '**/chess/**',
        '**/chess/**/*',
        '*/theme.css',
        "**\/chess\/**\/*",
        "**\/vendor\/**\/*",
      ],
    },
  }),
```

No matter what I do, this line always ends up in my generated sw.js : 

`{"revision":"4121fcdb5292d2a9dff2b96d565f3ba8","url":"chess/nova-theme/theme.css"},`

Am I just completely misusing the `globIgnores` syntax or.. is the problem elsewhere you think?

Would love some help solving this. Thanks a lot

**Comment by userquin** [comment]
@vesper8 weird, you can try adding a manifestTransform, you Will be able to filter any entry you want from the sw precache manfest, check how to configure it in sveltekit repo

**Comment by userquin** [comment]
https://github.com/vite-pwa/sveltekit/blob/main/src/config.ts#L61

**Comment by userquin** [comment]
@vesper8 you are using inject manifest, add it to `injectManifest` option instead to `workbox`

**Comment by userquin** [comment]
```ts
  VitePWA({
    mode: process.env.NODE_MODE,
    srcDir: 'src',
    // filename: 'sw.js',
    filename: 'sw.ts',
    base: '/',
    strategies: 'injectManifest',
    includeAssets: ['/favicon.ico'],
    manifest: {
      name: 'redacted',
      short_name: 'redacted',
      theme_color: '#4338ca',
      background_color: '#4338ca',
      display: 'standalone',
      icons: [
        {
          src: '/icons/android-chrome-192x192.png',
          sizes: '192x192',
          type: 'image/png',
        },
        {
          src: '/icons/android-chrome-512x512.png',
          sizes: '512x512',
          type: 'image/png',
        },
      ],
    },

    injectManifest: {
      globIgnores: [
        'chess',
        '*chess*',
        '*/chess/*',
        '**/chess/**',
        '**/chess/**/*',
        '*/theme.css',
        "**\/chess\/**\/*",
        "**\/vendor\/**\/*",
      ],
    },
  }),
```

**Comment by vesper8** [comment]
Thank you. I'll give that a try.

I did overcome my problem by changing the outDir to a tmp folder, and then copying the files to where I needed them to be afterwards. This prevented the sw.js from filling up with random files unrelated to my pwa build.
