### ISSUE TITLE
Dev dist folder path?

### ISSUE THREAD

**Issue by jrj2211** [vite-pwa/vite-plugin-pwa#417]
I've configured my vite to use another dist folder:
```
build: {
    target: 'esnext',
    outDir: '../dist',
    emptyOutDir: true,
  },
```

I notice that when building vite with VitePWA dev mode enabled, it creates anopther folder called 'dev-dist' that contains the registerSW.js, sw.js and workbox-*.js files. 

Is there a way to configure where these files are put? I just want them to go into the vite configured dist folder. Is there a reason these don't default to vites dist folder?

**Comment by userquin** [comment]
@jrj2211 rn `dist-dev` folder cannot be changed, only created for dev with devOptions enabled: PR welcome (check `src/plugins/dev.ts` module)

**Comment by userquin** [comment]
@ben-xD use `devOptions.resolveTempFolder`: https://github.com/vite-pwa/vite-plugin-pwa/blob/main/src/plugins/dev.ts#L190-L194

**Comment by ben-xD** [comment]
Thanks @userquin. Reading "Use it with caution, it should be used only by framework integrations.", I'm worried if I'm using it wrongly.

I just want to up to date service worker to be used in dev mode, but how can it be if it's in `dev-dist`?

**Comment by userquin** [comment]
Sw in dev should be used only to test the web manifest and custom sw logic such as push notifications, web shared target api, background sync...

If you're using generateSW strategy, having the sw in dev no makes sense. Keep in mind that the sw in dev will have only en entry point un the sw precache manifest.

You should always test the sw capabilities (offline for example) using build + preview.
