### ISSUE TITLE
Service Worker works in dev, but in production get error  Failed to execute 'importScripts' on '

### ISSUE THREAD

**Issue by samuk190** [vite-pwa/vite-plugin-pwa#419]
Hello I'm trying to implement  my firebase notification background service worker..

While this works in devmode

vite.config.ts
```
  VitePWA({
      base: '/',
      srcDir: 'src',
      filename: 'firebase-messaging-sw.js',
      registerType: 'autoUpdate',
      devOptions: {
        enabled: true
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html}', '**/*.{svg,png,jpg,gif}'],
        mode: 'production',
        swDest: 'dist/firebase-messaging-sw.js'
      },
    }),
    
```
   
 ```
  Firebase.tsx (imported in App)

 if ('serviceWorker' in navigator) {
    window.addEventListener('load', () => {
      navigator.serviceWorker.register('/firebase-messaging-sw.js', { scope: '/', type: 'module' }).then(serviceWorkerRegistration => {

```
        if(serviceWorkerRegistration.installing) {
          console.log('Service worker installing');
      } else if(serviceWorkerRegistration.waiting) {
          console.log('Service worker installed');
      } else if(serviceWorkerRegistration.active) {
          console.log('Service worker active');
      }
      getToken(getMessaging(fapp), {
        serviceWorkerRegistration,
        vapidKey: `SECRET_KEY`,
      }).then((state) => {
        console.log(state);
      })
      })  
    })
  }

Error in production:
Uncaught (in promise) TypeError: Failed to execute 'importScripts' on 'WorkerGlobalScope': Module scripts don't support importScripts().

how can I Correct that ?

**Comment by userquin** [comment]
@samuk190 cnhage strategies to injectManifest, you cannot use workbox option, change it to injectManifest

**Comment by userquin** [comment]
@samuk190 you cannot use `type: 'module'` registering the sw, it will work only con chromiun based browsers

**Comment by samuk190** [comment]
> @samuk190 you cannot use `type: 'module'` registering the sw, it will work only con chromiun based browsers

I' ve changed to classic, and made it injectManifest, but injectManifest always complain that swdest and swsrc are the same... 

What im doing that worked now is 
using viteStaticCopy to copy the sw to the dist folder.
using VitePWA to load it with generateSW to able to debug in dev mode.
  base: '/',
      srcDir: 'dist',
      filename: 'sw.js',
      registerType: 'autoUpdate',
      mode: 'development',
      outDir: 'dist',
      devOptions: {
        enabled: true,
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html}', '**/*.{svg,png,jpg,gif}'],
        mode: 'development',
        swDest: 'dist/firebase-messaging-sw.js',
        importScripts: ['./firebase-messaging-sw.js']

      },
    }),
    viteStaticCopy({
      targets: [
        {
          //coloca firebase messaging como sw.js (prod) sem transpilar.
          src: 'firebase-messaging-sw.js',
          dest: '.', // 2️⃣
          rename: 'sw.js'
        },
      ],
    }),
    
    I know injectManifest is a better approach and less hacky, but its working for now, I will try the best approach later.
