### ISSUE TITLE
​

### ISSUE THREAD

**Issue by VentGrey** [vite-pwa/vite-plugin-pwa#426]
​

**Comment by VentGrey** [comment]
I'm also noticing that the build command does not add the sw.js file as well :(

**Comment by userquin** [comment]
@VentGrey weird, build plugin has not been changed, only added sequential hook to support Vite 3.1 and some integration (from 0.13.0+ version you need Vite 3.1+)

**Comment by VentGrey** [comment]
I'm using vite 3.1+ I've noticed it's not inserting the links properly. Adding them manually restores the PWA functions correctly.

**Comment by VentGrey** [comment]
Just in case someone is having this issue as well, here is a temporary fix in `index.htm` file:

```html
<!-- Paste this near the other <link> tags in your <head> -->
<link rel="manifest" href="/manifest.webmanifest">
.
.
.
<!-- Paste this before your <body/> tag, prefferably after the main.ts file in svelte -->
<script id="vite-plugin-pwa:register-sw" src="/registerSW.js"></script>
```
