### ISSUE TITLE
The backround sync does not work immediately

### ISSUE THREAD

**Issue by realconvis** [vite-pwa/vite-plugin-pwa#434]
I try to get the backround sync running for a PWA with this config:

```
workbox: {
        runtimeCaching: [
          {
            handler: "NetworkOnly",
            urlPattern: new RegExp("^https://localhost/api/basic_packages$"),
            method: "POST",
            options: {
              backgroundSync: {
                name: "postQueue",
                options: {
                  maxRetentionTime: 24 * 60,
                },
              },
            },
          },
```

I clear all local storages and caches and load the application in browser.
I install the application.
I select the checkbox "offline" for serviceworker in devtools of chrome.
The post requests do not  end up in the queue.
But if i reload the PWA while offline, it suddenly works.
The matching requests end up in the queue like expceted.

If i use a string instead of the regexp, it works from the beginning without the reload.

What could be the problem?

**Comment by realconvis** [comment]
Still have problems to get background sync working. 
Does anyone have experience with it?

**Comment by userquin** [comment]
@realconvis maybe this repo can help you https://github.com/jeffposnick/yt-playlist-notifier; check also https://developer.chrome.com/articles/periodic-background-sync/
