### ISSUE TITLE
Subsequent variable declarations must have the same type

### ISSUE THREAD

**Issue by hornta** [vite-pwa/vite-plugin-pwa#444]
I'm getting a weird error that prevents me from building. 

![image](https://user-images.githubusercontent.com/4553604/211196038-1926284e-02af-4d60-89ff-ebf3c2e8d7ab.png)

I raised another issue regarding a similar issue where I thought I've solved my typing issues but it didn't work in the end.

This is how my tsconfig.json look like for sw.ts

```json
{
  "compilerOptions": {
    "lib": ["ESNext"],
    "types": ["serviceworker"],
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "noEmit": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "ESNext",
    "useDefineForClassFields": true
  },
  "include": ["./"]
}
```

**Comment by userquin** [comment]
I have this (using also `import.meta.env` on my custom sw), the tsconfig for the app has same entries as yours, can you try adding `WebWorker` to lib or change the reference to `WebWorker` (case sensitive?)?
```json
{
  "compilerOptions": {
    "lib": ["ESNext", "WebWorker"],
    "types": ["vite/client", "service-worker"]
  },
  "include": ["./"],
  "extends": "../tsconfig.json"
}
```

![imagen](https://user-images.githubusercontent.com/6311119/211196733-166aba59-07af-4403-b363-911835e11aff.png)

**Comment by hornta** [comment]
It didn't seem to help I'm afraid. I changed "service-worker" to serviceworker since that's what the name of the serverworker package is: https://www.npmjs.com/package/@types/serviceworker
![image](https://user-images.githubusercontent.com/4553604/211198692-c45afcfd-43b3-47b8-8bfe-640cb8cebae3.png)

**Comment by hornta** [comment]
I published what I have to a github repository: https://github.com/hornta/vite-project

It's just the Vite vanilla + TS and vite-plugin-pwa

The build fails when I do `pnpm build`

**Comment by userquin** [comment]
https://github.com/hornta/vite-project/pull/1

**Comment by hornta** [comment]
Thanks. I just tried it out in my real project and it works. I could even let the build script be `tsc && vite build` without any differences.
