### ISSUE TITLE
Barebones PWA won't automatically reload

### ISSUE THREAD

**Issue by jmagaram** [vite-pwa/vite-plugin-pwa#449]
I created a totally barebones React project from the Vite template and followed the instructions as best I could to create a minimal PWA that should automatically reload - no prompt - when the application changes. I can install it on Chrome on macOS, but it won't automatically reload. Here is the project... 

https://github.com/jmagaram/vite-empty-ts

This is what I'm doing to repro:

1. Run the "build" script
2. Run the "preview" script
3. Open the app in Chrome using the `http://localhost:...` path
4. Install the app
5. Edit text in `App.tsx`; just make some kind of visible change
6. Run the "build" script again - I'm expecting this to replace the old app with the new one
7. Wait for the running app to update; it won't automatically update
8. Close the PWA app. Start it again. You'll see the changes. Or click "Reload" when right-clicking on the title bar.

The main things I did to try to get it to automatically update were based on https://vite-pwa-org.netlify.app/guide/auto-update.html

a. `registerSW({immediate})` in the `main.tsx`
b. `registerType: "autoUpdate"` in `vite.config.ts`

**Comment by berkcambaz** [comment]
I think you should add
`workbox: {skipWaiting: true, clientsClaim: true}` to vite-plugin-pwa in your vite.config.ts

**Comment by userquin** [comment]
@jmagaram it is working, maybe you want the refresh to be automatic, if so, read this: https://vite-pwa-org.netlify.app/guide/periodic-sw-updates.html

https://streamable.com/3gzbx9
