### ISSUE TITLE
The user needs to refresh page twice

### ISSUE THREAD

**Issue by Oleksii14** [vite-pwa/vite-plugin-pwa#451]
Hello! I use the default config for Vite plugin PWA with "autoUpdate". There is one question I can find an answer to: when the new version is deployed, the user needs to reload the page twice to see the updated app. Can you advice how to solve this issue?

**Comment by userquin** [comment]
@Oleksii14 you can use periodic sync for updates to detect new version (this will not require refresh to detect new version): for second refresh, `autoUpdate` is not `auto refresh page`, so to do `auto update` + `refresh page to allow new sw controlling the app` you must use any virtual module

You can check these entries:
- check the warning here about auto update: https://vite-pwa-org.netlify.app/guide/auto-update.html#automatic-reload
- https://vite-pwa-org.netlify.app/guide/periodic-sw-updates.html

**Comment by Oleksii14** [comment]
@userquin thanks! It worked.

Could you explain how does it work under the hood? How does a virtual module checks for a new service worker and applies it? Can you share any links to the source code?
