### ISSUE TITLE
Question: Offline cache on dev mode

### ISSUE THREAD

**Issue by G100g** [vite-pwa/vite-plugin-pwa#453]
Is it possible to run the application offline with the command `npm run dev`?

With the default setup, if I set network connectivity to _Offline_ in the devtools, I'm not able to cache all JS assets,
I tested also you react-router example and is not possible to run it offline in dev mode.

Do you confirm that offline works just with `npm run build`?

Thank you for your amazing work! 🙏

**Comment by userquin** [comment]
> Is it possible to run the application offline with the command `npm run dev`?
> 

No, the pwa dev plugin disables explicitly offline support: `devOptions` was included to allow test web manifest and custom service worker logic (push notifications, web share target api...)

> Do you confirm that offline works just with `npm run build`?

Yes, you must test offline capabilities via `build + preview` Vite commands.

**Comment by G100g** [comment]
Thank you for the answer!
