### ISSUE TITLE
error on build

### ISSUE THREAD

**Issue by chirastefan** [vite-pwa/vite-plugin-pwa#462]
Runing vite build I get this error:

![Screenshot 2023-02-09 at 00 57 03](https://user-images.githubusercontent.com/16649178/217671122-fb088f82-7f4a-4063-8d2f-bdc7025c181b.png)

Config:

```
...
    plugins: [
      react(),
      splitVendorChunkPlugin(),
      VitePWA({
        manifest,
        registerType: 'autoUpdate',
        includeAssets: ['robots.txt', 'public/*', 'icons/*.svg', 'fonts/*.woff2'],
        devOptions: {
          enabled: mode === ENVS.Dev
        },
        workbox: {
          sourcemap: true
        }
      })
    ],
...
```

**Comment by userquin** [comment]
update to Vite 3.1, check readme file https://github.com/vite-pwa/vite-plugin-pwa#-install

if you cannot update to Vite 3.1, you should use only 0.12.* version
