### ISSUE TITLE
Feature request: Add SolidStart support

### ISSUE THREAD

**Issue by seeplusplus** [vite-pwa/vite-plugin-pwa#465]
I'm not sure how difficult this would be to add, but I've already used this plugin with a SolidStart project. Everything seems to work perfectly, except for injecting the SW registration script/manifest link (if I add  them manually into the root.tsx everything works). I am also more than happy to take a look at adding this support myself, but may take me a bit longer to learn the code.

**Comment by userquin** [comment]
I guess we don't need to include a new package to include only these 2 features, we have a solidjs virtual module and a new virtual module for pwa info that we can use to expose the <link> in the header (not documented, it is present only in meta framework integrations, check Astro or SvelteKit, in Nuxt we have a custom component similar to the code snippet shown below).

About sw registration, use `virtual:pwa-register/solid` instead `injectRegister: 'auto/script'`, will also solve automatic page reload on sw auto reload: check the warning here https://vite-pwa-org.netlify.app/guide/auto-update.html#automatic-reload

About web manifest, you can use a simple tsx component using `virtual:pwa-info`, I'm not an expert on Solid, update if necessary:
```ts
/// <reference types="vite-plugin-pwa/info" />
import { Link } from "solid-start"; // if missing, just use html <link> tag
import { pwaInfo } from 'virtual:pwa-info';

export function VitePwaManifest() {
  if (pwaInfo) {
    const { webManifest } = pwaInfo;
    if (webManifest) {
      const { href, useCredentials } = webManifest
      return (
        <>
          { useCredentials
            ? <Link rel="manifest" href={href} crossorigin="use-credentials" />
            : <Link rel="manifest" href={href} />
          }
        <>
      )
    }
  }
  return null;
}
```

**Comment by userquin** [comment]
@seeplusplus 
If the integration with Solid-Sart requires managing SSR or ISLANDS we could change our mind, the integrations with meta frameworks are only to avoid having to deal with the configuration to build the service worker, just check any of them.

I can upload a repository to my account and see what it comes up with, then it's a nuance to transfer it here.

**Comment by seeplusplus** [comment]
@userquin Thanks for the help! These suggestions work perfectly!

Everything is in this repo,

https://github.com/seeplusplus/solid-start-vite-pwa

 but it's basically as you said, I just added the `useRegisterSW` and `pwaInfo` imports to my `root.tsx` and everything worked.

I opened #468 in case anyone else finds themselves similarly looking to get started using this project with SolidStart.

**Comment by yume-chan** [comment]
@seeplusplus I can't get your repo (https://github.com/seeplusplus/solid-start-vite-pwa) working.

After `pnpm i`, `npm run buidl` and `npm start`, I got this error in browser console:

```
Uncaught (in promise) non-precached-url: non-precached-url :: [{"url":"index.html"}]
    at E.createHandlerBoundToURL (http://localhost:3000/workbox-e0782b83.js:1:13533)
    at Object.createHandlerBoundToURL (http://localhost:3000/workbox-e0782b83.js:1:15140)
    at http://localhost:3000/sw.js:1:1474
    at http://localhost:3000/sw.js:1:565
```

And after stopping the server, the web page doesn't work offline.
