### ISSUE TITLE
Pusher-js doesn't display on PWA production

### ISSUE THREAD

**Issue by MahmonirB** [vite-pwa/vite-plugin-pwa#466]
I have an issue with displaying push notification on PWA, it works in development env but after build and deploy doesn't show anything. What should I do and how to set/modify/define pusher-js config into vite?

- vite.config.ts file:
```
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'prompt',
      includeAssets: ['favicon.ico', 'apple-touch-icon.png', '**/*.{png}'],
      manifest: {
        id: '1.0.1',
        name: 'Anime Suche',
        short_name: 'Anime',
        theme_color: '#fff',
        start_url: '/',
        display: 'standalone',
        orientation: 'portrait',
        icons: [
          {
            src: '/favIcons/pwa-192x192.png',
            sizes: '192x192',
            type: 'image/png',
          },
          {
            src: '/favIcons/pwa-512x512.png',
            sizes: '512x512',
            type: 'image/png',
          },
        ],
      },
    }),
  ],
});

```
file that use pusher-js to show push-notofocation:
```
import React, { useEffect, useState } from 'react';
import Pusher from 'pusher-js';
import Alert from '../../components/alert/Alert';

interface PushBody {
    title: string;
    message: string;
}

function PushNotification() {
    const [notification, setNotification] = useState<any | undefined>();

    useEffect(() => {
        const pusher = new Pusher(`${import.meta.env.VITE_PUSH_API_KEY}`, {
            cluster: 'eu',
        });

        const channel = pusher.subscribe('my-channel');
        channel.bind('my-event', function (data: PushBody) {
            setNotification(data);
        });

        return () => {
            pusher.unbind();
            channel.unbind();
        }
    }, []);

    if (notification)
        return (
            <Alert
                title={notification?.title}
                content={notification?.message}
                onClose={() => setNotification(undefined)}
            />)

    return <></>;
}

export default PushNotification;

```

**Comment by userquin** [comment]
@MahmonirB I have no idea what is `Pusher-js`

**Comment by MahmonirB** [comment]
`pusher-js` is a package for managing push notification in client and server side. As I  wrote above, it works on dev mode, but after build and deploy on sever it does not work, I don't receive any push notification.

**Comment by userquin** [comment]
@MahmonirB it is an external dependency, you should file an issue on the corresponding repo. 

Are you receiving any error about pwa plugin such as sw registration error or similar or web manifest not shown in dev tools?

**Comment by MahmonirB** [comment]
@userquin yes I get error in reading manifest, in development I can find it into application tab in browser but in production is not found.

**Comment by userquin** [comment]
@MahmonirB the sw is registered and the web manifest is there:

![imagen](https://user-images.githubusercontent.com/6311119/218341945-2679339c-a069-4028-9034-86d66507b03a.png)

**Comment by userquin** [comment]
![imagen](https://user-images.githubusercontent.com/6311119/218342042-db47f3e6-82b3-4a67-858e-013d362c6c61.png)

**Comment by MahmonirB** [comment]
You're right, it works, I had to set pusher api key into environment variable in Vercel.
Thanks, Before that I was manipulating vite config.
