### ISSUE TITLE
Nuxt 3: Hydration Error in error.vue

### ISSUE THREAD

**Issue by SSbit01** [vite-pwa/vite-plugin-pwa#476]
Hi!

I recently worked on a website with Nuxt 3 and @vite-pwa/nuxt and noticed that the [`error.vue` page](https://nuxt.com/docs/getting-started/error-handling#rendering-an-error-page) has hydration errors when **PWA is enabled**.

**This bug doesn't appear the first time but occurs once the website gets cached.**

Here is the website: [https://handyvoid.com](https://handyvoid.com)
Example of a 404 page: [https://handyvoid.com/u](https://handyvoid.com/u)

Issue:

![Screenshot 2023-02-26 at 14-42-47 HandyVoid](https://user-images.githubusercontent.com/59541034/221414464-a9d318b7-8e7f-4ff3-8f8f-c5b7d28ba9db.png)

---

It should look like this:

![Screenshot 2023-02-26 at 15-05-01 HandyVoid](https://user-images.githubusercontent.com/59541034/221415558-949f6880-e596-4af6-9f9b-c47922f5fdfc.png)

**Comment by userquin** [comment]
@SSbit01 I cannot reproduce it https://streamable.com/q7x9vf

**Comment by SSbit01** [comment]
> @SSbit01 I cannot reproduce it https://streamable.com/q7x9vf

That's exactly the issue. In the 404 page, the content gets duplicated (hydration error). The bottom part shouldn't appear.
![error](https://user-images.githubusercontent.com/59541034/221415280-52e9c82a-772f-4eac-9b5c-01a024535c3a.png)

**Comment by SSbit01** [comment]
> > @SSbit01 I cannot reproduce it https://streamable.com/q7x9vf
> 
> That's exactly the issue. In the 404 page, the content gets duplicated (hydration error). The bottom shouldn't appear. ![error](https://user-images.githubusercontent.com/59541034/221415280-52e9c82a-772f-4eac-9b5c-01a024535c3a.png)

It should look like this
![Screenshot 2023-02-26 at 15-05-01 HandyVoid](https://user-images.githubusercontent.com/59541034/221415416-e5d77174-3a6a-4ac9-8ace-73ea454e92df.png)

**Comment by SSbit01** [comment]
It should look like this
![Screenshot 2023-02-26 at 15-05-01 HandyVoid](https://user-images.githubusercontent.com/59541034/221415499-fb9fd695-f5a4-4460-9335-cd89eb018c0d.png)

**Comment by userquin** [comment]
@SSbit01 ok, but there is no hydration error, hydration is not working properly: it works with a hard refresh.

I'm checking a few things, I'll ping you later...

**Comment by SSbit01** [comment]
> @SSbit01 ok, but there is no hydration error, hydration is not working properly: it works with a hard refresh.
> 
> I'm checking a few things, I'll ping you later...

Ok, thanks for the quick response!

**Comment by userquin** [comment]
@SSbit01 have you cnfigured the server as spa? I mean, redirecting anything to /? If so, try to remove the redirection, allow the server return 404 and nuxt should work properly.

For example, I have the same problem on this repo: https://github.com/antfu/vitesse-nuxt3/blob/main/netlify.toml#L9

On Elk, it is working properly, since netlify.toml is not redirecting and returning 404: check for example this missing page https://elk.zone/missing

![imagen](https://user-images.githubusercontent.com/6311119/221417849-78de02f2-ba8d-4e05-bae3-6bfb07d1a4bb.png)

**Comment by userquin** [comment]
Here there is no SPA: https://github.com/elk-zone/elk/blob/main/netlify.toml

**Comment by userquin** [comment]
@SSbit01 next time send the issue to nuxt integration repo :pray:

**Comment by userquin** [comment]
I need to review this more in deep

**Comment by SSbit01** [comment]
> @SSbit01 have you configured the server as spa? I mean, redirecting anything to /? If so, try to remove the redirection, allow the server return 404 and nuxt should work properly.
> 
> For example, I have the same problem on this repo: https://github.com/antfu/vitesse-nuxt3/blob/main/netlify.toml#L9
> 
> On Elk, it is working properly, since netlify.toml is not redirecting and returning 404: check for example this missing page https://elk.zone/missing
> 
> ![imagen](https://user-images.githubusercontent.com/6311119/221417849-78de02f2-ba8d-4e05-bae3-6bfb07d1a4bb.png)

Removing the fallback redirection solved the problem. Thank you so much!
