### ISSUE TITLE
Question: index.html refers to cache busted js file

### ISSUE THREAD

**Issue by SamLoys** [vite-pwa/vite-plugin-pwa#479]
Hello,
First of all thanks for this amazing plugin.

Currently, the vite build command adds a hash after the cs and javascript files for cache busting. 
I have the problem that after a long time of not opening the PWA, it will result in the index.html referrring to the old javascript file, which at this point is already removed from the server, and results in a module not available error. 
When this happens the user needs to close the PWA and open it again for it to work again. After a reload the index.html will refer to the new js file, and loading goes correctly.  

Is there a solution where I can change this behaviour?
 
<img width="842" alt="Screenshot 2023-03-01 at 14 24 40" src="https://user-images.githubusercontent.com/32015146/222162183-af2a1747-f9b0-47b6-8c26-034ba87df722.png">

**Comment by JoaoBelo-TWT** [comment]
I also notice this issue, any ideia?

**Comment by JoaoBelo-TWT** [comment]
anyway should be this one
https://github.com/vite-pwa/vite-plugin-pwa/issues/458

**Comment by SamLoys** [comment]
Actually found a simple solution. You can add onerror="window.location.reload" to your script tag.
