### ISSUE TITLE
exclude index.html from precache

### ISSUE THREAD

**Issue by AnilSonix** [vite-pwa/vite-plugin-pwa#481]
I have a react app where one route is normal but another route is **cross site isolated** (due to SharedArrayBuffer).
It was created with CRA (typescript pwa template).
I do a full-page reload when navigated to the cross-site isolated one, that's why I ignore the index.html in precache so that it can work.
cross site isolation headers are configured in netlify.toml.

I am thinking of moving to vite.
Is it possible to remove index.html from precache in vite-plugin-pwa?
I know it defeats the purpose of the offline factor.

**Comment by userquin** [comment]
@AnilSonix it depends on your needs, you can use pwa plugin without precache manifest, configure `workbox.navigateFallback = null`, but then your app will not work on offline.

**Comment by AnilSonix** [comment]
> @AnilSonix it depends on your needs, you can use pwa plugin without precache manifest, configure `workbox.navigateFallback = null`, but then your app will not work on offline.

I want to precache all build artifacts except index.html.

**Comment by userquin** [comment]
@AnilSonix check this link https://developer.chrome.com/docs/workbox/modules/workbox-precaching/

**Comment by AnilSonix** [comment]
Thanks, globIgnore did the trick.

```
      workbox : {
        globIgnores : ["**/*.html"]
      }
```
