### ISSUE TITLE
Service worker does not get installed unless I refresh the page on React app

### ISSUE THREAD

**Issue by fiosman** [vite-pwa/vite-plugin-pwa#482]
Hello, 

I have a client side rendered react app built using Vite template `react-swc-ts` and I have a service worker configured using `VitePWA` plugin. I am using `strategies:generateSW` configuration and `registerType:prompt`. I am also using the default example `ReloadPrompt.tsx` and it seems to be working fine when I manually refresh the page but if I am already on the page and I push a new change, then navigate between pages (we use React Router) without refreshing, the prompt modal does not show up and the app still uses the old service worker. Only when I refresh does the prompt show up. Is there a way to show the prompt on page change?

Thanks

**Comment by userquin** [comment]
@fiosman check https://vite-pwa-org.netlify.app/guide/periodic-sw-updates.html

**Comment by fiosman** [comment]
> @fiosman check https://vite-pwa-org.netlify.app/guide/periodic-sw-updates.html

Thank you. But I think this may not work out for us. If a user is already on a page, and we push an update, the user won't see the update modal until 1 hour after.

**Comment by userquin** [comment]
@fiosman on the client side pwa plugin cannot solve that problem, maybe you can use some push capabilities on client and server app (if you have a server, I have no idea if it is an static or dynamic app): you can also check this https://developer.chrome.com/articles/periodic-background-sync/ (an example can be found here https://github.com/jeffposnick/yt-playlist-notifier), but it is not supported in all browsers.

**Comment by fiosman** [comment]
Ended up resolving this issue by manually updating the service worker on page change. We fetch the available registrations, and for every registration available we update it and send a SKIP_WAITING type message to our custom service worker file. Note, we had to change the `strategies` for VitePWA to be `injectManifest`.

**Comment by natsl05164** [comment]
> Ended up resolving this issue by manually updating the service worker on page change. We fetch the available registrations, and for every registration available we update it and send a `SKIP_WAITING` type message to our custom service worker file which has a `message` event handler. Note, we had to change the `strategies` for VitePWA to be `injectManifest`.

hi, i have the same issue. would you mind to share the code?   i am a total SW newbie...

**Comment by userquin** [comment]
https://vite-pwa-org.netlify.app/guide/periodic-sw-updates.html
