### ISSUE TITLE
Types regression

### ISSUE THREAD

**Issue by jacquesg** [vite-pwa/vite-plugin-pwa#490]
The recently released `0.14.5` version seems to have regressed. Now seeing the following:

```
error TS2305: Module '"virtual:pwa-register/react"' has no exported member 'RegisterSWOptions'.

3 import { RegisterSWOptions, useRegisterSW } from 'virtual:pwa-register/react';
           ~~~~~~~~~~~~~~~~~
```

**Comment by userquin** [comment]
@jacquesg do you have `vite-plugin-pwa/client` or `vite-plugin-pwa/react` in some dts or tsconfig/jsconfig file? it seems we have included a breaking change, module augmentation now should be explicit

**Comment by userquin** [comment]
Upps, sorry, that type is not exported, I Will try to fix it.

**Comment by userquin** [comment]
@jacquesg I'll release a new patch version (0.14.6) fixing the regression, thx for reporting the problem:

![imagen](https://user-images.githubusercontent.com/6311119/227189060-2a790c9d-06b4-43e6-ad11-57efa4a164a0.png)

**Comment by userquin** [comment]
@jacquesg fixed https://github.com/vite-pwa/vite-plugin-pwa/releases/tag/v0.14.6

**Comment by jacquesg** [comment]
@userquin Confirmed, thank you.
