### ISSUE TITLE
Is is possible to use own service worker injection with development build?

### ISSUE THREAD

**Issue by ceisele-r** [vite-pwa/vite-plugin-pwa#497]
Having the following VitePWA settings
```
{
        strategies: "injectManifest",
        injectRegister: null,
        registerType: "autoUpdate",
        srcDir: "src/serviceworker",
        filename: "sw.ts",
        manifest: {
          ...
        },
        devOptions: {
          enabled: true,
          navigateFallback: "index.html",
        },
}
```

and registering the serviceworker in our app itself, e.g. using 
```
const serviceWorkerPath = `/sw.js`;
const wb = new Workbox(serviceWorkerPath, {
  type: import.meta.env.MODE === "production" ? "classic" : "module",
});

wb.addEventListener("waiting", (event) => {
...
});

wb.register();
```

in the `main.tsx`, VitePWA injects the service worker registration again using a script tag that is added to the html page:
```
<script id="vite-plugin-pwa:register-dev-sw" type="module">
import registerDevSW from '/my/app/@vite-plugin-pwa/pwa-entry-point-loaded';
registerDevSW();
</script>
```

When turning  `devOptions.enabled` to false, the `dev-sw.js` is no longer compiled and served.

Is it possible to configure VitePWA to compile and serve the `dev-sw.js` but do not inject the `registerDevSW` script in the html page as this would result in a duplicate service worker registration call?

**Comment by userquin** [comment]
@ceisele-r you can configure `injectRegister: false` and manually register your custom service worker, if you want to also run your sw in dev, check this entry https://vite-pwa-org.netlify.app/guide/development.html#injectmanifest-strategy:
```ts
if ('serviceWorker' in navigator) {
  navigator.serviceWorker.register(
    import.meta.env.MODE === 'production' ? '/sw.js' : '/dev-sw.js?dev-sw'
  )
}
```
and next one in the docs about using static imports.

**Comment by ceisele-r** [comment]
Thanks @userquin but even when setting `injectRegister` to `false` (which I guessed results in the same as setting it to `null`), the virtual register code is still appended to the html page:
```
<script id="vite-plugin-pwa:register-dev-sw" type="module">
import registerDevSW from '/my/app/@vite-plugin-pwa/pwa-entry-point-loaded';
registerDevSW();
</script>
```

It does not seem to harm though, as my "own" sw registration comes first.

**Comment by userquin** [comment]
@ceisele-r that code is only injected when `devOptions.enabled = true`, and using `injectRegister: false`, previous script will not register the sw.

**Comment by ceisele-r** [comment]
@userquin ah ok, so it means the script will always be there but if `injectRegister` is set to `false`, it will noe execute the registration. Thanks!

**Comment by userquin** [comment]
@ceisele-r yeah, the script will add a ws listener for a custom ws event, and that event is not sent back to the client; it is only sent if not using a virtual module and using an inject register variant (inline or script) to register the sw, here the ws handler logic: https://github.com/vite-pwa/vite-plugin-pwa/blob/a79ae1d07d1f6259d9809ce32c1206f15d9e86e2/src/plugins/dev.ts#L205
