### ISSUE TITLE
nuxt 3, bad-precaching-response: The precaching request failed with an HTTP status of 500.

### ISSUE THREAD

**Issue by Timtendo12** [vite-pwa/vite-plugin-pwa#499]
Hi, Ive been using PWA for a while now without any issues, Now  I implemented Nuxt Middleware and whenever I redirect from my middleware I get the following error:

```
Uncaught (in promise) bad-precaching-response: The precaching request for 'http://localhost:3000/' failed with an HTTP status of 500.
    at PrecacheStrategy._handleInstall (http://localhost:3000/workbox-148cb7e5.js:2582:17)
    at async PrecacheStrategy._handle (http://localhost:3000/workbox-148cb7e5.js:2511:18)
    at async PrecacheStrategy._getResponse (http://localhost:3000/workbox-148cb7e5.js:2360:22)
```

nuxt.config.ts pwa section:
```
  pwa: {
    registerType: "autoUpdate",
    manifest: {
      name: "AppName",
      short_name: "AppName",
      theme_color: "#35B05F",
      background_color: "#FFFFFF",
      icons: [
        {
          src: "/img/pwa-192x192.png",
          sizes: "192x192",
          type: "image/png",
        },
        {
          src: "/img/pwa-512x512.png",
          sizes: "512x512",
          type: "image/png",
        },
      ],
    },
    workbox: {
      navigateFallback: "/",
      globPatterns: ["**/*.{js,css,html,ico,png,jpg,jpeg,svg}"],
    },
    devOptions: {
      enabled: true,
      type: "module",
    },
  },
```

**Comment by userquin** [comment]
@Timtendo12 what's the error? the middleware/server is sending 500 status code

**Comment by Timtendo12** [comment]
> Uncaught (in promise) bad-precaching-response: The precaching request for 'http://localhost:3000/' failed with an HTTP status of 500.
>     at PrecacheStrategy._handleInstall (http://localhost:3000/workbox-148cb7e5.js:2582:17)
>     at async PrecacheStrategy._handle (http://localhost:3000/workbox-148cb7e5.js:2511:18)
>     at async PrecacheStrategy._getResponse (http://localhost:3000/workbox-148cb7e5.js:2360:22)

The error was that Window was not defined, I fixed this by only running the middleware on the client side but im not sure if thats the optimal solution to this issue.

**Comment by userquin** [comment]
can you try prerendering `/`?
```ts
  routeRules: {
    // Static generation
    '/': { prerender: true },
    /* other options */
  }
```

**Comment by userquin** [comment]
and also prevent running the middleware on server:
 ```ts
  if (process.server)
    return
```

**Comment by Timtendo12** [comment]
> ```ts
>   routeRules: {
>     // Static generation
>     '/': { prerender: true },
>     /* other options */
>   }
> ```

I already did this and this removed the error for me.
