### ISSUE TITLE
[Question] How to custom pwa install menu?

### ISSUE THREAD

**Issue by Nemure231** [vite-pwa/vite-plugin-pwa#500]
Hi, i am ask this after find out that https://tauri.app have nice install menu, that place in the bottom of my screen.
![Screenshot_20230408-012025](https://user-images.githubusercontent.com/49015080/230658694-09195855-c3f6-412b-b8ed-8d2543d1898c.png)

What should i config to have the same install menu like that? I don't know what keyword to searching in the internet. Many thanks

**Comment by userquin** [comment]
@Nemure231 you can listen to a custom event, but is is not supported bu all browsers: https://web.dev/customize-install/

I've configured a custom one on Elk (Nuxt 3 and Vue 3), you can find it here https://github.com/elk-zone/elk/blob/main/modules/pwa/runtime/pwa-plugin.client.ts and rhe component here https://github.com/elk-zone/elk/blob/main/components/pwa/PwaInstallPrompt.client.vue

![Screenshot_20230407_213430_Chrome](https://user-images.githubusercontent.com/6311119/230666963-110c3e8f-34f7-4555-8eab-255979f88ac0.jpg)

**Comment by Nemure231** [comment]
![Screenshot_20230408-045453](https://user-images.githubusercontent.com/49015080/230683778-2c910869-7c00-4ae0-8212-ef08d9070947.png)

Hi @userquin, to be honest, i am aleady following your method with custom install and update button for my project. Yes, its works really well.

What i am asking is, the native browser popup. Elk have mini popup that placed in the middle of screen after we clicked the install button.

But tauri website, is showing native browser popup from the bottom of page, information like with title, desc, img. I mean its feels like native brower menu, like not part of the web, its i can slide it down or up to open.

I found it, its called PWAmp here. https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable#customizing_the_installation_prompt

**Comment by userquin** [comment]
You cannot replace that popup

**Comment by Nemure231** [comment]
@userquin 

Oh, nevermind, i figured it. Looks like i just need to set some screenshot in my manifest, and then magically the native popup come from bottom of page... 🤯

Reference:
https://www.stefanjudis.com/notes/how-to-define-progressive-web-app-pwa-screenshots-and-shortcuts/
