### ISSUE TITLE
Including `vite-plugin-pwa/client` in types in `tsconfig.json` in a React project with Vitepress for documentation changes all `JSX` types to `ReactElement<any, string | JSXElementConstructor<any>> | null`

### ISSUE THREAD

**Issue by tresabhi** [vite-pwa/vite-plugin-pwa#507]
I have a React project and I wanted to use Vitepress for my documentation. Everything works perfectly fine and all type definitions are properly set up. However, since both Vitepress and my React project use Vite, including `vite-plugin-pwa/client` in my `tsconfig.json` "leaks" Vue typings into my React project. Only the typing of my React project broke. The Vitepress site compiles without any errors.

Source code: https://github.com/tresabhi/stellar
Documentation website: https://tresabhi.github.io/stellar/

tsconfig.json
```json
    "lib": ["DOM", "DOM.Iterable", "ESNext", "ES6", "WebWorker"],
    "types": [
      "vite/client",
      "vite-plugin-svgr/client",
      "vite-plugin-pwa/client"
    ],
    "allowJs": false,
```

Removing `vite-plugin-pwa/client` solves the issue but removes typings for the `virtual:pwa-register` module which is not sub optimal. The entries for `types` other than `virtual:pwa-register` do not cause any issues.

**Comment by userquin** [comment]
@tresabhi try using `vite-plugin-pwa/react` instead client, check release page, we split the types (we need to update the docs): if still not working try upgrading to 0.14.7.

**Comment by tresabhi** [comment]
I apologize for the delayed response. This solved the issue. However, now I do have to rewrite a good chunk of the startup code to use the `useRegisterSW` hook instead of `registerSW`.

**Comment by userquin** [comment]
@tresabhi IIRC you have also `vite-plugin-pwa/vanillajs`

**Comment by tresabhi** [comment]
In my code or as an available option? I was able to switch to the use hook no problem. Thanks you for your help; this would've been impossible otherwise \:\)

**Comment by tresabhi** [comment]
I think the hook has a "vibe" to it. I'll stick to it.

**Comment by userquin** [comment]
@tresabhi just add `/// <reference types="vite-plugin-pwa/vanillajs" />` at top of `src/utilities/preroot.tsx`, remove the `@ts-ignore` and remove entry from `src/types/Global.d.ts`: 
```ts
/*
  module 'virtual:pwa-register' {
    export function registerSW(
      options?: RegisterSWOptions,
    ): (reloadPage?: boolean) => Promise<void>;
  }

*/
```

![imagen](https://user-images.githubusercontent.com/6311119/235679885-73d7b2c0-5da2-4813-a695-3638b1b281fb.png)
