### ISSUE TITLE
Can't get @vite-pwa/sveltekit to work out-of-the-box

### ISSUE THREAD

**Issue by Nickersoft** [vite-pwa/vite-plugin-pwa#512]
Hey folks,

After reading the docs over and over, I can't for the life of me figure out why I'm having so much trouble building my project with `@vite-pwa/sveltekit`. I based most of my implementation off of [this repo](https://github.com/aromalanil/WhatSend), which successfully uses the plugin, yet when I try to build I receive:

```
warnings
  One of the glob patterns doesn't match any files. Please remove or fix the following: {
  "globDirectory": "/Users/tjnickerson/Documents/GitHub/Nickersoft/vite-pwa-repro/.svelte-kit/output",
  "globPattern": "client/**/*.{js,css,ico,png,svg,webp,webmanifest}",
  "globIgnores": [
    "**/node_modules/**/*",
    "server/sw.js",
    "server/workbox-*.js"
  ]
}
  One of the glob patterns doesn't match any files. Please remove or fix the following: {
  "globDirectory": "/Users/tjnickerson/Documents/GitHub/Nickersoft/vite-pwa-repro/.svelte-kit/output",
  "globPattern": "prerendered/**/*.html",
  "globIgnores": [
    "**/node_modules/**/*",
    "server/sw.js",
    "server/workbox-*.js"
  ]
}

[vite-plugin-pwa:sveltekit:build] ENOENT: no such file or directory, open '/Users/tjnickerson/Documents/GitHub/Nickersoft/vite-pwa-repro/.svelte-kit/output/client/sw.js'
error during build:
Error: ENOENT: no such file or directory, open '/Users/tjnickerson/Documents/GitHub/Nickersoft/vite-pwa-repro/.svelte-kit/output/client/sw.js'
 ELIFECYCLE  Command failed with exit code 1.
```

Removing the custom code I have in `+layout.svelte` seems to fix the build, even though the code I put in there is verbatim from the docs. The reason the plugin can't find the above file is because `sw.js` instead lives in `.svelte-kit/server`, not `client`.

My reproduction repo is [here](https://github.com/Nickersoft/vite-pwa-repro). You just run `pnpm install` and then `pnpm build`. Any pointers would be appreciated.

**Comment by userquin** [comment]
@Nickersoft try using latest kit version, and please use `@vite-pwa/sveltekit` repo.

**Comment by Nickersoft** [comment]
Whoops! Sorry, assumed this was a monorepo. Opened a [new issue](https://github.com/vite-pwa/sveltekit/issues/49) over there.

**Comment by Nickersoft** [comment]
Also, I didn't realize `npm create svelte` doesn't land you with the latest version of SvelteKit. I upgraded to the latest (1.16.2), but the error still persists.
