### ISSUE TITLE
[Question] manifest.json name and file reference

### ISSUE THREAD

**Issue by garrett-wombat** [vite-pwa/vite-plugin-pwa#518]
[Question] Two questions:
1) would it be better to allow for users to rename their manifest using the `[hash]` syntax. As it should be cached, and its not best practice to cache non versioned files.
2) would it be an accepted update if the manifest config was extended to allow for reference to an already existing manifest.json file. Potential config update being he addition of `manifestFile: path.join(__dirname, 'public','manifest.json')`.

Would either or both of these changes have a change at getting merged?

**Comment by userquin** [comment]
@garrett-wombat 
> would it be better to allow for users to rename their manifest using the [hash] syntax. As it should be cached, and its not best practice to cache non versioned files.

Don't do this: if you add hash to manifest.webmanifest file you will end up with 404, change cache headers to always return 200 with must-revalidate, check this https://vite-pwa-org.netlify.app/deployment/#cache-control

> would it be an accepted update if the manifest config was extended to allow for reference to an already existing manifest.json file. Potential config update being he addition of manifestFile: path.join(__dirname, 'public','manifest.json').

No, you have 2 options:
- change manifest entry to `manifest: false` and then add the webmanifest link manually to all html files
- read the webmanifest json file and pass it to manifest entry in pwa options: can be done from user land
