### ISSUE TITLE
0.15.0 uses the wrong path to output custom sw.js

### ISSUE THREAD

**Issue by sheremet-va** [vite-pwa/vite-plugin-pwa#522]
Reproduction: https://github.com/sheremet-va/pwa-repro-custom-sw

Run:

```
pnpm install
pnpm build
```

`vite-plugin-pwa` resolves the output path relative to the cwd instead of the project root like other files are resolved to.

- cwd: `/reproductions/pwa`
- root: `/reproductions/pwa/src`
- actually sw.js output: `/reproductions/dist/sw.js`
- expected sw.js output: `/reproductions/pwa/dist/sw.js` (`injectionManifest.swDest` is resolved correctly, it tries to load the file, but it's not there)

**Comment by userquin** [comment]
@sheremet-va so, do you want the sw in another dist folder? If I run build in your repro, Vite is generating the build in dist folder

**Comment by sheremet-va** [comment]
> @sheremet-va so, do you want the sw in another dist folder? If I run build in your repro, Vite is generating the build in dist folder

Build is generated in dist folder which is ok. `sw,js` is not generated in dist folder.

**Comment by userquin** [comment]
> Build is generated in dist folder which is ok. `sw.js` is not generated in dist folder.

Testing with previous version `0.14.7` the sw is generated in `<root>/dist` folder, using latest version not working, it is failing.

I'll check what's the problem, I guess missing root in sw build using Vite `build` module.
