### ISSUE TITLE
Exclude API backend on VueJS

### ISSUE THREAD

**Issue by francoism90** [vite-pwa/vite-plugin-pwa#532]
```ts
workbox: {
        globPatterns: ['**/*.{css,js,html,svg,png,ico,txt,woff2}'],
        navigateFallbackDenylist: [/^\/api/]
},
```
This doesn't seem to always work, like when calling `https://localhost/api/media/foo.jpg`.
This is my proxy: `https://localhost/api` to my backend.

Is this normal? I need to call static content from my API.

Thanks

**Comment by userquin** [comment]
@francoism90 I have no idea what's your problem, but you shouldn't use the same host, use Vite proxy instead. What are the host:port for vuejs app and api?

I have no idea if your api requests in production will go to the same host, if so, previous configuration should work. If production api is in another host, you don't need `navigateFallbackDenylist`.

**Comment by francoism90** [comment]
@userquin Thanks for your reply.

The problem is that I'm using a nginx server, with a proxy path to my api backend.
So they are using the same host, but the worker intercepts everything that ends with an extension for some reason.

```
https://localhost <-- PWA
https://localhost/api/v1 <-- shows json
https://localhost/api/v1/thumbnail.jpg <-- shows 404 - even when exits on API
```
The only workaround is using a different domain, but this requires CORS, etc.

**Comment by userquin** [comment]
@francoism90 start you nginx server in another port, for example 8080, then add this entry to your vite config file, and just use always local requests: 
```ts
  server: {
    proxy: {
      '/api': {
        target: 'http://localhost:8080',
        changeOrigin: true,
      },
    },
  },
```

**Comment by userquin** [comment]
@francoism90 I suggest you to test it first on local using http instead https, then you can start testing https.

How do you serve your vuejs app in production, via nginx or in separated servers?

I use Apache (SSL) + Tomcat or only Netty (SSL) behind HA Proxy, in both cases the backend serving vuejs app, so you will need to deal with it. In my case I just test the app on local only using http via Vite proxy, to test production I build the app and start only my backend (in your case nginx).

**Comment by francoism90** [comment]
@userquin Thanks for answer. :)

I made a configuration issue, see https://www.digitalocean.com/community/tutorials/understanding-nginx-server-and-location-block-selection-algorithms

Turns out I used the wrong regex: `location ^~ /api {`
Now it matches with extensions as well.

Sorry for the noise, but thanks for the help.
