### ISSUE TITLE
[Question] How to set pwa manifest start_url to be dynamic?

### ISSUE THREAD

**Issue by Nemure231** [vite-pwa/vite-plugin-pwa#533]
The use case is pretty simple, lets say i have login cookie named "login", i want to check if there is the cookie still active, then the start_url will be redirect into '/dashboard' else it will redirect into home '/'

This is my latest code.

```JS
function gettCookie(name: string) {
   
        const match = document.cookie.match(new RegExp('(^| )' + name + '=([^;]+)'));
        if (match) {
            return match[2]
        }
   
    return null
}
```

My manifest setting
```JS
 {
        id: '/,
        scope: '/,
        start_url: gettCookie('login) ? '/dashboard' : '/',
        ...
}
```

My cookie function is fine, i can confirm that i can get that cookie value, but the problem is.. is this method can be work in pwa module? I try it and it doesn't work, any idea how can i do this? Many thanks

**Comment by userquin** [comment]
cannot be done, it is generated in build time, just keep `/` route, what's the problem (server redirect instead client redirect)?

**Comment by Nemure231** [comment]
no server things, just in on client to check the cookie, the cookie is also not httponly, so i can get it with document.cookie. 

Oh, alright, if there is no other option, i should set it with '/' thanks

**Comment by sk-tjdownes** [comment]
> cannot be done, it is generated in build time, just keep `/` route, what's the problem (server redirect instead client redirect)?

I don't think this is entirely true. You can reset the start URL in the head of your index file. Be sure to also set the scope. I am currently doing this and it seems to be working fine. I'm new to the whole PWA space, so maybe there's an issue I haven't come across yet. if so, please let me know.

```
 <script>
			async function transformManifest() {
				const url = '/manifest.webmanifest'
				const manifest = await ((await fetch(url)).json())
				const path = location.pathname.split('/')
				const subpath = path[1]
				manifest.start_url = path && subpath? window.location.origin + '/' + subpath : window.location.href
				manifest.scope = path && subpath ? window.location.origin + '/' + subpath : window.location.href
				manifest.id = '/'
				const manifestString = JSON.stringify(manifest)
				const blob = new Blob([manifestString], {type: 'application/json'})
				const manifestURL = URL.createObjectURL(blob)
				document.querySelector('[rel="manifest"]').setAttribute('href', manifestURL)

				return Promise.resolve(manifestURL)
			}

			transformManifest()
    </script>
```

**Comment by sk-tjdownes** [comment]
Just to add to the above, with some apps the scope will not always be root. In our case, the root is a basic marketing page that most users will never see. It's there in case someone goes to the root url, but the actual scope of the app is a url paramter, like `https://123xyzdomain.com/customername`

**Comment by userquin** [comment]
You can change in the client everything, my previous comment was about `manifest` entry in PWA plugin configuration...

**Comment by Nemure231** [comment]
@sk-tjdownes 

hey, thanks for your example and the testimony, i will give it try!
