### ISSUE TITLE
React client plugin useRegisterSW hook is not correctly implemented

### ISSUE THREAD

**Issue by hikariNTU** [vite-pwa/vite-plugin-pwa#536]
The `useRegisterSW` hook do not accept any "reactive" options been provided as params. The returned `updateServiceWorker` will use the initial given functions, options for its references.

https://github.com/vite-pwa/vite-plugin-pwa/blob/31ccaa89bb18b7d39f8d150435b26d33dfee04dd/src/client/build/react.ts#LL20C1-L35C5

```ts
const [updateServiceWorker] = useState(() => {
    return registerSW({
      immediate,
      onOfflineReady() {
        setOfflineReady(true)
        onOfflineReady?.()
      },
      onNeedRefresh() {
        setNeedRefresh(true)
        onNeedRefresh?.()
      },
      onRegistered,
      onRegisteredSW,
      onRegisterError,
    })
  })
```

A correct way to implement it is to use `useCallback` or `ref` for the function instead of this `useState` hack. But it will call the `registerSW` multiple time if the given options are changed.

I do not know how many websites out there have been impacted since this might be an edge case which most of the people using this library will do some simple setup instead of relying of the options provided to the hook. And fixing it might need a full rewrite for `registerSW` function.

@userquin What's your thought on this issue? Should be mentioned on documentation if this is intended behavior

**Comment by userquin** [comment]
closed via https://github.com/vite-pwa/docs/pull/52
