### ISSUE TITLE
[Question] How i can check what is files need to update with prompt scheme + periodic update ?

### ISSUE THREAD

**Issue by evdevru** [vite-pwa/vite-plugin-pwa#543]
I have fantom updates and i want to check what files are triggered that. How i can get what files need to update ?

Code:

register:
```ts
const { useRegisterSW } = await import('virtual:pwa-register/vue')

      const { needRefresh, updateServiceWorker } = useRegisterSW({
        immediate: true,
        onRegistered(r) {
          r
            && setInterval(async () => {
              try {
                await r.update()
              }
              catch (e) {
                console.error('Worker', e)
              }
            }, 30000)
        },
      })
```

config:
```ts
VitePWA({
        base: '/',
        scope: '/',
        workbox: {
          globPatterns: ['**/*.{js,css,ico,png,svg,ttf,woff,eot}', 'fallback.html'],
          skipWaiting: false,
          clientsClaim: true, 
          navigateFallbackDenylist: [/^\/api/],
          navigateFallback: 'fallback.html',
        },
        manifest: {
          scope: '/',
          id: '/',
          icons: []
        },
        devOptions: {
          enabled: false, // isDev,
          // type: "module",
          navigateFallback: 'index.html',
        },
      })
```

**Comment by userquin** [comment]
@evdevru you can checl the caches, should exists an entry with your host, there you have last update timestamp, I don't remember if you can sort the table

**Comment by evdevru** [comment]
> @evdevru you can check the caches, should exists an entry with your host, there you have last update timestamp, I don't remember if you can sort the table.
> 
> ![imagen](https://user-images.githubusercontent.com/6311119/250298893-c5c5d6fd-09ae-495f-b7de-86798b748dd0.png)

I cant check what is updated. If worker was updated then all files has new date, but really i dont have new build
