### ISSUE TITLE
navigateFallbackDenylist is not working with generateSW Strategy

### ISSUE THREAD

**Issue by ad1992** [vite-pwa/vite-plugin-pwa#546]
Hi I want to exclude contents of locales folder completely from getting pre-cached however thats not working.
And similarly the runtime cache for locales folder also doesn't work.

The locales folder is inside `src/locales/*.json` and I want to avoid precaching locales folder, however even after adding to `navigateFallbackDenylist` it still gets pre-cached under assets.

<img width="677" alt="Screenshot 2023-07-11 at 1 49 48 PM" src="https://github.com/vite-pwa/vite-plugin-pwa/assets/11256141/e2b46a92-2946-4904-b0ec-947495f81880">

This is how I do it 👇🏻 
```
navigateFallbackDenylist: [new RegExp("locales/[^/]+.json")]
```
Is this because locales are not inside `public` folder but `src` ? However since I am using it in code to import so I cannot move it outside `src` folder.

Please let me know how can I fix this If I want to use `generateSW` strategy

**Comment by userquin** [comment]
@ad1992 the regex is applied to the build/dist folder not to the src folder. Try adding a custom regex for locale assets, something like this `/^[a-z]{2}-[A-Z]{2}\./`

**Comment by userquin** [comment]
If you want to exclude them also from sw precache you need to add similar glob pattern to ignore entry

**Comment by ad1992** [comment]
> If you want to exclude them also from sw precache you need to add similar glob pattern to ignore entry.
> 
> EDIT: you can also add a `manifestTransform` to filter out those entries: https://github.com/vite-pwa/vite-plugin-pwa/blob/main/examples/sveltekit-pwa/pwa-configuration.js#L61-L79

@userquin thank you so much for the suggestion! Adding `manifestTransform` actually works for me in local but not in production, any idea why that would happen ?
and here is the preview for reference https://excalidraw-39qbvraqa-excalidraw.vercel.app/

**Comment by userquin** [comment]
@ad1992 

The json files are converted to js files when you build the repo, and so you need to exclude the js files, not the json files.
`workbox-build` will run against the dist folder, change the manifest transform with this one:
:
```ts
  manifestTransforms: [
      (entries) => {
        const manifest = entries.filter(({ url }) => !/assets\/[a-z]{2}-[A-Z]{2}-[]\.js$/.test(url))
        return { manifest };
      },
    ],
```

You can add a similar regex to the runtime config for the locales.

Wow, great PR.

**Comment by userquin** [comment]
![imagen](https://github.com/vite-pwa/vite-plugin-pwa/assets/6311119/e31766e6-84fe-4d30-9bbd-dc08a40bd425)

**Comment by userquin** [comment]
![imagen](https://github.com/vite-pwa/vite-plugin-pwa/assets/6311119/9b0df554-0c67-471c-a5ce-a20463cdabdc)

**Comment by ad1992** [comment]
@userquin filtering the assets works but I am not sure if this would be the best way to do it as its not necessary to follow the specific format eg the below ones will still be pre-cached since its a different format and similarly more could in future

<img width="737" alt="Screenshot 2023-07-12 at 11 13 22 AM" src="https://github.com/vite-pwa/vite-plugin-pwa/assets/11256141/ae3b500e-1d0a-4e54-bc9d-96b6c466715c">

Hence if there is some way so we can say anything inside `locales` folder shouldn't be pre-cached instead of checking the content of locales and matching them with regex, this way it would be easier for longer term as lang format could change.

Also I am trying similar regex with `assets` for runtime cache but it doesn't work and doesn't create locales folder, so anything additional I need to do to create `locales` runtime cache ?

And one last question for some reason `fonts.css` doesn't get cached under runtime cache `fonts`
<img width="715" alt="Screenshot 2023-07-12 at 11 20 42 AM" src="https://github.com/vite-pwa/vite-plugin-pwa/assets/11256141/053cf525-3a00-4321-ba69-abc477911303">

Thanks again for helping out!

**Comment by userquin** [comment]
@ad1992 maybe you need to modify assets names for any locale and move it to a custom folder (`locales/` for example), then you can use `workbox: { globIgnores: ['locales/**'] }`.

I'll check your vite config file in the PR

**Comment by userquin** [comment]
> And one last question for some reason `fonts.css` doesn't get cached under runtime cache `fonts`

Runtime caching will not include any resource in first request, it will be included in the cache in next navigation:

![imagen](https://github.com/vite-pwa/vite-plugin-pwa/assets/6311119/e671b3cd-351a-4385-977a-da8c9a19a2d4)

![imagen](https://github.com/vite-pwa/vite-plugin-pwa/assets/6311119/8dd01da1-242c-49b1-9838-6f2715914aa8)

**Comment by ad1992** [comment]
> > And one last question for some reason `fonts.css` doesn't get cached under runtime cache `fonts`
> 
> Runtime caching will not include any resource in first navigation, it will be included in the cache in next navigation:
> 
> ![imagen](https://user-images.githubusercontent.com/6311119/252944970-e671b3cd-351a-4385-977a-da8c9a19a2d4.png)
> 
> ![imagen](https://user-images.githubusercontent.com/6311119/252945030-8dd01da1-242c-49b1-9838-6f2715914aa8.png)

Hey yep thats right but you notice `font.css` is not in the `fonts` cache, its in workbox pre-cache instead, thats what I was referring to, I am trying to push it in `fonts` cache instead via the config.

**Comment by userquin** [comment]
@ad1992 you can exclude it using `workbox.globIgnore` option

About moving your locale files: check this https://rollupjs.org/configuration-options/#output-manualchunks, there is a similar example

**Comment by userquin** [comment]
@ad1992 I've notice you're using auto register without any virtual (registerSW.js), the app will not update until next navigation when a new version found (open app in a new browser session or hard refresh), the current  sw will not claim all controlled clients.

I have no idea how do you store client state, if you're using local storage or IndexedDB, you can add a new module importing it in the entry point or use dynamic import (you will need to add `vite-plugin-pwa/vanillajs` to tsconfig or use triple slash reference):
```ts
import('virtual:pwa-register').then(({ registerSW }) => registerSW({ immediate: true }))
```

Check the warning in the docs: https://vite-pwa-org.netlify.app/guide/auto-update.html#automatic-reload

**Comment by ad1992** [comment]
@userquin thats right I am using auto register right now without virtual module. We store the data in local storage. One concern when using automatic reload is if this could lead to some inconsistent user experience / race condition due to which LS data could get overridden resulting in loss of data ?
I might be completely wrong and I am not sure if this would ever happen but since the browser tabs will be automatically reloaded when user is using the app so just little worried about the overall user experience. 
Would like to hear your thoughts on the same as well

**Comment by userquin** [comment]
> thats right I am using auto register right now without virtual module. We store the data in local storage. One concern when using automatic reload is if this could lead to some inconsistent user experience / race condition due to which LS data could get overridden resulting in loss of data ?

Yes, that's the main problem (lose data and page reload); you can also switch to prompt for update, but it will need some additional work to add the dialog to reload the app.

> I might be completely wrong and I am not sure if this would ever happen but since the browser tabs will be automatically reloaded when user is using the app so just little worried about the overall user experience.

That's why I'm asking you, using the virtual will automatically reload the app once the new sw installed and activated, I use it only in docs websites (with the exception of PWA docs).

**Comment by userquin** [comment]
A few months/years ago I added the pwa with automatic reload to Layout It: https://github.com/Leniolabs/layoutit-grid/blob/main/src/App.vue

**Comment by ad1992** [comment]
> Yes, that's the main problem (lose data and page reload); you can also switch to prompt for update, but it will need some additional work to add the dialog to reload the app.

Thats the reason I didn't introduce automatic reload yet as I am little skeptical about data loss during page reload. 
Switching to prompt we would like to avoid since that would introduce an extra step for users to decide. 

So I am thinking is launch with current state (auto register) and see how it works and then introduce automatic reload as needed.

**Comment by ad1992** [comment]
Hi @userquin there is one issue I am facing and wanted to know in case you have any insights to share

Separating out the `locales` to `manualChunks` using rollup config is preventing the site from pre-caching the necessary assets for first load, is this expected behaviour ?

To reproduce 
1. You can visit https://excalidraw-50736k678-excalidraw.vercel.app/
2. Switch to offline
3. Refresh - the site won't load

if you try the same in https://excalidraw-aaakct09b-excalidraw.vercel.app/ it will work fine - this is before separating out locales to manual chunks

**Comment by userquin** [comment]
@ad1992 I Will check it later...

**Comment by userquin** [comment]
It seems it is working because the browser is caching the locale for en, check the first visit (using es), then switch to offline and refresh page will switch to en locale (check the network errors):

![imagen](https://github.com/vite-pwa/vite-plugin-pwa/assets/6311119/be4ff923-cba1-41b1-9e16-f82f3b57ffed)

**Comment by userquin** [comment]
I'll try to fix it with a simple repro test.

**Comment by userquin** [comment]
@ad1992 can you update to latest vite-plugin-pwa? you're using 0.14.7 and we've 0.16.4, also remove all workbox-** from dependencies (maybe you need to add `workbox-build 7.0.0` in devDependencies.

**Comment by ad1992** [comment]
Sure @userquin let me try upgrading
In prev url 2 languages were getting cached (due to wrong regex I think) and thats how I misunderstood it to be locales getting pre-cached

<img width="1038" alt="Screenshot 2023-07-25 at 3 01 30 PM" src="https://github.com/vite-pwa/vite-plugin-pwa/assets/11256141/6ec40ba7-3223-48f6-bedb-a5e49a3355f1">

**Comment by userquin** [comment]
@ad1992 I guess we also need to remove locales from sw precache, I mean, since it has a custom cache we should include the pattern in the `deny list`.

Here my changes to locales:
```ts
// workbox runtimeCaching entry
      runtimeCaching: [{
          urlPattern: ({ sameOrigin, url }) => sameOrigin && url.pathname.startsWith('/assets/locales/'),
          // urlPattern: new RegExp('locales/[^/]+.js'),
          handler: 'CacheFirst',
          options: {
            cacheName: 'locales',
            expiration: {
              maxEntries: 50,
              maxAgeSeconds: 60 * 60 * 24 * 30, // <== 30 days
            },
            // add this entry, we don't want to cache failing responses
            cacheableResponse: {
              statuses: [200],
            },
          },
        }],
```

Then add this entry to `workbox`:
```ts
navigateFallbackDenylist: [/^\/assets\/locales\//],
```

**Comment by userquin** [comment]
If working we should apply the same for fonts and fonts.css entries.

**Comment by userquin** [comment]
@ad1992 we've the same `cacheName` for fonts and fonts.css file with distinct expiration options, we should store them in separated caches or include both in the regex

**Comment by ad1992** [comment]
@userquin was playing with it after upgrading and changes you suggested. 
So the issue with necessary assets not being pre cached still persists after upgrading

And as per `navigateFallbackDenylist`, I have the `globIgnores` which is taking care of not adding it in workbox precache so any special purpose of adding `navigateFallbackDenylist` ?

**Comment by userquin** [comment]
@ad1992 `globIgnores` is for build time, `navigateFallbackDenylist` is for runtime: `globIgnores` will prevent adding local assets to the sw precache manifest, while `navigateFallbackDenylist` will prevent the sw to intercept those requests at runtime.

**Comment by ad1992** [comment]
There is some weird behaviour which I am experiencing with different browsers (I am currently testing in local with preview build)

When changing only the url pattern regex from `new RegExp("locales/[^/]+.js")` -> `/^\/assets\/locales\//`

With this change in firefox - the first load starts pre- caching the en.json so on refresh with network disabled it works 
![image](https://github.com/vite-pwa/vite-plugin-pwa/assets/11256141/ecded1da-2468-483f-9b42-9bf7e5bb44fe)

however in chrome it doesn't since `en.json` isn't precached.

![image](https://github.com/vite-pwa/vite-plugin-pwa/assets/11256141/5b767f28-784f-42eb-93ec-a27a5ed8696c)

**Comment by userquin** [comment]
@ad1992 try adding the `navigationFallbackDenylist`

**Comment by userquin** [comment]
FF is caching the `en` json file, not the sw, the `Tranferred` column should be `service worker` and it is `cached`.

**Comment by ad1992** [comment]
> There is some weird behaviour which I am experiencing with different browsers (I am currently testing in local with preview build)
> 
> When changing only the url pattern regex from `new RegExp("locales/[^/]+.js")` -> `/^\/assets\/locales\//`
> 
> With this change in firefox - the first load starts pre- caching the en.json so on refresh with network disabled it works ![image](https://user-images.githubusercontent.com/11256141/255888808-ecded1da-2468-483f-9b42-9bf7e5bb44fe.png)
> 
> however in chrome it doesn't since `en.json` isn't precached.
> 
> ![image](https://user-images.githubusercontent.com/11256141/255888856-5b767f28-784f-42eb-93ec-a27a5ed8696c.png)

Also one more thing `locales` folder is no more created after regex updated in both browsers.
Yes for ff browser is caching `en.json` but for chrome browser isn't
with `navigateFallbackDenylist` as well the first reload issue isn't solved in chrome.


I will be afk for sometime. will post more updates once I am back.

**Comment by userquin** [comment]
@ad1992 I'll prepare an small repro...

**Comment by userquin** [comment]
@ad1992 one last thing, you should remove all the `workbox-**`  from `public/workbox` folder

**Comment by userquin** [comment]
@ad1992 here a small repro https://github.com/userquin/pwa-locales-custom-cache, I've enabled `mode: 'development'` and so we can check workbox messages:
- `pnpm install` (or `yarn` from root)
- `pnpm build && pnpm preview`

The problem is the cache for runtime caching, it not being created on first visit, you need refresh the page. I've added also png and ico files to the sw precache (to include pwa icons and screenshots).

You should also update the PWA theme color entry to match the theme color in the entry point.

**Comment by userquin** [comment]
It seems you're using Vercel, maybe we can add the `immutable` or `cache` header for these assets (fonts, font.css and assets/locales/*), this way the browser can use the cache

**Comment by ad1992** [comment]
> 



> @ad1992 here a small repro https://github.com/userquin/pwa-locales-custom-cache, I've enabled `mode: 'development'` and so we can check workbox messages:
> 
> * `pnpm install` (or `yarn` from root)
> * `pnpm build && pnpm preview`
> 
> The problem is the cache for runtime caching, it not being created on first visit, you need refresh the page. I've added also png and ico files to the sw precache (to include pwa icons and screenshots).
> 
> You should also update the PWA theme color entry to match the theme color in the entry point.
> 
> Using or removing the `navigateFallbackDenylist` option has the same result, will not work if go offline on first visit and refresh the page.

Yep thats whats happening right now so the only issue left is first visit and the going offline isn't working because `en.json` is not pre-cached. 
So earlier we were using CRA and in that `en.json` wasn't pre-cached separately I just checked in production https://excalidraw.com/ and I don't see it being cached in workbox pre-cache as well so looks like its bundled with the code as there is no separate call for `en.json`. 
![Screenshot 2023-07-25 at 8 18 28 PM](https://github.com/vite-pwa/vite-plugin-pwa/assets/11256141/3d8eb35f-59a3-4169-ac33-c54691f3ac44)

![Screenshot 2023-07-25 at 8 18 40 PM](https://github.com/vite-pwa/vite-plugin-pwa/assets/11256141/e8c46152-ad26-4ffb-92b4-606e4cb44952)

So even if you were at some language "x" on first visit and you go offline, its going to fallback to `en.json` since runtime cache isn't created until you refresh again and that I think is how service worker works ? 

So we cannot do anything about runtime cache but if we can bundle `en.json` so there is no separate call for it then the use case will be resolved. 

So what I can try is when creating manual chunks - consider all files except `en.json` and `percentages.json` then it will be considered part of main cache and that might help in overcoming the first load+offline issue

**Comment by ad1992** [comment]
looks like this strategy is working and first load + offline issue seems to be resolved  https://excalidraw-9xup84w1r-excalidraw.vercel.app/

**Comment by ad1992** [comment]
> @ad1992 I've notice you're using auto register without any virtual (registerSW.js), the app will not update until next navigation when a new version found (open app in a new browser session or hard refresh), the current sw will not claim all controlled clients.
> 
> I have no idea how do you store client state, if you're using local storage or IndexedDB, you can add a new module importing it in the entry point or use dynamic import (you will need to add `vite-plugin-pwa/vanillajs` to tsconfig or use triple slash reference):
> 
> ```ts
> import('virtual:pwa-register').then(({ registerSW }) => registerSW({ immediate: true }))
> ```
> 
> Check the warning in the docs: https://vite-pwa-org.netlify.app/guide/auto-update.html#automatic-reload

@userquin since I have disabled automatic reload so page won't auto reload which is fine and it won'r reload even after refresh unless "Hard refresh" is done  so is there a way to reload the page with regular refresh ?

If I just call `registerSW` without any options then what would be the behaviour ?
```
registerSW()
```

**Comment by userquin** [comment]
> @userquin since I have disabled automatic reload so page won't auto reload which is fine and it won'r reload even after refresh unless "Hard refresh" is done so is there a way to reload the page with regular refresh ?

No, only hard refresh or reopening the browser: check sw in dev tools, new sw will be awaiting (yellow flag)

> If I just call registerSW without any options then what would be the behaviour ?

Using any virtual pwa module will auto reload all client pages once new sw detected and activated (the sw will claim all clients controlled by previous sw, this event will fire the reload in all clients)

**Comment by ad1992** [comment]
@userquin  can you confirm if my understanding is correct ?
This is what I am seeing when testing 👇🏻 
1. with `registerType: autoUpdate` - The sw isn't updated unless until page refreshed. Once page refreshed it checks for sw and post that once page refreshed, the new changes are reflected
2. with calling `registerSW` - The sw isn't updated unless until page refreshed. Once sw is updated, the page is automatically reloaded.
3. `registerSW({immediate: true})` - Same as above (I am not seeing any difference)

Here is the URL - https://excalidraw-git-aakansha-fix-sw-reload-excalidraw.vercel.app/ and PR for reference - https://github.com/excalidraw/excalidraw/pull/6824

**Comment by userquin** [comment]
Auto update and page auto refresh is about the sw behaviour, if you want to auto check if there is a new version, you'll need to add periodic sync for updates: https://vite-pwa-org.netlify.app/guide/periodic-sw-updates.html (use the code in the example here https://vite-pwa-org.netlify.app/guide/periodic-sw-updates.html#handling-edge-cases)

**Comment by ad1992** [comment]
@userquin we shipped the sw with automatic reloading. But I have a query, so in chrome and firefox I had excalidraw.com opened with previous version (without automatic reload) and on refresh it it got updated with new one but on firefox it didn't and I had to hard refresh. 
What can we do to make sure it works the same for everyone browser and on refresh sw is actually updated ?
I can see sw is not being cached so it should have gotten updated on all browsers when refreshing.

**Comment by userquin** [comment]
It should work on next browser session or hard refresh on any browser (IIRC chrome fix it allowing to refresh the sw with jist f5, check closed issue 33 in pwa plugon repo). We cannot do anything.

**Comment by ad1992** [comment]
@userquin unfortunately there is one weird issue (probably related to SW / Vite I am not sure), in a browser which I haven't used for long time (lets say few months), in that If I open excalidraw.com, it goes to some older commit way before vite was pushed. So latest sw isn't getting fetched hence its older version.

So the change now is earlier we had our custom sw code and now vite is handling it, but looks like for browsers which were hardly used the changes are not getting updated as well. 

Any suggestion on what we can do to migrate everyone to vite ? 
Also let me know If I should open a different issue for this as its deviating from the topic of issue

**Comment by userquin** [comment]
uhmm, the service worker name was changed? I mean, what was the old service worker asset name? the current is sw.js

**Comment by ad1992** [comment]
yes it was `service-worker.js` earlier and now its `sw.js`

**Comment by userquin** [comment]
ok, I'll check the old sw behavior, open a new draft PR adding `service-worker.js` to public folder with this content, I'll check how do you register the old service-worker, the new app has been published?: 
```js
self.addEventListener('install', function(e) {
  self.skipWaiting();
});
self.addEventListener('activate', function(e) {
  self.registration.unregister()
    .then(function() {
      return self.clients.matchAll();
    })
    .then(function(clients) {
      clients.forEach(client => client.navigate(client.url))
    });
});
```

**Comment by userquin** [comment]
I guess previous code should work, the browser should update the service worker and once updated should remove it clearing all caches and reloading any client being still controlled by its previous version

**Comment by userquin** [comment]
@ad1992 you can test locally  if you rollback to previous service worker logic, then `build + preview` opening excalidraw in the browser, then restore the new version adding the new self destroying service-worker.js and run `build + preview` refreshing the page...

**Comment by userquin** [comment]
@ad1992 it is a lot of work, maybe you can apply the same steps:
- restore copy previous to the Vite PR migration, `build + preview` opening the app in the browser
- restore new sw logic, `build + preview` refreshing the app in the browser
- add self destroying service-worker.js,  `build + preview` refreshing the app in the browser

**Comment by ad1992** [comment]
> @ad1992 it is a lot of work, maybe you can apply the same steps:
> 
> * restore copy previous to the Vite PR migration, `build + preview` opening the app in the browser
> * restore new sw logic, `build + preview` refreshing the app in the browser
> * add self destroying service-worker.js,  `build + preview` refreshing the app in the browser

Let me try this in preview itself

**Comment by ad1992** [comment]
I am able to reproduce it in my PR https://github.com/excalidraw/excalidraw/pull/6833, Will try with your suggestion and it should get fixed

**Comment by ad1992** [comment]
@userquin the fix worked, thank you so much once again. You are awesome!
 I am not sure how / if its still possible to fix the other issue of sw worker getting cached before and after auto update, so I will create a reproducible scenario for that as well.

**Comment by userquin** [comment]
> I am not sure how / if its still possible to fix the other issue of sw worker getting cached before and after auto update, so I will create a reproducible scenario for that as well.

What do you mean? is the sw.js inside its precache? or are you referrring to this?
![imagen](https://github.com/vite-pwa/vite-plugin-pwa/assets/6311119/991745ec-1465-4c72-926e-b3b104039c88)

**Comment by userquin** [comment]
@ad1992 you should include `service-worker.js` in the `workbox.globIgnores` entry

**Comment by ad1992** [comment]
> > I am not sure how / if its still possible to fix the other issue of sw worker getting cached before and after auto update, so I will create a reproducible scenario for that as well.
> 
> What do you mean? is the sw.js inside its precache? or are you referrring to this? ![imagen](https://user-images.githubusercontent.com/6311119/257241230-991745ec-1465-4c72-926e-b3b104039c88.png)

I am referring to the other issue where sw didn't get updated for users before automatic reload vs after automatic reload as mentioned in https://github.com/vite-pwa/vite-plugin-pwa/issues/546#issuecomment-1655899326
so this would mainly happen for the users who would have sw before automatic reload was pushed which can happen in two cases
1. Users who hard reloaded post Vite was pushed without automatic reload (which would be very rare so we can ignore)
2. New users who landed on excalidraw.com after Vite was pushed without automatic reload (This is where we still would like to fix)

**Comment by ad1992** [comment]
Hi @userquin since all the queries related to integration were resolved so I am closing this. 

Thank you again for the help and support! I will open another issue for any future queries.
