### ISSUE TITLE
Qwik support

### ISSUE THREAD

**Issue by maiieul** [vite-pwa/vite-plugin-pwa#550]
Hi, I'm in the process of adopting Qwik and I am wondering how well it will work with vite-pwa, since Qwik is built on Vite. Are there any obstacles I should expect? Are you planning on adding a Qwik integration like for other frameworks?

**Comment by userquin** [comment]
It seems qwik will register a custom service worker, I'll check how can we integrate pwa plugin with it...

**Comment by userquin** [comment]
check https://github.com/QwikDev/pwa
