### ISSUE TITLE
Unable to reinstall PWA APP

### ISSUE THREAD

**Issue by lixianbin1** [vite-pwa/vite-plugin-pwa#555]
When I set it up with the minimal configuration of the PWA, I accessed it through the browser of my Android phone, and a message prompted me to install it was successfully displayed. When I install it, I remove the PWA APP on my phone. When I visited the website again, I was no longer prompted to install the PWA APP。

```
# vite.config.js

VitePWA({ 
    includeAssets: ['favicon.ico', 'favicon.svg'],
    manifest: {
      name: 'PWA-Example',
      short_name: 'Example',
      description: 'A PWA Example',
      theme_color: '#ffffff',
      icons: [
        {
          src: 'pwa-192x192.png',
          sizes: '192x192',
          type: 'image/png'
        },
        {
          src: 'pwa-512x512.png',
          sizes: '512x512',
          type: 'image/png'
        }
      ]
    },
    registerType: 'autoUpdate'
}),
```

**Comment by userquin** [comment]
@lixianbin1 that's weird, the prompt is shown by the browser, the plugin just registers the sw.
