### ISSUE TITLE
add-to-cache-list-conflicting-entries

### ISSUE THREAD

**Issue by rrd108** [vite-pwa/vite-plugin-pwa#556]
```
"vite-plugin-pwa": "^0.16.0",
"workbox-build": "^7.0.0"
```

`vite.config.ts`

```
VitePWA({
      registerType: 'autoUpdate',
      devOptions: {
        enabled: true,
        type: 'module', // need to be 'module' for HMR
      },
      includeAssets: ['favicon.ico', 'apple-touch-icon.png', 'masked-icon.svg'],
      manifest: {
        name: 'Sadhana App',
        short_name: 'Sadhana',
        description: 'Sadhana',
        theme_color: '#31003e',
        orientation: 'portrait',
        icons: [
          {
            src: 'android-chrome-192x192.png',
            sizes: '192x192',
            type: 'image/png',
          },
          {
            src: 'android-chrome-512x512.png',
            sizes: '512x512',
            type: 'image/png',
          },
        ],
      },
      workbox: {
        additionalManifestEntries: [{ url: 'index.html', revision: null }],
      },
    }),
```

With this setup, after build and deploy I get this error message on the borwser's console (real domain replaced with stars):

`Uncaught (in promise) add-to-cache-list-conflicting-entries: add-to-cache-list-conflicting-entries :: [{"firstEntry":"https://***/index.html?__WB_REVISION__=52ac5d9f0d316fa782fadb6a87eb3b76","secondEntry":"https://***/index.html"}]
    at O.addToCacheList (https://***/workbox-fa446783.js:1:11736)
    at O.precache (https://***/workbox-fa446783.js:1:11367)
    at https://***/workbox-fa446783.js:1:14994
    at Object.precacheAndRoute (https://***/workbox-fa446783.js:1:15006)
    at https://***/sw.js:1:673
    at https://***/sw.js:1:565`

I do not know how long I have this error, so I am not sure what update caused this, but about a month back, I had noo problem with this, and since then I did not touched any code related to the service worker.

**Comment by userquin** [comment]
Remove `additionalManifestEntries`, html files are added by workbox-build by default.
