### ISSUE TITLE
google auth stopped work with Service Worker

### ISSUE THREAD

**Issue by Todosiienko** [vite-pwa/vite-plugin-pwa#558]
Hello. I have SPA project which use Vue3, Vite, Firebase 9,  and vite-plugin-pwa to generate Service Worker.
Everything worked good but once when i tried to login with Google Auth it started to open the new window with my app without login. 
When i stop using pwa plugin and unregister previously registered SW i can login with Google without any problems.

My vite.config.js file looks like this 

```js
import vue from "@vitejs/plugin-vue";
import legacy from "@vitejs/plugin-legacy";
import { defineConfig } from "vite";
import { VitePWA } from "vite-plugin-pwa";

import path from "path";
export default defineConfig({
  plugins: [
    vue(),
    legacy({
      targets: ["defaults", "not IE 11"],
    }),
    VitePWA({ strategies: "generateSW", registerType: "autoUpdate" }),
  ],
  server: { port: 8080, host: "localhost" },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  commonjsOptions: {
    esmExternals: true,
  },
  build: {
    minify: "terser",
  },
});
```

I will very appreciate for any suggestions.

**Comment by userquin** [comment]
@Todosiienko can you provide a repro or url where I can check it? I don't use PWA with authentication (yet) and never used Firebase.

**Comment by Todosiienko** [comment]
I found the reason of this problem. Acording to the [firebase docs](https://firebase.google.com/docs/hosting/reserved-urls#reserved_urls_and_service_workers) I have to set up navigation fallback in the VitePWA  like this 
`VitePWA({ strategies: "generateSW", registerType: "autoUpdate", workbox:{ navigateFallbackAllowlist:[/^(?!\/__).*/]} }),`
and now this issue is resolved.

**Comment by userquin** [comment]
@Todosiienko 

can you share the link? https://firebase.google.com/docs/web/pwa seems to have anything about this

I want to add some to the PWA docs... (PR welcome ;) )
