### ISSUE TITLE
Self destroying service worker should clean up cache storage

### ISSUE THREAD

**Issue by Huskydog9988** [vite-pwa/vite-plugin-pwa#560]
When I deployed the self destroying service worker to my site , I noted that while the service worker did disappear, the saved file used to cache the site did not. While I probably should have read more into the sw, I do feel like its somewhat of an expected feature, so hopefully this gets implemented in some form.

**Comment by Doctor-wu** [comment]
@userquin what about to support it by postMessage to each client?

**Comment by userquin** [comment]
This is the code for self destroying sw https://github.com/vite-pwa/vite-plugin-pwa/blob/main/src/modules.ts#L44

**Comment by develohpanda** [comment]
My 2c: I agree that leaving artifacts around isn't great, but I have reservations about adding any extra steps into a self-destroying service worker. It's sole purpose is to self-destroy in case there are any issues and to do it quickly. Adding any extra steps (thus dependencies) into the installation process of the self-destroying SW _could_ lead to an error within that SW, so it should be kept fairly lean like it is here.

**Comment by userquin** [comment]
@develohpanda  @Doctor-wu @Huskydog9988 I've a local PR to remove also sw cache storage entries and fix a problem when clients aren't WindowClient` (for example a Push/Sync worker)
