### ISSUE TITLE
How to conditionally execute registerSW & useRegisterSW based on different MODE?

### ISSUE THREAD

**Issue by wtto00** [vite-pwa/vite-plugin-pwa#569]
I have multiple modes, such as `mode=production` for packaging to the web, and `mode=tauri` for packaging to the PC client. 

I only want to enable PWA when packaging to the web, and not enable PWA when packaging to the PC client. So I added the following code:

`main.js`
```js
import { registerSW } from 'virtual:pwa-register'
const updateSW = registerSW({
          onNeedRefresh() {
            // alert('prompt user to update')
          }
        })
```

`vite.config.js`
```js
{
  plugins: [
    vue(),
    mode === 'production' && VitePWA({
      // ...
    }),
  ]
}
```

I cannot conditionally enable `vite-plugin-pwa` as configured in `vite.config.ts` above, otherwise it will throw an error: `Importing "virtual:pwa-register" could not be resolved.`

How should I conditionally execute `registerSW` and `useRegisterSW` based on different MODE?

**Comment by userquin** [comment]
check elk.repo, we have also Tauri app:
- disable the plugin via env variable and using `std-env`: https://github.com/elk-zone/elk/blob/main/config/pwa.ts#L7
- register tauri module before the pwa: https://github.com/elk-zone/elk/blob/main/nuxt.config.ts#L32
- in tauri module just disable the option: https://github.com/elk-zone/elk/blob/main/modules/tauri/index.ts#L18

**Comment by wtto00** [comment]
Hi, @userquin 

Thanks for your reply.

What you showed is quite complicated, especially regarding the configuration environment of Nuxt. I'm not entirely sure how to simply move it to a regular Vite+Vue frontend project.

I'm considering whether to write the logic for `registerSW` and `useRegisterSW` in a Vue plugin, using the form `createApp({}).use(pwaPlugin)`.   
This way, I can determine whether to execute the logic based on environmental variables.   
If it's not executed, the error of importing should not occur during the packaging process.   
I'm not certain about this approach, but I plan to give it a try tomorrow.

**Comment by userquin** [comment]
https://github.com/vite-pwa/vite-plugin-pwa/blob/main/examples/vue-router/vite.config.ts#L45

**Comment by wtto00** [comment]
@userquin thanks for your answer.

To be honest, I'm not quite sure where `disabled:true` should be written in the configuration parameter.

I saw that a type definition `interface VitePluginPWAAPI` is exposed, which has a `disabled` property. However, the `function VitePWA`, with its parameter `VitePWAOptions`, does not have the disabled attribute or the VitePluginPWAAPI type attribute.


The logic for the "disabled" parameter here comes from `createAPI`.https://github.com/vite-pwa/vite-plugin-pwa/blob/b8202760d924f458f4a8d8aa1e7cb3dc59a62327/src/index.ts#L10-L14

The logic for the "disabled" parameter here comes from `ctx?.options`.https://github.com/vite-pwa/vite-plugin-pwa/blob/b8202760d924f458f4a8d8aa1e7cb3dc59a62327/src/api.ts#L60-L62

The logic for the "disabled" parameter here comes from `createContext`.https://github.com/vite-pwa/vite-plugin-pwa/blob/b8202760d924f458f4a8d8aa1e7cb3dc59a62327/src/index.ts#L10-L12

The logic for "disabled" parameter here always get false.https://github.com/vite-pwa/vite-plugin-pwa/blob/b8202760d924f458f4a8d8aa1e7cb3dc59a62327/src/context.ts#L12-L20

**Comment by userquin** [comment]
> To be honest, I'm not quite sure where disabled:true should be written in the configuration parameter.

It is `disable`, remove the final **`d`**: you need to override the configuration options, you cannot change the PWA  options once loaded.

**Comment by wtto00** [comment]
I guess it should be done like this
`vite.config.ts`
```js
{
  plugins: [
    vue(),
    {
      ...VitePWA({
        // ...
      }),
      disable: true
    }
  ]
}
```
I will give it a try tomorrow. Thank you for your guidance :heart:
