### ISSUE TITLE
Page is shown with no assets

### ISSUE THREAD

**Issue by jasonhibbs** [vite-pwa/vite-plugin-pwa#576]
I've had this issue since adding the plugin to Nuxt 3 on Netlify.

When returning to the site, no styles or scripts are shown.

Am I missing something? Happy to share any more details.

The [development site is here](https://relaxed-travesseiro-494a12.netlify.app).

Repro:
1. [Visit site](https://relaxed-travesseiro-494a12.netlify.app) on Mobile Safari on iOS
2. Close Safari from App Switcher
3. Reopen Safari
4. See page with no styles or scripts

When visited:
![image](https://github.com/vite-pwa/vite-plugin-pwa/assets/919628/c7420efa-73c4-40bc-8e7c-a6bad07030d1)

When returning:
![image](https://github.com/vite-pwa/vite-plugin-pwa/assets/919628/039c8512-b98a-41f6-8e44-a97e110445ee)

**Comment by userquin** [comment]
@jasonhibbs your sw is broken, check image below.

check https://github.com/antfu/vitesse-nuxt3/pull/98 and https://github.com/vite-pwa/nuxt/pull/66

EDIT: some explanations here with SvelteKit (same problem with same solution): https://github.com/vite-pwa/sveltekit/issues/65#issuecomment-1734213190

![imagen](https://github.com/vite-pwa/vite-plugin-pwa/assets/6311119/92ab3ce9-80b2-4cfd-bdc5-014cea9dcf8b)

**Comment by jasonhibbs** [comment]
Thanks for a quick response and reference, looks like I have some reading to do!
