### ISSUE TITLE
Why does this public folder get "cached"?

### ISSUE THREAD

**Issue by jasonhibbs** [vite-pwa/vite-plugin-pwa#577]
Making a number of guesses about what I actually need here after opening #576. Now seeing a public folder returning 404, which is not unexpected – I don’t know why it would be included.

<img width="726" alt="Screenshot 2023-10-11 at 23 53 43" src="https://github.com/vite-pwa/vite-plugin-pwa/assets/919628/03fe58ea-5f2b-4ef1-9f46-764811639b86">

In any case, I added a rule that I expect to prevent this folder `/launch` from being included, but I’m sure I’m misunderstanding something.

[Dev site](https://relaxed-travesseiro-494a12.netlify.app) & [sw.js](https://relaxed-travesseiro-494a12.netlify.app/sw.js) links.

Config:
```
    workbox: {
      navigateFallback: '/',
      navigateFallbackAllowlist: [/^\/$/, /^\/find$/, /^\/check$/, /^\/solve$/],
      navigateFallbackDenylist: [/^\/api/, /^\/launch/],
    },
```

**Comment by userquin** [comment]
@jasonhibbs the server is respondinf 404 for that url, do you have a /launch.html file or /launch endpoint api/route?

**Comment by userquin** [comment]
@jasonhibbs for some reason you're registering the sw twice, it is weird, sw.js twice in dev tools.

**Comment by userquin** [comment]
Just include launch in the `workbox.globIgnores`, it is being included the sw precache manifest, if it is an html file use `[/^launch\.html$/]`  (check also the sw.js is not included in the sw precache manifest): 
```ts
workbox: {
  globIgnores: [/^launch/]
}
```

![imagen](https://github.com/vite-pwa/vite-plugin-pwa/assets/6311119/6696ca2e-99df-4cda-ab8d-a56c1f040cb5)

Opening the launch url in private browsing:

![imagen](https://github.com/vite-pwa/vite-plugin-pwa/assets/6311119/776cee76-1000-4a84-880a-d22472190198)

**Comment by jasonhibbs** [comment]
Thanks again!

`/launch` is only a folder containing assets, it is not a page or file, it is expected to 404, since there is nothing to cache.

That said, it makes sense to cache all the assets in the folder, so ai wouldn't want to exclude its contents.

What do you suggest?

And is there anything I can share to help figure out why you see two sw.js?

**Comment by userquin** [comment]
But, why is including workbox-build launch as an entry in the sw precache? If you're not using any assets in the webapp just exclude it, don't waste bandwidth and storage in the client

Just check the launch entry and any of the assets inside are missing in the sw.js file. Once redeployed clean the pwa and visit again the site, the sw.js should be in green in devtools.

About sw.js twice, it is weird, maybe the problem is about sw.js is failing.

**Comment by userquin** [comment]
@jasonhibbs don't forget remove `navigateFallbackAllowlist` and `navigateFallbackDenylist`.

**Comment by jasonhibbs** [comment]
Oh I see – yes, the launch folder is for splash images anyway, so they don't need caching at all.

I'll try some things and report back, thanks!

**Comment by jasonhibbs** [comment]
Alright I think I’ve got it, and the SW only appears once now – thanks!

```js
    workbox: {
      navigateFallback: '/',
      navigateFallbackAllowlist: [/^\/$/, /^\/find$/, /^\/check$/, /^\/solve$/],
      globIgnores: ['launch'],
    },
```
