### ISSUE TITLE
Should sw.js has filename hash?

### ISSUE THREAD

**Issue by winston0410** [vite-pwa/vite-plugin-pwa#580]
I encountered a cache issue today, since sw.js has no filename hash, and there is a cache layer in CDN, it keeps serving the incorrect `sw.js`.

I am not an expect on service worker, a naive solution to this would be filename hash based on the content of `sw.js`, but as this library handle autoUpdate/prompt update as well, is adding filename hash an anti pattern, or is dynamic import the blocker here?

**Comment by userquin** [comment]
https://vite-pwa-org.netlify.app/deployment/#cache-control

**Comment by winston0410** [comment]
thank you so much for pointing me to the doc, and after I have disabled cache for those path, it has been working well.

Just 1 follow-up question, is it right to say we don't want sw.js to have any hash, as it is an entry point by itself since the content of sw.js is derived by other files in a build? So once the client get a new sw.js, they will get the update, and sw will cache the new resources?

**Comment by userquin** [comment]
@winston0410 yes to both questions: sw will change if you change a single comma in any html, js, css or other assets that's in the sw precache manifest (or some new content added). 

The browser will use the sw asset to detect a new version comparing both versions (bit by bit) and will switch it when detected and activated (will serve the new cached version of your app assets).

**Comment by winston0410** [comment]
That is very helpful, thanks!
