### ISSUE TITLE
Offline mode for examples doesn't work

### ISSUE THREAD

**Issue by chawes13** [vite-pwa/vite-plugin-pwa#581]
Following the steps in the [offline section](https://vite-pwa-org.netlify.app/examples/#how-to-test-the-examples-projects-offline) of Getting Started, I cloned the latest version of this repo and ran the `react-router` project.

### Steps to Reproduce
- Install example dependencies and run `dev` script
- Open up Chrome dev tools and navigate to Application
- Select registered service worker
- Click "offline"
- Perform a normal refresh

### Expected
App loads, including `favicon.svg` which is defined in `includeAssets`.

### Actual
App doesn't load as several assets cannot be retrieved by the service worker

Recording: https://share.zight.com/WnupkQK6

As an aside, I'm also experiencing the same issue on a net new project.

**Comment by userquin** [comment]
Offline support will not work in dev, you must build and test it using preview script in a chromium based browser.

**Comment by userquin** [comment]
You can run the `examples`  script and follow the wizard: `pnpm run examples`.

**Comment by chawes13** [comment]
> Offline support will not work in dev, you must build and test it using preview script in a chromium based browser.

Is this still the case when `devOptions.enabled = true`?

I ran the `start-preview` script and got the following error:
![Image 2023-10-23 at 2 29 37 PM](https://github.com/vite-pwa/vite-plugin-pwa/assets/20426095/295b3de4-e765-4edd-8797-0c9fa89107d6)

I'm assuming I'm missing some more steps there. Could you point me in the right direction?

**Comment by userquin** [comment]
You must build the repo first, from root run:
`pnpm install && pnpm run build`.

You can run the pwa in dev node to test he web manifest and custom sw when using injectManifest strategy. To enable pwa in dev, configure:
`devOoptions. enabled = true`.

To test anu example offline, you must build the example and use the preview script from the example folder:
`pnpm run build && pnpm run preview`.

Or you can run the examples script from root folder:
`pnpm run examples`

**Comment by chawes13** [comment]
Oh, lovely! Sorry I misunderstood what enabling `devOptions` would get for me.

I can confirm that the example _does_ work offline when the running through preview. Thanks for the help 🙏
