### ISSUE TITLE
globpatterns-warning in nuxt3 analyzed

### ISSUE THREAD

**Issue by lovkyndig** [vite-pwa/vite-plugin-pwa#584]
The following screen clip is well known of many users that have tried `vite-plugin-pwa` trough `@vite-pwa/nuxt`:
<img width="459" alt="capture from terminal of globpatterns" src="https://github.com/vite-pwa/vite-plugin-pwa/assets/125480548/b9454fca-49ea-4c2b-b8a8-4f0413b0eb42">

## Analyzing the warning msg
I have analyzed the warning message[^1], and have this comment:

The globdirectory is `.nuxt/dev-sw-dist`  - always.[^2]

Well, there is the problem! 
One of the globpatterns have to unmatch files in this folder, because there is only four `js`-files in this `sw*`-folder.

I haven't set the globDirectory to this `dev`-directory, so its out of my control.   
I can never get rid of this warning, without creating my own custom sw.[^3] 

[^1]: After I have worked at list 10 ours to get rid of the message, without success.
[^2]: I can tell you because I got this message over 100 times.
[^3]: And that's outside of my programming-knowledge.

**Comment by userquin** [comment]
https://vite-pwa-org.netlify.app/guide/faq.html#suppress-workbox-build-warnings-in-dev

**Comment by userquin** [comment]
Check also https://vite-pwa-org.netlify.app/guide/cookbook.html

**Comment by userquin** [comment]
Or just disable devOptions...

**Comment by lovkyndig** [comment]
Wow, thanks a lot! 
I will check this out as soon as possibly:)

**Comment by lovkyndig** [comment]
Wow, fastes fix I ever have done - 5 min and all the warnings gone.
Thanks again!
