### ISSUE TITLE
workbox runtimeCaching set networkOnly strategy fails when url with search parameters

### ISSUE THREAD

**Issue by zheeeng** [vite-pwa/vite-plugin-pwa#589]
I made config below, it works when visit 'https://app.example.com/reset_password' and 'https://app.example.com/reset_password.html', but once we add some search parameters 'https://app.example.com/reset_password.html?token=xxxx', the request fallbacks to app entry index.html unless I press shift + page refresh.

```js
workbox: {
  runtimeCaching: [
    {
      urlPattern: /^\/reset_password(\.html)?$/,
      handler: 'NetworkOnly',
    },
  ],
  globPatterns: ['**/*.{js,css,html,ico,png,svg}'],
  maximumFileSizeToCacheInBytes: 5 * 1024 * 1024,
},
```

**Comment by userquin** [comment]
You should add a few options to the hanlder, check this:
https://github.com/vite-pwa/nuxt/issues/79#issuecomment-1781745717

**Comment by zheeeng** [comment]
It works thx for help me.
