### ISSUE TITLE
Error: [InjectManifest] 'rollupFormat' property is not expected to be here.

### ISSUE THREAD

**Issue by meticoeus** [vite-pwa/vite-plugin-pwa#597]
@vite-pwa/sveltekit: 0.2.8
vite-plugin-pwa: 0.16.7
workbox-build: 7.0.0

I am posting here as the issue appears to be in the build process options in this repository and not the sveltekit plugin package.

I am getting an error attempting a production build with injectManifest strategy with `injectManifest.rollupFormat: 'iife'`. If I remove `rollupFormat: 'iife'` from my build options then I instead get a runtime error in the browser because the SW is built as a module but workbox-window is using the 'classic' type to register the SW.

Investigating workbox-build source it appears injectManifest.rollupFormat does not exist and that they added a JSON schema validation of the options, resulting in an error. vite-plugin-pwa is looking for this option to control when to build the SW in `iife` or `es` format [link](https://github.com/vite-pwa/vite-plugin-pwa/blob/d4c053b324d980b1b0bdb05c31f60c6bde5687b5/src/options.ts#L112).

Separate, related issue: workbox-window is being passed type: 'classic' unless devOptions override it but in the `./src/options.ts:resolveOptions` devOptions.type is set to 'classic' when `viteConfig.command !== 'serve'` [link](https://github.com/vite-pwa/vite-plugin-pwa/blob/d4c053b324d980b1b0bdb05c31f60c6bde5687b5/src/options.ts#L135) so it does not appear to be possible to have workbox-window use type: 'module' in production from this plugin's virtual modules.

These 2 issues seem to be resulting it not being possible to create a working injectManifest production build with workbox-build 7, which is the listed peerDependency.

```ts
// vite.config.ts
const config: UserConfig = {
  ...
  plugins: [
    sveltekit(),
    SvelteKitPWA({
      minify: false,
      srcDir: './src',
      mode: process.env.NODE_ENV === 'development' ? 'development' : 'production',
      strategies: 'injectManifest',
      filename: 'sw.ts',
      useCredentials: true,
      injectRegister: false,
      manifest: {...},
      injectManifest: {
        rollupFormat: process.env.NODE_ENV === 'development' ? 'es' : 'iife',
        globPatterns: ['client/**/*.{js,css,ico,png,svg,webp,woff,woff2}'],
      },
      devOptions: {
        enabled: true,
        type: 'module',
        navigateFallback: '/',
      },
    }),
  ],
}

// app.ts
  import { useRegisterSW } from 'virtual:pwa-register/svelte'

  const {} = useRegisterSW({...})
```

Stacktrace:
```sh
error during build:
Error: [InjectManifest] 'rollupFormat' property is not expected to be here. Did you mean property 'globFollow'?
    at validate (/<path>/node_modules/workbox-build/build/lib/validate-options.js:52:11)
    at validateInjectManifestOptions (/<path>/node_modules/workbox-build/build/lib/validate-options.js:121:32)
    at injectManifest (/<path>/node_modules/workbox-build/build/inject-manifest.js:55:74)
    at Object.handler (file:///<path>/node_modules/@vite-pwa/sveltekit/dist/index.mjs:189:37)
    at async PluginDriver.hookParallel (file:///<path>/node_modules/rollup/dist/es/shared/node-entry.js:25461:17)
    at async Object.close (file:///<path>/node_modules/rollup/dist/es/shared/node-entry.js:26721:13)
    at async build (file:///<path>/node_modules/vite/dist/node/chunks/dep-df561101.js:48021:13)
    at async CAC.<anonymous> (file:///<path>/node_modules/vite/dist/node/cli.js:822:9)
```

**Comment by userquin** [comment]
@meticoeus the service worker is built now by SvelteKit, since you're are include `rollupFormat`, vite-pwa-plugin will just provide that configuration to workbox-build module, remove `rollupFormat` from `injectManifest` option.

If you want file an issue in PWA Sveltekit repo.

**Comment by userquin** [comment]
SvelteKit version?

**Comment by userquin** [comment]
ok, build plugin is not used, should be excluded here: https://github.com/vite-pwa/sveltekit/blob/main/src/plugins/SvelteKitPlugin.ts#L100-L105

**Comment by userquin** [comment]
We can build for production the example in the repo. If you want to register your service worker using type module, you can add your own logic, here the source code: https://github.com/vite-pwa/vite-plugin-pwa/blob/main/src/client/build/register.ts

**Comment by meticoeus** [comment]
Sveltekit version: 1.20.2

I made a local copy of https://github.com/vite-pwa/vite-plugin-pwa/blob/main/src/client/build/register.ts for now so I can use type: module as a workaround.

I'm using this plugin to build a custom service worker that works in development. Last I checked, the Sveltekit serviceworker build didn't work in development and my app has heavy offline based functionality that requires that serviceworker always exists or many parts of the app don't work.

**Comment by userquin** [comment]
add this to your pwa options: `devOptions: { enabled: true, type: 'module' }` https://vite-pwa-org.netlify.app/guide/development.html

**Comment by userquin** [comment]
The offline mode will not work in dev, try build + preview in your local.

**Comment by meticoeus** [comment]
To clarify, I'm testing the serviceworker in dev mode which works perfectly. I'm not testing the offline caching of the page assets, just other functionality of the serviceworker which includes fetch interception and retrieval of local data from indexeddb.

**Comment by meticoeus** [comment]
This is actually an x-y problem. I've posted https://github.com/vite-pwa/sveltekit/issues/72 with the actual problem I was tying to solve by using rollupFormat, which was working in an earlier version of this plugin.
