### ISSUE TITLE
Custom service-worker error

### ISSUE THREAD

**Issue by jandante** [vite-pwa/vite-plugin-pwa#599]
For my PWA I want to add share target, push notifications and possibly some background jobs (if I can get my head around it).
For this I see it is better to make you custom service worker.
So I follow the instructions and adopting the vite.config.js:

```
    VitePWA({
      devOptions: {
        enabled: true,
        type: 'module'
      },
      strategies: 'injectManifest',
      srcDir: 'src',
      filename: 'sw.js',
```

My /src/sw.js is the provided code from the docs:

```
import { precacheAndRoute } from 'workbox-precaching'

precacheAndRoute(self.__WB_MANIFEST)
```

But I get the "Uncaught SyntaxError: Cannot use import statement outside a module."
I've seen and read https://github.com/vite-pwa/vite-plugin-pwa/issues/35 but this should be 'old news' since with the devOptions.type property set to 'module' things should work...

Is there something wrong in this config?

**Comment by userquin** [comment]
You can only run sw with type module un chromium based browser.

**Comment by userquin** [comment]
You can check elk.zone github repo, the sw has push notificqtions and web shared target api.

**Comment by jandante** [comment]
Yes I've read that also. I'm testing in Brave browser but also installed Chrome but I keep getting this error in dev environment.

In production all goes well.

**Comment by jandante** [comment]
> You can check elk.zone github repo, the sw has push notifications and web shared target api.

Thank you. I've been trough it already and that's a very professional implementation. I'll probably start with the basic. (eg https://blog.lekoala.be/the-only-snippet-you-will-need-to-deal-with-push-notifications-in-a-service-worker for push notifications works great for me).

**Comment by jandante** [comment]
> You can only run sw with type module un chromium based browser.

Brave and Chrome are chromium based? Or should it actually be Chromium?

**Comment by userquin** [comment]
Dobt use brave, it has some limitations, you can use Chrome. Chromium and Edge, aslo in private browsing and without https.

Check also docs.elk.zone, there is a pwa page with a lot of hints , including testing sw in real android device via use.

**Comment by userquin** [comment]
Try adding type module to your package.json.

**Comment by jandante** [comment]
It's working (even in Brave :)) when creating a new Vite + VitePWA plugin and setting the config like in the original post. So was not able to reproduce.

My project that isn't working (in dev) I'm using ionic framework. If you're up for it I can give access to the code through a github repo.

In package.json I have "type": "module" already set (it was there already).

**Comment by jandante** [comment]
I've setup a blank ionic project with just the pwa plugin enabled and added the config from the first post and that is triggering the error as well. See https://github.com/jandante/vite-pwa-sw-issue

The code can be found here. Should I make a ticket for this at the Ionic repo?

Beste regards!

**Comment by jandante** [comment]
Closing this since can't create minimal reproduction without Ionic.

Opened a ticket at ionic-framework repo that is linked above.

@userquin Thanks for your help
