### ISSUE TITLE
Running vue-router example results in TypeError

### ISSUE THREAD

**Issue by zluiten** [vite-pwa/vite-plugin-pwa#602]
> 
> workerImport.js:4 Uncaught TypeError: Cannot read properties of undefined (reading 'NODE_ENV')
>     at workerImport.js:4:33
>     at my-worker.js:16:1

**Comment by userquin** [comment]
Use `import.meta.env.mode` or remove the import at top

**Comment by zluiten** [comment]
Thanks!

Removing the import did work!

Using `import.meta.env.mode` did not though. The build step then outputs the following: 

```
[warn] ▲ [WARNING] "import.meta" is not available with the "cjs" output format and will be empty [empty-import-meta]

    src/modules.ts:11:26:
      11 │   : dirname(fileURLToPath(import.meta.url))
         ╵                           ~~~~~~~~~~~

  You need to set the output format to "esm" for "import.meta" to work correctly.
```
