### ISSUE TITLE
Importing a CommonJS node_module in a custom service worker turns it into an ES module

### ISSUE THREAD

**Issue by kgroat** [vite-pwa/vite-plugin-pwa#615]
I've discovered that creating a custom service worker using the `injectManifest` strategy can lead to an issue when importing a `node_module` that is in the CommonJS format.  Specifically, the service worker will end up as an ES module, with an `export default`, which will result in an error when registered in the browser.  The built asset will look something like this:
```js
var t = (l, o) => () => (o || l((o = { exports: {} }).exports, o), o.exports);
var _ = t((r, e) => {
  // Your compiled code here
});
export default _();
```

I've created this minimal reproduction case [here](https://github.com/kgroat/Minimal-SW-ES-Repro).

I've discovered that adding this to the config gets rid of the default export, but I'm not sure if it has other side-effects:
```js
VitePWA({
  // the rest of your config up here...

  injectManifest: {
    rollupFormat: 'iife'
  }
})
```

**Comment by userquin** [comment]
It seems a problem with esbuild: https://github.com/vitejs/vite/issues/15379

**Comment by userquin** [comment]
@Rich-Harris good to know it, thx

How about `.mts` when using TS?

**Comment by Rich-Harris** [comment]
that wouldn't make sense — this is the _output_ filename. it's purely a signal to `esbuild` that prevents it from erroneously adding an unwanted `export` declaration

**Comment by userquin** [comment]
yeah, forgot it
