### ISSUE TITLE
Cannot use 'import.meta' outside of a module in development with script inject register method

### ISSUE THREAD

**Issue by AlekEagle** [vite-pwa/vite-plugin-pwa#622]
When I'm running Vite in development mode (running `vite` with no arguments) I get the `Cannot use 'import.meta' outside of a module` error even though I have explicitly specified `type: 'module'` in my vite.config.ts file. My inject register method is script, but when using inline, it works fine.

**Comment by userquin** [comment]
using custom sw (injectManifest strategy)? can you show me also devOptions?

**Comment by AlekEagle** [comment]
Yes, I am using a custom sw with injectManifest.

The Error:
```
Uncaught SyntaxError: Cannot use 'import.meta' outside a module (at dev-sw.js?dev-sw:1:8)

Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('http://localhost:4173/') with script ('http://localhost:4173/dev-sw.js?dev-sw'): ServiceWorker script evaluation failed
```

The line in question:
```js
import.meta.env = {"BASE_URL":"/","MODE":"ptb","DEV":true,"PROD":false,"SSR":false};import.meta.env.LEGACY = false;import { Router } from "/src/utils/swRouter.ts";
```

My config:
```ts
// ...
      injectRegister: 'script',
      // ...
      devOptions: {
        enabled: true,
        type: 'module',
      },
// ...
```

And when I switch the `injectRegister` method to `'inline'` it no longer gives me errors and successfully registers the service worker.

**Comment by userquin** [comment]
The error is in the service worker, try adding this line at top of the sw:
```ts
/// <reference types="vite/client" />
```
The Router import cannot use any dynamic import.

**Comment by userquin** [comment]
You can check these 2 examples or any example in the examples folder in this repo:
- SvelteKit: https://github.com/vite-pwa/sveltekit/blob/main/examples/sveltekit-ts/src/prompt-sw.ts#L22
- Vue 3: https://github.com/vite-pwa/vite-plugin-pwa/blob/main/examples/vue-router/src/claims-sw.ts#L14

**Comment by AlekEagle** [comment]
I'm not using dynamic imports anywhere, the error is specifically at the use of the `import.meta` statement according to the error, and the issue is that despite me explicitly declaring that the service worker should be registered as a module instead of a classic service worker, and that this only happens when using `injectRegister: 'script'`. I have gone ahead and edited my earlier comment to be a little more specific.

**Comment by userquin** [comment]
@AlekEagle  Cannot reproduce the error, can you stop dev server and delete the `dev-dist` folder?:
![imagen](https://github.com/vite-pwa/vite-plugin-pwa/assets/6311119/471b8459-b9dc-4267-8b6d-d4a24900f643)

![imagen](https://github.com/vite-pwa/vite-plugin-pwa/assets/6311119/6e2f373e-a692-4a04-8ce0-c54774f6d77c)

**Comment by AlekEagle** [comment]
Looks like my issue was partially because my plugin version was out of date, I successfully solved the issue, sorry for troubles!
