### ISSUE TITLE
Site Crash in offline mode on Firefox after refreshing/reloading the page.

### ISSUE THREAD

**Issue by alamgir8** [vite-pwa/vite-plugin-pwa#640]
Is there any way to prevent or show the app on offline mode after reloading/refreshing the page on the Firefox browser? 

Let's say if I open this site https://vite-pwa-org.netlify.app/ on Chrome then try to go offline, then reload the page, and it still shows the site, but in Firefox it's not work.

<img width="1387" alt="Screenshot 2024-01-08 at 7 51 16 PM" src="https://github.com/vite-pwa/vite-plugin-pwa/assets/52715776/f1b6607c-05a7-4e79-aa4f-c4d98a0b8183">

<img width="1366" alt="Screenshot 2024-01-08 at 7 55 53 PM" src="https://github.com/vite-pwa/vite-plugin-pwa/assets/52715776/1e645eac-1367-4f89-ae9b-39a4678809a5">

**Comment by userquin** [comment]
Should be a bug in Firefox, in Chrome it is working when offline.
