### ISSUE TITLE
How to remove the workbox console?

### ISSUE THREAD

**Issue by haerim95** [vite-pwa/vite-plugin-pwa#642]
Hi

I created a react project with vite and am working on it

There are so many workbox console in development, it's confusing.
Is there an option to prevent the console from appearing?

I ask because I can't find it by reading the documentation.

These are my vite.config options

```
 VitePWA({
      registerType: 'autoUpdate',
      devOptions: {
        enabled: true,
      },
      workbox: {
        disableDevLogs: true,
        globPatterns: ['**/*.{js,css,html,ico,png,svg}'],
      })
```

![Screenshot 2024-01-16 at 10 18 49 AM](https://github.com/vite-pwa/vite-plugin-pwa/assets/63902948/8bd299d1-2691-476f-9ad9-c70efc64b5c6)

I've done a lot of searching and haven't come up with an answer, so I'm asking here.

**Comment by userquin** [comment]
In dev aeever or build? Try adding `mode; 'production'` to pwa options

**Comment by haerim95** [comment]
OMG...
I changed the mode to production, gave it some time, rebuilt, and the console was gone!

Thank you for your quick response!!!! 👍❤️
