### ISSUE TITLE
Output is minified even with --minify false

### ISSUE THREAD

**Issue by iBicha** [vite-pwa/vite-plugin-pwa#643]
Running `vite build --minify false`, I expected the generated files (sw.js, workbox) to be not minified, but they are

**Comment by userquin** [comment]
use `mode: 'development'` or you can try configuring `process.env.NODE_ENV` in Vite's define entry:
```js
define: {
    'process.env.NODE_ENV': process.env.NODE_ENV === 'production' 
      ? '"production"'
      : '"development"'
  }
```

**Comment by userquin** [comment]
IIRC there is no way to only minify the codebase and exclude the sw using `generateSW`. For `injectManifest` strategy there is a PR to add 3 new options: https://github.com/vite-pwa/vite-plugin-pwa/pull/629

**Comment by iBicha** [comment]
Yeah that's fair, on a second thought keeping things separate might be useful. Thanks!
