### ISSUE TITLE
Error handling for workbox import

### ISSUE THREAD

**Issue by cpojer** [vite-pwa/vite-plugin-pwa#645]
I have a lot of users on older devices who run into issues with downloading the `workbox-window` module. Here is what shows up in Sentry, despite the file being available on my CDN:

![CleanShot 2024-01-22 at 10 42 58@2x](https://github.com/vite-pwa/vite-plugin-pwa/assets/13352/b58771b0-5fa6-48a4-a5e1-17e207cb8c14)

Would it be acceptable to add try-catch behavior to the Workbox import here?

https://github.com/vite-pwa/vite-plugin-pwa/blob/main/src/client/build/register.ts#L40

**Comment by userquin** [comment]
How to you use the virtual module in your app?

**Comment by cpojer** [comment]
Via `import { registerSW } from 'virtual:pwa-register';`.

**Comment by userquin** [comment]
If your app is consumed by ancient browsers maybe you should use another approach. is your app used in chrome browser or inside native webview?

I'm going to fix the error, maybe review your PR (should handle the error properly).

**Comment by cpojer** [comment]
I have no control which browser people are using and this is showing up in my crash logs, which is why I brought up the issue and PR.
