### ISSUE TITLE
Service Worker won't self-destruct on development

### ISSUE THREAD

**Issue by lgaspari** [vite-pwa/vite-plugin-pwa#647]
### Description

Hey, I'm trying to set up my application's PWA Vite plugin with an environment variable to handle whether the Service Workers are enabled. As per last week I thought that toggling the `disabled` property from the config would've been enough, however, considering I needed to also destroy the Service Worker, so I ended up with a different configuration:

```ts
VitePWA({
  // always `true`
  devOptions: {
    enabled: true,
  },
  // depends on env var
  selfDestroying: !env.isServiceWorkerEnabled,
})
```

After discussing this configuration with @userquin through Discord, it seemed like it would be enough to make it work. Nonetheless, it seems like there might be a bug when trying to self-destroy the Service Worker on development, but not on production.

Is this the correct way to control the Service Worker registration? Seems to me that eventually I'd need another environment variable so that I can completely turn off the plugin after the service worker was destroyed.

### Reproduction

You may use the following repository to reproduce the issue: https://github.com/lgaspari/vite-plugin-pwa-sw-dev-repro

In addition, here are the **raw steps** in order to reproduce the issue:

1. Make sure your **Vite PWA configuration** has at least the following structure:

```ts
VitePWA({
  devOptions: {
    enabled: true,
  },
  selfDestroying: false,
})
```

2. Run your application for DEVELOPMENT (most likely `npm run start`, or just `vite`).
3. Open your browser, open Dev Tools, and go to the Application tab. You should see the Service Worker up and running.
4. Now, without stopping the application, change your **Vite PWA configuration** to the following:

```ts
VitePWA({
  devOptions: {
    enabled: true,
  },
  selfDestroying: true,
})
```

5. Go back to your browser, you'll see the application's reloaded, but the Service Worker remains there.
6. Now, repeat the same steps but for PRODUCTION (use `vite build && vite preview`). You'll notice that the Service Worker was successfully deleted on step 5.

### Solution

A possible solution to the issue would be changing this condition from https://github.com/vite-pwa/vite-plugin-pwa/blob/main/src/plugins/dev.ts#L131 to:

```
if (!swDevOptions.swDevGenerated || !existsSync(swDest) || options.selfDestroying) { ... }
```

That way, when the `selfDestroying` option is `true` it will create a new SW that will self-destroy. It worked like a charm on my local, but if we try the other way around (toggling `selfDestroying` from `false` to `true`) won't work, resulting in a self-destruct SW until I restart the server to generate a new SW.

**Comment by lgaspari** [comment]
Hey @userquin, I've just gave this new patch version a try, but unfortunately the issue remains.

Here's a video showcasing what I'm trying to do, please note that I have to restart the server to make the SW redundant. Is this behavior intended? I may be expecting it to work in my way but it might not work like that 😅 

https://github.com/vite-pwa/vite-plugin-pwa/assets/20128985/a1989a06-59bf-4442-a837-75c46f2a445f

**Comment by userquin** [comment]
You cannot remove the sw, it should be there forever, you don't know when it will be loaded in your clients.

In your local tests, you can disable it once you've visited the page.

**Comment by lgaspari** [comment]
> You cannot remove the sw, it should be there forever, you don't know when it will be loaded in your clients.
> 
> In your local tests, you can disable it once you've visited the page.

Then, to turn on/off the Service Worker on DEVELOPMENT won't be enough by restarting the server through HMR but rather stop the server and start it over again? That's okay for me! I'll make sure to document that somewhere in the README to remember it by.

For PRODUCTION (`npm run build && vite serve`) it works like a charm as is, so no need for changes there.

I appreciate the time you've taken on reviewing this issue and helping me through it :)
