### ISSUE TITLE
vite-wasm-plugin does not work with serviceworker

### ISSUE THREAD

**Issue by ffreddow** [vite-pwa/vite-plugin-pwa#655]
When trying to build a service worker that imports Webassembly I get the same error as if [vite-plugin-wasm](https://github.com/Menci/vite-plugin-wasm) is not there:
> "ESM integration proposal for Wasm" is not supported currently. Use vite-plugin-wasm or other community plugins to handle this. Alternatively, you can use `.wasm?init` or `.wasm?url`. See https://vitejs.dev/guide/features.html#webassembly for more details.

Building for developement does not throw an error but there is no serviceworker present.
Without the wasm import everything works just fine.

The config looks like this:
![image](https://github.com/vite-pwa/vite-plugin-pwa/assets/88713513/7e23accb-2b2c-4922-b45d-ffa918d0340c)

Am I configuring this wrong, is it a problem with VietPWA or is it a problem with the wasm plugin.

**Comment by ffreddow** [comment]
Update: 
It works (at least for production builds) when providing the plugins directly to vite's build function inside src/modules.tsx of VitePWA.
![image](https://github.com/vite-pwa/vite-plugin-pwa/assets/88713513/8137155b-9c3f-4ee3-9ae9-2ddc77efb3ef)

**Comment by userquin** [comment]
configured plugins should be added to Vite's plugins entry, we need another entry

**Comment by userquin** [comment]
> It works (at least for production builds) when also providing the plugins directly to vite's build function inside src/modules.tsx of VitePWA.

does the sw work running the app via local preview? what's the top level await plugin?

I'm going to add a new `vitePlugins` option in this PR: https://github.com/vite-pwa/vite-plugin-pwa/pull/629

**Comment by userquin** [comment]
do you have a reproduction where I can test the changes?

**Comment by userquin** [comment]
@ffreddow can you test with new `v0.18.0` version using `injectManifest.buildPlugins.vite`?

**Comment by ffreddow** [comment]
I created  reproduction repository (https://github.com/ffreddow/vite-pwa-plugins-test).
I still get the same error when running the dev server. The production build looks fine when staring at it but something doesn't work out with the preview (probably because of a dynamic import, which is afaik forbidden in a serviceworker, so I guess that's not a problem with VitePWA).

**Comment by userquin** [comment]
You need to register both plugins in vite and inject manifest vite plugins: in dev, the pwa plugin will use vite (no build) and so you need both plugins in vite, on build, pwa plugon will use a new vite build from the api, the build will not use main vite plugins it will use the configured inject manifest vite plugins
