### ISSUE TITLE
0.18.0 breaks `registerType: "prompt"`

### ISSUE THREAD

**Issue by alexlapwood** [vite-pwa/vite-plugin-pwa#663]
# Expected behaviour

In 0.17.5 setting `registerType: "prompt"` behaved like this:

1. Check for updates with `serviceWorkerRegistration.update()`
2. If a new update is found show a prompt
3. When the prompt is activated reload the page to active the new service worker with `updateServiceWorker()`

# Observed behaviour

In 0.18.0 setting `registerType: "prompt"` behaves like this:

1. Check for updates with `serviceWorkerRegistration.update()`
2. If a new update is found the page automatically reloads (this is the bug)
3. Curiously the new service worker still needs to be activated with `updateServiceWorker()` (causing another reload)

# Steps to reproduce

You can reproduce this issue using the following SolidJS hook:

```ts
export function useUpdate() {
  const [serviceWorkerRegistration, setServiceWorkerRegistration] =
    createSignal<ServiceWorkerRegistration | undefined>(undefined);

  const {
    needRefresh: [needRefresh],
    updateServiceWorker,
  } = useRegisterSW({
    onRegistered(serviceWorkerRegistration) {
      setServiceWorkerRegistration(serviceWorkerRegistration);
      setInterval(() => {
        serviceWorkerRegistration?.update();
      }, 60 * 1000);
    },
    onRegisterError(error) {
      console.error("SW registration error", error);
    },
  });

  return { updateReady: needRefresh, updateServiceWorker };
}
```

I'm not sure if the title of this issue is correct, please change as needed.

**Comment by userquin** [comment]
Why are you exposing `update` instead `updateServiceWorker`? I need to check if calling `await serviceWorkerRegistration()?.update();` will skip the awaiting state.

In the meantime, can you test using the logic provided in the [periodic sync for updates](https://vite-pwa-org.netlify.app/guide/periodic-sw-updates.html#handling-edge-cases) and exposing `updateServiceWorker` in the `update` value?

**Comment by userquin** [comment]
Can you try removing the interval in your local? I Will vheck your reproduction tmr.

**Comment by userquin** [comment]
You Will need to avoid calling update if the sw also waiting to be activated, I guess the update will also trigger the event to active it

**Comment by userquin** [comment]
it seems the problem is the heuristic time approach in worbox window to detect false positivies: you can try awaiting a minute after second build (https://github.com/GoogleChrome/workbox/blob/v7/packages/workbox-window/src/Workbox.ts#L414)

**Comment by userquin** [comment]
Cleanup the storage removing the sw, the logic is always 1 step behind, you don't need to wait 10 min. just 1 min.
