### ISSUE TITLE
Cached files does not load pages except "/" (base path) in sveltekit

### ISSUE THREAD

**Issue by omerharuncetin** [vite-pwa/vite-plugin-pwa#665]
My problem is related to the cached files. If I route to the main page, which is `/` everything works fine. However, if I want to route another page, such as 
- `/explore`
- `/posts/x`
- `/users/y`

These page assets are loading from the current path not from the base path. Therefore, non of the files be able to uploaded and the page doesn't respond correctly.

Some project information may be helpful for finding solution.

- I have defined `scope` and `base` as `/` both in manifest and **SvelteKitPWA** config.
- I use `generateSW` strategy with `autoUpdate` register type
- I don't have custom service worker. 

If you need any further information, please let me know. 

Also, here is the a part of error in browser console. If I do hard refresh on page, everything works fine.

![image](https://github.com/vite-pwa/vite-plugin-pwa/assets/47770235/a96a3a41-4301-43bc-bccf-fb994f87a9ce)

**Comment by omerharuncetin** [comment]
> try setting `paths.relative` to false in kit config file: https://kit.svelte.dev/docs/configuration#paths

I tried it, now page loads but it does not load the related page. It loads the main page instead.

Current behaviour:

I route to `/profile/x`

Website url is `/profile/x` but it loads the `/x` page and shows the main page contents.

**Comment by userquin** [comment]
Any SSR page or api call must be excluded from sw interception, check  https://github.com/vite-pwa/sveltekit/issues/65

**Comment by omerharuncetin** [comment]
> Any SSR page or api call must be excluded from sw interception, check [vite-pwa/sveltekit#65](https://github.com/vite-pwa/sveltekit/issues/65)
> 
> NOTE: any page not being prerendered will not have the corresponding html page in the dist folder, on page refresh the entry will not be in the sw precache manifest and the sw will redirect/forward to fallback page, you need to exclude SSR pages from sw interception including them in the `navigateFallbackDenylist` and then add a custom handler to avoid browser offline error page redirecting to the offline page

Unfortunately still opens the home page when I try to route dynamic ssr pages. Here are what I added to the config regarding to the issue that you suggested to look at.

I defined `navigateFallbackDenyList` for my routes as following:

```ts
const navigateFallbackDenyList = [
  // prettier-ignore
  new RegExp("/^\/[^\/]+\/?$/") /* eslint-disable-line */,
  // prettier-ignore
  new RegExp("/^\/[^\/]+\/posts\/[^\/]+\/?$/") /* eslint-disable-line */,
  // prettier-ignore
  new RegExp("/^\/profile\/[^\/]+\/?$/") /* eslint-disable-line */,
  // prettier-ignore
  new RegExp("/^\/posts\/[^\/]+\/?$/") /* eslint-disable-line */,
  // prettier-ignore
  new RegExp("/^\/topics\/[^\/]+\/?$/") /* eslint-disable-line */,
];
```

Also defined `runtimeCaching` for every rule. Here is the one example:

```ts
{
            urlPattern: ({ url, sameOrigin }) =>
              // prettier-ignore
              sameOrigin && url.pathname.match("/^\/[^\/]+\/?$/") /* eslint-disable-line */,
            handler: "NetworkFirst",
            options: {
              cacheName: "ssr-pages-cache",
              /* cache only 200 responses */
              cacheableResponse: {
                statuses: [200],
              },
              /* check the options in the workbox-build docs*/
              matchOptions: {
                ignoreVary: true,
                ignoreSearch: true,
              },
              plugins: [
                {
                  /* this callback will be called when the fetch call fails */
                  handlerDidError: async () =>
                    Response.redirect("/error?offline", 302),
                  /* this callback will prevent caching the response */
                  cacheWillUpdate: async ({ response }) =>
                    response.status === 200 ? response : null,
                },
              ],
            },
          },
```

**Comment by userquin** [comment]
can you share the repo?

**Comment by omerharuncetin** [comment]
> can you share the repo?

Here is minimal reproduction that has the same vite, svelte and pwa config and node modules
https://github.com/omerharuncetin/pwa-reproduction

also here is the deployed version of the repository:

https://pwa-reprod.netlify.app/

you can try these urls:

https://pwa-reprod.netlify.app/
https://pwa-reprod.netlify.app/test
https://pwa-reprod.netlify.app/test/posts/postid
https://pwa-reprod.netlify.app/explore

**Comment by omerharuncetin** [comment]
hi @userquin is there any update on this issue?

**Comment by userquin** [comment]
You cannot redirect to error page since it is not being prerendered, the error.html page isn't in the sw precache, so you can prerender it or replace `handlerDidError` redirection with `/` instead using `/error` (you will get an infinite redirection).

Add `workbox.globPatterns` to include html, css, js and png assets (pwa icons not being precached).

Change cache names on each router or use only one with all the logic: move the logic to only 1 `urlPattern` handler.

If you refresh the page you will see the caches (right button on caches and refresh caches): the cache cannot be created if missing when intercepting the request.

**Comment by userquin** [comment]
Add `mode: 'development'` to pwa option to show the workbox messages in Netlify...

**Comment by omerharuncetin** [comment]
Thank you for your response. I added the `globPattern` values and set mode as `development` then updated the repository and netlify. Could you please briefly explain the following statement, because I couldn't understand it

`Change cache names on each router or use only one with all the logic: move the logic to only 1 urlPattern handler.`

> You cannot redirect to error page since it is not being prerendered, the error.html page isn't in the sw precache, so you can prerender it or replace `handlerDidError` redirection with `/` instead using `/error` (you will get an infinite redirection).
> 
> Add `workbox.globPatterns` to include html, css, js and png assets (pwa icons not being precached): `workbox.globPatterns: ['client/**/*.{js,css,png}']` (don't include html here, the plugin will do it for you)
> 
> Change cache names on each router or use only one with all the logic: move the logic to only 1 `urlPattern` handler.
> 
> If you refresh the page you will see the caches (right button on caches and refresh caches): the cache cannot be created if missing when intercepting the request.

**Comment by userquin** [comment]
![imagen](https://github.com/vite-pwa/vite-plugin-pwa/assets/6311119/45c49bbb-aa30-4015-b11e-7ff7fe919761)

**Comment by userquin** [comment]
you're caching all resources on each cache: navigate between routes in this comment https://github.com/vite-pwa/vite-plugin-pwa/issues/665#issuecomment-1949272129 with a page refresh and refresh `Cache storage` entries in dev tools (right button + refresh caches)

**Comment by userquin** [comment]
- go to https://pwa-reprod.netlify.app/ then go to https://pwa-reprod.netlify.app/test +page refresh
- back to home page + page refresh, then go to https://pwa-reprod.netlify.app/test +page refresh + refresh caches

Cache entries will be there (repeat the process with a few more pages)

**Comment by userquin** [comment]
You have duplicated cache names:
- https://github.com/omerharuncetin/pwa-reproduction/blob/main/vite.config.ts#L79
- https://github.com/omerharuncetin/pwa-reproduction/blob/main/vite.config.ts#L107
- https://github.com/omerharuncetin/pwa-reproduction/blob/main/vite.config.ts#L135
- https://github.com/omerharuncetin/pwa-reproduction/blob/main/vite.config.ts#L163
- https://github.com/omerharuncetin/pwa-reproduction/blob/main/vite.config.ts#L191

Move all to only 1 handler, you can use custom logic to return the `true` value for all ssr pages with a single regex

**Comment by userquin** [comment]
what's the purpose of this handler https://github.com/omerharuncetin/pwa-reproduction/blob/main/vite.config.ts#L76?

**Comment by userquin** [comment]
maybe the problem is previous handler

**Comment by omerharuncetin** [comment]
> what's the purpose of this handler https://github.com/omerharuncetin/pwa-reproduction/blob/main/vite.config.ts#L76?

That url should catch the profile url's in production. Such as `/userquin` or `/omerharuncetin`.

**Comment by userquin** [comment]
add pwa icons inside static folder, since you don't have web manifest icons the sw will have weird behavior, use `@vite-pwa/assets-generator` via CLI (or just copy paste them from the pwa kit repo to test the sw in your local)

**Comment by omerharuncetin** [comment]
> add pwa icons inside static folder, since you don't have web manifest icons the sw will have weird behavior, use `@vite-pwa/assets-generator` via CLI (or just copy paste them from the pwa kit repo to test the sw in your local)
> 
> EDIT: once web manifest icons added the sw `scope` will take effect and so only 1 cache added to the browser when navigating between pages + page refresh

PWA icons are already in the static folder. However, it's not included in precache and does not shows up in deployed netlify directory too. 

![image](https://github.com/vite-pwa/vite-plugin-pwa/assets/47770235/7ff3ad6b-348c-4612-9e92-15564a3da1f4)

**Comment by userquin** [comment]
pwa icons missing in the server ? just try requesting one of them or check the web manifest  in dev tools

**Comment by userquin** [comment]
uhmm, static folder should be on root not inside src folder

**Comment by omerharuncetin** [comment]
> uhmm, static folder should be on root not inside src folder

Oh good catch, thank you! Probably there was a mistake when I was moving the folder from my original repo to minimal. Just updated and I guess you are right. The regex that I use to catch profile url doesn't work properly tbh and idk why. Do you have any opinion on that, that would help me a lot tbh. Because that regex works when I try it on different regex test websites.

**Comment by userquin** [comment]
I'll try using another approach later, using kit sw: we've access to routes there https://kit.svelte.dev/docs/service-workers#inside-the-service-worker

**Comment by userquin** [comment]
it seems the sw precaching is there but it shouldn't (using custom sw we can warm the ssr cache when installing the sw):

![imagen](https://github.com/vite-pwa/vite-plugin-pwa/assets/6311119/a21033ff-399e-44b5-a4b3-0848a087a7ec)

**Comment by userquin** [comment]
it seems your pages not working properly, this is an example that's working:

![imagen](https://github.com/vite-pwa/vite-plugin-pwa/assets/6311119/3e4b70a6-e3d0-4ef3-b896-864fc88e9698)

![imagen](https://github.com/vite-pwa/vite-plugin-pwa/assets/6311119/21e39113-5741-4682-818c-c4a1496d90be)

**Comment by omerharuncetin** [comment]
> it seems your pages not working properly, this is an example that's working (just visit the page and then refresh it):
> 
> ![imagen](https://private-user-images.githubusercontent.com/6311119/306036098-3e4b70a6-e3d0-4ef3-b896-864fc88e9698.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNjQzODYsIm5iZiI6MTcwODM2NDA4NiwicGF0aCI6Ii82MzExMTE5LzMwNjAzNjA5OC0zZTRiNzBhNi1lM2QwLTRlZjMtYjg5Ni04NjRmYzg4ZTk2OTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTlUMTczNDQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDcxMTAwNDQ5NDViNGFlMzUzMzM3NTFmMmYzMzA3Y2ViYmFmYWU2MzE1YTIxYTgyOTExZTRiNjUzNzQ0ZjlkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dr0RxxYOGptRjHMxPmYKWbeY-SmMHbJNv83e6-S7sQ0)
> 
> ![imagen](https://private-user-images.githubusercontent.com/6311119/306036232-21e39113-5741-4682-818c-c4a1496d90be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNjQzODYsIm5iZiI6MTcwODM2NDA4NiwicGF0aCI6Ii82MzExMTE5LzMwNjAzNjIzMi0yMWUzOTExMy01NzQxLTQ2ODItODE4Yy1jNGExNDk2ZDkwYmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTlUMTczNDQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmY3ODYzZDE0MTU5OGFjZGM0NDg5Y2E0MjQ1NGNlMWY3ZjU3MjNkOTJkOTY1NGUxMGU2NmU3NjBmODg2Mzg1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BUR2j9dIDadhh3vA-cwUm2NWUGDsRFYmzCiWUQAcunU)

Thank you. and I wonder why /slug/posts/postId works but /slug does not work. Probably it would be better if I search for the routing in sveltekit.

**Comment by omerharuncetin** [comment]
I found out that the issue was related to regex as we discussed before. The regex was wrong and I had to use same regex for `workbox.navigateFallbackDenylist` and `workbox.runtimeCaching`. Thank you for your support @userquin 🙌
