### ISSUE TITLE
`updateServiceWorker` doesn't trigger page reload since `v0.19.1`

### ISSUE THREAD

**Issue by NicolaiHorlacher** [vite-pwa/vite-plugin-pwa#674]
I updated to version `v0.19.1` and noticed that `updateServiceWorker` doesn't trigger a reload of the page anymore.
I checked the changes between `v0.17.5` (last version I used) and noticed this condition was reversed.
https://github.com/vite-pwa/vite-plugin-pwa/blob/9652a0bfed99365b2037ab7374c818c85de3daaf/src/client/build/register.ts#L86

Maybe it got reversed by accident in #673?

**Comment by userquin** [comment]
upps

**Comment by userquin** [comment]
@NicolaiHorlacher should be fixed in `v0.19.2`
