### ISSUE TITLE
error injecting head tag with Remix vite plugin

### ISSUE THREAD

**Issue by xstevenyung** [vite-pwa/vite-plugin-pwa#678]
Remix has recently stabilized it's Vite support and will be migrating to it in the future.

I tried to setup `vite-plugin-pwa` but it seems like there is some problem with Remix and the plugin to be able to inject the proper `head` tags at the moment (not head tag is injected at the moment)

## Repoduction steps
1. init a new remix project with the vite template with: `npx create-remix@latest --template remix-run/remix/templates/vite`
2. install and setup `vite-plugin-pwa`

## workaround

I can manually inject the `link` tag in my `app/root.tsx`  file and the manifest is now properly injected.
I suspect that Remix override `vite-plugin-pwa` with it's own `head` tag handling logic.

```tsx
// app/root.tsx

  import {
    Links,
    Meta,
    Outlet,
    Scripts,
    ScrollRestoration,
  } from "@remix-run/react";
  import "./styles.css";

  export function Layout(props: { children: React.ReactNode }) {
    return (
      <html lang="en">
        <head>
          <meta charSet="utf-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <Meta />
          <Links />
          <link rel="manifest" href="/manifest.webmanifest"></link>
        </head>
        <body>
          {props.children}
          <ScrollRestoration />
          <Scripts />
        </body>
      </html>
    );
  }

  export default function App() {
    return <Outlet />;
  }

```

**Comment by userquin** [comment]
importing `virtual:pwa-info` not working?

**Comment by userquin** [comment]
check this sveltekit example: https://github.com/vite-pwa/sveltekit/blob/main/examples/sveltekit-ts/src/routes/%2Blayout.svelte#L6

**Comment by kirbysayshi** [comment]
In case this helps, this seems to be working for me in Remix:

```tsx
import { pwaInfo } from 'virtual:pwa-info';
// ....
// ....
        {pwaInfo ? (
          <link rel='manifest' href={pwaInfo.webManifest.href} />
        ) : null}
      </head>
```

It did take me a while to figure that out though :)

**Comment by xstevenyung** [comment]
just tested out, and yes both approaches works. maybe we could document this with an example similar to the sveltekit one ?

**Comment by userquin** [comment]
I Will try to add an example and include remix in the docs...

**Comment by userquin** [comment]
So, remix doesn't have an html entry point, that's why the manifest cannot be injected, and so we need to add it to the layout or root tsx component/entry point.

I'm going to play with it on my local to test also custom sw in dev mode and the pwa assets generation integration.

**Comment by xstevenyung** [comment]
thanks for the quick response, happy to help if you need any assistance for this!

**Comment by userquin** [comment]
like a beast, custom sw on dev server with pwa assets generator on the fly:

![imagen](https://github.com/vite-pwa/vite-plugin-pwa/assets/6311119/ed9dc6ef-f7b9-41cd-a22c-9f18e7158e80)

![imagen](https://github.com/vite-pwa/vite-plugin-pwa/assets/6311119/6db4b730-f4f1-4f26-a0ec-89b0442d49c5)

**Comment by userquin** [comment]
build also working:

![imagen](https://github.com/vite-pwa/vite-plugin-pwa/assets/6311119/33493c86-20bb-4d7f-8a5f-18b225f1fcd7)

**Comment by userquin** [comment]
how can I run the build locally? `node build/server/index.js` seems to be not working...

**Comment by userquin** [comment]
Here the repo: https://github.com/userquin/remix-pwa

**Comment by userquin** [comment]
`pnpm start` 🤦‍♂️

![imagen](https://github.com/vite-pwa/vite-plugin-pwa/assets/6311119/ca2189d5-ed78-4c2b-bf94-bb671b662e77)

**Comment by userquin** [comment]
Using SPA mode (`ssr: false` in remix plugin) remix build seems to generate the entry pont (index.html) after pwa plugin builds the service worker and so missing from the sw precache manifest.

It seems we can use SPA or SSR app, there is no hybrid mode.

**Comment by userquin** [comment]
spa pwa changes can be found here with some configuration changes: https://github.com/userquin/remix-pwa/pull/1

**Comment by userquin** [comment]
@xstevenyung @kirbysayshi just found `buildEnd` remix plugin hook, with SPA mode we can now include the entry point in the sw precache manifest.

I'm going to update the PR and merge into main, SSR App will require some additional work.

About SSR app, we'll need a new integration in ViteOrg for Remix.

![imagen](https://github.com/vite-pwa/vite-plugin-pwa/assets/6311119/c5b220bd-de34-45e1-b71b-9de4be94c29a)

**Comment by userquin** [comment]
SPA mode in main https://github.com/userquin/remix-pwa

**Comment by userquin** [comment]
@xstevenyung you can check the hack for SSR in main: https://github.com/userquin/remix-pwa/blob/main/vite.config.ts

**Comment by xstevenyung** [comment]
just implemented, seems to work but i have to admit, i have a limited understanding on what's going on in the vite.config.ts

**Comment by userquin** [comment]
@xstevenyung we need a custom plugin for remix, this weekend I'll try to create it: `@vite-pwa/remix` with similar logic and a few options to customize the build.

**Comment by xstevenyung** [comment]
thanks so much for your work 🙏

**Comment by userquin** [comment]
@xstevenyung FYI https://github.com/vite-pwa/remix, I'm preparing release and docs...

**Comment by xstevenyung** [comment]
thanks will give it a try asap 🙏

**Comment by xstevenyung** [comment]
closing this as all future issue discussion will happens on https://github.com/vite-pwa/remix

thanks again for your work @userquin
