### ISSUE TITLE
The script has an unsupported MIME type ('text/html').

### ISSUE THREAD

**Issue by joaocruz-dev** [vite-pwa/vite-plugin-pwa#680]
Hi, I couldn't find a solution to this problem. I'm using vite-plugin-pwa with the settings below:

<img width="500" alt="image" src="https://github.com/vite-pwa/vite-plugin-pwa/assets/40739602/22d7131d-a03f-45db-92aa-d73eae1fb10c">

___
When I build the code in production and test it locally, I get the following warning in the console for the "sw.js" file:

<img width="500" alt="image" src="https://github.com/vite-pwa/vite-plugin-pwa/assets/40739602/181ad8b5-6b9c-486f-8c63-716b9865a602">

___
Debugging the code, the service worker is being injected as "./sw.js"

<img width="800" alt="image" src="https://github.com/vite-pwa/vite-plugin-pwa/assets/40739602/00ae4a71-868e-4baf-ad04-31e77947d72f">

___
In the case of a single page application, when accessing the "/auth/sign-in" route, the scope is translated as "/auth/sw.js", generating an error. 

<img width="500" alt="image" src="https://github.com/vite-pwa/vite-plugin-pwa/assets/40739602/78d2058e-5450-4ffe-a711-fdaced40d682">

___
The service worker is being generated correctly and can be accessed in "/sw.js".

What is the best solution?

Thanks so much!

**Comment by userquin** [comment]
try setting `base: '/'` to vite options or pwa options

**Comment by joaocruz-dev** [comment]
Worked perfectly. I thank @userquin  !!!
