### ISSUE TITLE
Wrong envPrefix in Astro Integration

### ISSUE THREAD

**Issue by Eptagone** [vite-pwa/vite-plugin-pwa#689]
Hi, thank you very much for this library.

I'm using the Astro Integration and I discovered that all my **PUBLIC_*** variables are been ignored after build in my custom service worker.
I tested with the following variables:
```dotenv
PUBLIC_SAMPLE=ASTRO
VITE_SAMPLE=VITE
```
I saw that the **VITE_SAMPLE** variable is included but not **PUBLIC_SAMPLE**.

The default value of **envPrefix** in Vite is [VITE_](https://vitejs.dev/config/shared-options.html#envprefix) but in Astro the prefix is [PUBLIC_](https://docs.astro.build/en/guides/environment-variables/) for client scripts.

Is there a way to change that?

**Comment by userquin** [comment]
Only variables starting with VITE_ will be exposed by vite https://vitejs.dev/guide/env-and-mode.html#env-variables-and-modes

**Comment by Eptagone** [comment]
That prefix is customized with the envPrefix option.

https://vitejs.dev/config/shared-options.html#envprefix

**Comment by userquin** [comment]
Yeah, you can change it, but only those env vars starting with the prefix will be available via `import.meta.env`.

**Comment by userquin** [comment]
You can configure empty prefix

**Comment by userquin** [comment]
Read the `SECURITY NOTES` from you VITE_ link, you can also use define.

**Comment by Eptagone** [comment]
> Yeah, you can change it, but only those env vars starting with the prefix will be available via `import.meta.env`.

Yes, that's what I want. I want to make VitePWA to use the same prefix as Astro: `PUBLIC_`. Because that's the default prefix for client variables in Astro projects.

**Comment by Eptagone** [comment]
Oops. Sorry, I thought this was a monorepo. Sorry. I will move this issue to the [correct repository](https://github.com/vite-pwa/astro).
