### ISSUE TITLE
submit logo to simple-icon

### ISSUE THREAD

**Issue by ianzone** [vite-pwa/vite-plugin-pwa#703]
nice logo, wish to make a badge like [![PWA](https://img.shields.io/badge/PWA-5A0FC8?logo=PWA&labelColor=grey)](https://github.com/vite-pwa/vite-plugin-pwa/), would you please submit logo to https://github.com/simple-icons/simple-icons

**Comment by userquin** [comment]
?

**Comment by ianzone** [comment]
the point is, that if the SVG logo is available on simple-icons, I could create a badge on the readme file using `[![VitePWA](https://img.shields.io/badge/PWA-orange?logo=VitePWA&labelColor=grey)](https://vite-pwa-org.netlify.app/)`. Otherwise, the logo has to be referenced as dataurl
[![PWA](https://img.shields.io/badge/PWA-35849a?labelColor=grey&logo=data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjYwIiBoZWlnaHQ9IjI2MCIgdmlld0JveD0iMCAwIDE1NSAxNTUiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxwYXRoIGQ9Ik01MC42ODUzIDEwNC4zNDVDNDguMzkwOSAxMDAuMzk4IDQ2LjAwNDcgOTYuMzYwMiA0My43MTAzIDkyLjQxMzhDNDMuNTI2OCA5Mi4xMzg1IDQzLjQzNSA5MS44NjMyIDQzLjUyNjcgOTEuNDA0M0M0NS44MjExIDg0LjQyOTMgNDguMTE1NSA3Ny4zNjI2IDUwLjQwOTkgNzAuMzg3NkM1MC40MDk5IDcwLjI5NTkgNTAuNTAxNyA3MC4xMTIzIDUwLjU5MzUgNjkuODM3QzUzLjI1NSA3NS4wNjgyIDU1LjgyNDcgODAuMjA3NiA1OC40ODYyIDg1LjQzODlDNTguNjY5NyA4NS4wNzE3IDU4Ljc2MTUgODQuNzk2NCA1OC44NTMzIDg0LjUyMTFDNjIuNDMyNiA3My41MDggNjYuMDExOCA2Mi41ODY3IDY5LjU5MTEgNTEuNTczNkM2OS43NzQ2IDUxLjExNDcgNjkuOTU4MiA1MC45MzEyIDcwLjQxNyA1MS4wMjI5QzczLjYyOTIgNTEuMDIyOSA3Ni44NDE0IDUxLjAyMjkgODAuMTQ1MyA1MS4wMjI5QzgwLjY5NTkgNTEuMDIyOSA4MC44Nzk1IDUxLjIwNjUgODEuMDYzIDUxLjY2NTRDODQuMzY3IDYyLjU4NjcgODcuNjcwOSA3My40MTYyIDkwLjk3NDggODQuMzM3NUM5MS4wNjY2IDg0LjYxMjkgOTEuMTU4NCA4NC45OCA5MS4zNDE5IDg1LjQzODlDOTEuODAwOCA4NC41MjExIDkyLjE2NzkgODMuNjAzMyA5Mi40NDMyIDgyLjc3NzRDOTYuOTQwMiA3Mi4zMTQ5IDEwMS4zNDUgNjEuOTQ0MyAxMDUuODQyIDUxLjQ4MThDMTA1LjkzNCA1MS4yMDY1IDEwNi4wMjYgNTEuMDIyOSAxMDYuMzkzIDUxLjAyMjlDMTEwLjk4MiA1MS4wMjI5IDExNS41NzEgNTEuMDIyOSAxMjAuMDY4IDUxLjAyMjlDMTIwLjA2OCA1MS4wMjI5IDEyMC4xNiA1MS4wMjI5IDEyMC4yNTEgNTEuMDIyOUMxMTkuNzAxIDUyLjMwNzggMTE5LjI0MiA1My41MDA5IDExOC43ODMgNTQuNzg1N0MxMTIuMTc1IDcxLjAzMDEgMTA1LjY1OSA4Ny4zNjYxIDk5LjA1MTEgMTAzLjYxQzk4Ljk1OTMgMTAzLjc5NCA5OC43NzU3IDEwMy45NzggOTguODY3NSAxMDQuMjUzQzk0LjA5NTIgMTA0LjI1MyA4OS4zMjI5IDEwNC4yNTMgODQuNTUwNSAxMDQuMjUzQzg0LjY0MjMgMTA0LjA2OSA4NC41NTA1IDEwMy43OTQgODQuNDU4NyAxMDMuNjFDODQuMDkxNiAxMDIuNDE3IDgzLjcyNDUgMTAxLjIyNCA4My4zNTc0IDEwMC4wMzFDODAuNjA0MiA5MS4zMTI1IDc3Ljk0MjYgODIuNjg1NiA3NS4xODk0IDczLjk2NjlDNzUuMTg5NCA3My43ODMzIDc1LjE4OTQgNzMuNTk5OCA3NC45MTQxIDczLjUwOEM3MS41MTg0IDgzLjY5NTEgNjguMjE0NCA5My45NzQgNjQuODE4NyAxMDQuMTYxQzYwLjA0NjQgMTA0LjM0NSA1NS4zNjU4IDEwNC4zNDUgNTAuNjg1MyAxMDQuMzQ1WiIgZmlsbD0iIzRBQTZDMCIvPgo8cGF0aCBkPSJNNyAxMDQuMzQ1QzcgODYuODE1NSA3IDY5LjI4NjMgNyA1MS43NTcxQzcgNTEuMjA2NSA3LjA5MTc4IDUxLjAyMjkgNy43MzQyMSA1MS4wMjI5QzE1LjE2OCA1MS4wMjI5IDIyLjYwMTkgNTEuMDIyOSAzMC4wMzU3IDUxLjAyMjlDMzQuMTY1NiA1MS4wMjI5IDM4LjAyMDIgNTEuOTQwNyA0MS4zMjQxIDU0LjUxMDRDNDIuNzAwOCA1NS41MTk5IDQzLjg5MzggNTYuODA0OCA0NC45MDM0IDU4LjI3MzJDNDUuMDg2OSA1OC41NDg1IDQ1LjA4NjkgNTguNzMyMSA0NC45OTUyIDU5LjAwNzRDNDIuMjQxOSA2Ny41NDI2IDM5LjM5NjggNzYuMTY5NSAzNi42NDM2IDg0LjcwNDZDMzYuNTUxOCA4NS4wNzE3IDM2LjM2ODIgODUuMTYzNSAzNi4wMDExIDg1LjI1NTNDMzQuMDczOCA4NS43MTQyIDMyLjA1NDggODUuOTg5NSAzMC4wMzU3IDg1Ljk4OTVDMjcuMDA3MSA4NS45ODk1IDI0LjA3MDMgODUuOTg5NSAyMS4wNDE3IDg1Ljk4OTVDMjAuNjc0NiA4NS45ODk1IDIwLjU4MjggODUuOTg5NSAyMC41ODI4IDg2LjQ0ODRDMjAuNTgyOCA5Mi4zMjIgMjAuNTgyOCA5OC4yODc0IDIwLjU4MjggMTA0LjE2MVYxMDQuMjUzQzE2LjA4NTggMTA0LjM0NSAxMS40OTcgMTA0LjM0NSA3IDEwNC4zNDVaTTIwLjU4MjggNjguNDYwM0MyMC41ODI4IDcwLjY2MjkgMjAuNTgyOCA3Mi44NjU2IDIwLjU4MjggNzUuMTZDMjAuNTgyOCA3NS42MTg4IDIwLjY3NDYgNzUuNzEwNiAyMS4xMzM1IDc1LjcxMDZDMjIuMjM0OCA3NS43MTA2IDIzLjQyNzkgNzUuNzEwNiAyNC41MjkyIDc1LjcxMDZDMjYuMDg5NCA3NS43MTA2IDI3LjY0OTUgNzUuNzEwNiAyOS4yMDk3IDc1LjM0MzVDMzAuNTg2NCA3NC45NzY0IDMxLjg3MTIgNzQuNTE3NSAzMi42OTcyIDczLjMyNDRDMzQuNDQxIDcwLjg0NjUgMzQuNjI0NSA2OC4wOTMyIDMzLjUyMzIgNjUuMzRDMzIuNjA1NCA2Mi44NjIgMzAuNDk0NiA2MS44NTI1IDI4LjAxNjYgNjEuNTc3MUMyNS43MjIzIDYxLjMwMTggMjMuNDI3OSA2MS40ODU0IDIxLjEzMzUgNjEuMzkzNkMyMC42NzQ2IDYxLjM5MzYgMjAuNTgyOCA2MS41NzcxIDIwLjU4MjggNjEuOTQ0MkMyMC41ODI4IDY0LjE0NjkgMjAuNTgyOCA2Ni4zNDk1IDIwLjU4MjggNjguNDYwM1oiIGZpbGw9IiNFRUVFRUUiLz4KPHBhdGggZD0iTTEyOC4xNjcgOTIuMzYzNkgxMTRMMTMzLjgzMyA0NFY3MS42MzY0SDE0OEwxMjguMTY3IDEyMFY5Mi4zNjM2WiIgZmlsbD0iI0Y3RDk0QiIvPgo8L3N2Zz4K)](https://vite-pwa-org.netlify.app/)
```
[![PWA](https://img.shields.io/badge/PWA-35849a?labelColor=grey&logo=data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjYwIiBoZWlnaHQ9IjI2MCIgdmlld0JveD0iMCAwIDE1NSAxNTUiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxwYXRoIGQ9Ik01MC42ODUzIDEwNC4zNDVDNDguMzkwOSAxMDAuMzk4IDQ2LjAwNDcgOTYuMzYwMiA0My43MTAzIDkyLjQxMzhDNDMuNTI2OCA5Mi4xMzg1IDQzLjQzNSA5MS44NjMyIDQzLjUyNjcgOTEuNDA0M0M0NS44MjExIDg0LjQyOTMgNDguMTE1NSA3Ny4zNjI2IDUwLjQwOTkgNzAuMzg3NkM1MC40MDk5IDcwLjI5NTkgNTAuNTAxNyA3MC4xMTIzIDUwLjU5MzUgNjkuODM3QzUzLjI1NSA3NS4wNjgyIDU1LjgyNDcgODAuMjA3NiA1OC40ODYyIDg1LjQzODlDNTguNjY5NyA4NS4wNzE3IDU4Ljc2MTUgODQuNzk2NCA1OC44NTMzIDg0LjUyMTFDNjIuNDMyNiA3My41MDggNjYuMDExOCA2Mi41ODY3IDY5LjU5MTEgNTEuNTczNkM2OS43NzQ2IDUxLjExNDcgNjkuOTU4MiA1MC45MzEyIDcwLjQxNyA1MS4wMjI5QzczLjYyOTIgNTEuMDIyOSA3Ni44NDE0IDUxLjAyMjkgODAuMTQ1MyA1MS4wMjI5QzgwLjY5NTkgNTEuMDIyOSA4MC44Nzk1IDUxLjIwNjUgODEuMDYzIDUxLjY2NTRDODQuMzY3IDYyLjU4NjcgODcuNjcwOSA3My40MTYyIDkwLjk3NDggODQuMzM3NUM5MS4wNjY2IDg0LjYxMjkgOTEuMTU4NCA4NC45OCA5MS4zNDE5IDg1LjQzODlDOTEuODAwOCA4NC41MjExIDkyLjE2NzkgODMuNjAzMyA5Mi40NDMyIDgyLjc3NzRDOTYuOTQwMiA3Mi4zMTQ5IDEwMS4zNDUgNjEuOTQ0MyAxMDUuODQyIDUxLjQ4MThDMTA1LjkzNCA1MS4yMDY1IDEwNi4wMjYgNTEuMDIyOSAxMDYuMzkzIDUxLjAyMjlDMTEwLjk4MiA1MS4wMjI5IDExNS41NzEgNTEuMDIyOSAxMjAuMDY4IDUxLjAyMjlDMTIwLjA2OCA1MS4wMjI5IDEyMC4xNiA1MS4wMjI5IDEyMC4yNTEgNTEuMDIyOUMxMTkuNzAxIDUyLjMwNzggMTE5LjI0MiA1My41MDA5IDExOC43ODMgNTQuNzg1N0MxMTIuMTc1IDcxLjAzMDEgMTA1LjY1OSA4Ny4zNjYxIDk5LjA1MTEgMTAzLjYxQzk4Ljk1OTMgMTAzLjc5NCA5OC43NzU3IDEwMy45NzggOTguODY3NSAxMDQuMjUzQzk0LjA5NTIgMTA0LjI1MyA4OS4zMjI5IDEwNC4yNTMgODQuNTUwNSAxMDQuMjUzQzg0LjY0MjMgMTA0LjA2OSA4NC41NTA1IDEwMy43OTQgODQuNDU4NyAxMDMuNjFDODQuMDkxNiAxMDIuNDE3IDgzLjcyNDUgMTAxLjIyNCA4My4zNTc0IDEwMC4wMzFDODAuNjA0MiA5MS4zMTI1IDc3Ljk0MjYgODIuNjg1NiA3NS4xODk0IDczLjk2NjlDNzUuMTg5NCA3My43ODMzIDc1LjE4OTQgNzMuNTk5OCA3NC45MTQxIDczLjUwOEM3MS41MTg0IDgzLjY5NTEgNjguMjE0NCA5My45NzQgNjQuODE4NyAxMDQuMTYxQzYwLjA0NjQgMTA0LjM0NSA1NS4zNjU4IDEwNC4zNDUgNTAuNjg1MyAxMDQuMzQ1WiIgZmlsbD0iIzRBQTZDMCIvPgo8cGF0aCBkPSJNNyAxMDQuMzQ1QzcgODYuODE1NSA3IDY5LjI4NjMgNyA1MS43NTcxQzcgNTEuMjA2NSA3LjA5MTc4IDUxLjAyMjkgNy43MzQyMSA1MS4wMjI5QzE1LjE2OCA1MS4wMjI5IDIyLjYwMTkgNTEuMDIyOSAzMC4wMzU3IDUxLjAyMjlDMzQuMTY1NiA1MS4wMjI5IDM4LjAyMDIgNTEuOTQwNyA0MS4zMjQxIDU0LjUxMDRDNDIuNzAwOCA1NS41MTk5IDQzLjg5MzggNTYuODA0OCA0NC45MDM0IDU4LjI3MzJDNDUuMDg2OSA1OC41NDg1IDQ1LjA4NjkgNTguNzMyMSA0NC45OTUyIDU5LjAwNzRDNDIuMjQxOSA2Ny41NDI2IDM5LjM5NjggNzYuMTY5NSAzNi42NDM2IDg0LjcwNDZDMzYuNTUxOCA4NS4wNzE3IDM2LjM2ODIgODUuMTYzNSAzNi4wMDExIDg1LjI1NTNDMzQuMDczOCA4NS43MTQyIDMyLjA1NDggODUuOTg5NSAzMC4wMzU3IDg1Ljk4OTVDMjcuMDA3MSA4NS45ODk1IDI0LjA3MDMgODUuOTg5NSAyMS4wNDE3IDg1Ljk4OTVDMjAuNjc0NiA4NS45ODk1IDIwLjU4MjggODUuOTg5NSAyMC41ODI4IDg2LjQ0ODRDMjAuNTgyOCA5Mi4zMjIgMjAuNTgyOCA5OC4yODc0IDIwLjU4MjggMTA0LjE2MVYxMDQuMjUzQzE2LjA4NTggMTA0LjM0NSAxMS40OTcgMTA0LjM0NSA3IDEwNC4zNDVaTTIwLjU4MjggNjguNDYwM0MyMC41ODI4IDcwLjY2MjkgMjAuNTgyOCA3Mi44NjU2IDIwLjU4MjggNzUuMTZDMjAuNTgyOCA3NS42MTg4IDIwLjY3NDYgNzUuNzEwNiAyMS4xMzM1IDc1LjcxMDZDMjIuMjM0OCA3NS43MTA2IDIzLjQyNzkgNzUuNzEwNiAyNC41MjkyIDc1LjcxMDZDMjYuMDg5NCA3NS43MTA2IDI3LjY0OTUgNzUuNzEwNiAyOS4yMDk3IDc1LjM0MzVDMzAuNTg2NCA3NC45NzY0IDMxLjg3MTIgNzQuNTE3NSAzMi42OTcyIDczLjMyNDRDMzQuNDQxIDcwLjg0NjUgMzQuNjI0NSA2OC4wOTMyIDMzLjUyMzIgNjUuMzRDMzIuNjA1NCA2Mi44NjIgMzAuNDk0NiA2MS44NTI1IDI4LjAxNjYgNjEuNTc3MUMyNS43MjIzIDYxLjMwMTggMjMuNDI3OSA2MS40ODU0IDIxLjEzMzUgNjEuMzkzNkMyMC42NzQ2IDYxLjM5MzYgMjAuNTgyOCA2MS41NzcxIDIwLjU4MjggNjEuOTQ0MkMyMC41ODI4IDY0LjE0NjkgMjAuNTgyOCA2Ni4zNDk1IDIwLjU4MjggNjguNDYwM1oiIGZpbGw9IiNFRUVFRUUiLz4KPHBhdGggZD0iTTEyOC4xNjcgOTIuMzYzNkgxMTRMMTMzLjgzMyA0NFY3MS42MzY0SDE0OEwxMjguMTY3IDEyMFY5Mi4zNjM2WiIgZmlsbD0iI0Y3RDk0QiIvPgo8L3N2Zz4K)](https://vite-pwa-org.netlify.app/)
```
