### ISSUE TITLE
Prompt- Reload - not reloading

### ISSUE THREAD

**Issue by elvince** [vite-pwa/vite-plugin-pwa#717]
Hi,

Thanks for this plugin.

I follow all the instructions and look at your react samples on how to implement the update prompt.
Everything is working as expected except the "reload" part.
When I call **_updateServiceWorker(true)_**, nothing hapenned. I had to call _**window.location.reload();**_ for the refresh to happenned.
Without the reload part, even a "normal F5 refresh" was not working as if the worker was in a waiting state and can't move out of it.

Any hints?

Just in case it helps, during the build I had a warning on my main js file that **_won't be precached. Configure maximumFileSizeToCacheInBytes to change this limit._**

Thanks,

**Comment by userquin** [comment]
Try to provide a minimal reproduction, you can use the new create-pwa https://vite-pwa-org.netlify.app/guide/scaffolding.html   

About the warbing : https://vite-pwa-org.netlify.app/guide/faq.html

**Comment by mpaland** [comment]
@elvince, have you solved it? Cause our index.js is 2.5MB and reload (prompt setting) does not work either.

**Comment by userquin** [comment]
@mpaland any asset greater than 2MiB won't be added to the sw precache, check https://vite-pwa-org.netlify.app/guide/faq.html#missing-assets-from-sw-precache-manifest
