### ISSUE TITLE
Sqlite or database in users phone

### ISSUE THREAD

**Issue by alesha2911** [vite-pwa/vite-plugin-pwa#719]
How can i keep a database in users phone ?. May be sqlite. Only in users phone. **Not** browers a database.

**Comment by userquin** [comment]
You can use indexeddb, it is an sqlite database. If the database is complex or can change frequently, check dexie.

You can also check https://sqlite.org/wasm/doc/trunk/about.md.

**Comment by Jeree-TheOne** [comment]
@userquin using indexeddb where does data stored? if my app installed on a phone does all this data stored in local wrapper browser instance or maybe in global browser scope?

**Comment by userquin** [comment]
It is stored per host globally, check devtools application tab, search indexed db, you can access db also from service workers and web workers.

Beware with safari and ff: on safari there are some limitations (50mb only) and ff will not work in private browsing.

**Comment by Jeree-TheOne** [comment]
@userquin okay, got it, thank you!

**Comment by alesha2911** [comment]
@userquin  thank you, good day )

**Comment by alesha2911** [comment]
@userquin https://whatpwacando.today/ . PWA Vite Plugin support current function  ?

**Comment by userquin** [comment]
@alesha2911 what do you mean?

**Comment by alesha2911** [comment]
PWA Vite Plugin  support function Authentication, Face detection, Notifications, Geolocation  ?
