### ISSUE TITLE
Chromium based browsers shutdowns when open application tab in dev-tools

### ISSUE THREAD

**Issue by d-kurchenko** [vite-pwa/vite-plugin-pwa#722]
Description from this issue [#720](https://github.com/vite-pwa/vite-plugin-pwa/issues/720) is actual for me. 

My environment setup:
`node v20.10.0`
`npm 10.2.3`
`chrome 125.0.6422.141`

vite-plugin-pwa config:
```ts
VitePWA({
        registerType: 'autoUpdate',
        workbox: {
          importScripts: [
            '/web-push-sw.js',
          ],
          disableDevLogs: true,
          globPatterns: ['**/*.{js,css,html,svg,png,ico}'],
          cleanupOutdatedCaches: true,
          clientsClaim: true,
        },
        devOptions: {
          enabled: true,
          suppressWarnings: true,
          resolveTempFolder: () => 'public/sw',
        },
        manifest: {
          name: 'Name',
          short_name: 'short_name',
          start_url: '/',
          theme_color: '#ffffff',
          background_color: '#ffffff',
          description: 'description',
          icons: [
            {
              src: '/icon.png',
              purpose: 'any',
            },
            {
              src: '/maskable_icon.png',
              purpose: 'maskable',
            },
          ],
        },
      })
```

Chrome logs on shutdown:
![image](https://github.com/vite-pwa/vite-plugin-pwa/assets/93146235/ecc9255e-fec0-4c1b-89ba-9500796c213b)

**Comment by d-kurchenko** [comment]
> You can file an issue in chrome/chromium, we cannot do anything here

But it looks like problem not with chromium, because i have just tried to open `application` tab on another web-sites and it works fine.

**Comment by userquin** [comment]
When does the error occur, in development, local build + preview, or application deployed to production? If the error is about the development server, the Chrome error is about the ssl/tls handshake, try disabling https in development

**Comment by d-kurchenko** [comment]
> When does the error occur, in development, local build + preview, or application deployed to production? If the error is about the development server, the Chrome error is about the ssl/tls handshake, try disabling https in development

Error occurs in all envs: dev, local build + preview, prod.

**Comment by d-kurchenko** [comment]
> Can you share the url in production?

[url](https://mentor-v2.dev.hope.study/)

**Comment by userquin** [comment]
opening Application tab just closes all chrome instances even with private browsing 🤔

**Comment by userquin** [comment]
can you try removing `install` and `activate` from your `web-push-sw.js`? Just remove these listeners:

```js
self.addEventListener('install', (event) => {
  event.waitUntil(self.skipWaiting());
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});
```

**Comment by d-kurchenko** [comment]
> can you try removing `install` and `activate` from your `web-push-sw.js`? Just remove these listeners:

It did not help. I have tried to remove all custom config ssettings, and leave only defaults, but it did not help too. A little bit later i will try to init new project and add `vite-plugin-pwa` to it. After that I will write back

**Comment by d-kurchenko** [comment]
The problem disappeared when I removed the `icon` options from `manifest`. May be the problem have occurred because chromium team updated the manifest contract and my icons no longer match it.

**Comment by userquin** [comment]
Can you just add the type (mime type, image/png) and sizes options  to your icons?

**Comment by d-kurchenko** [comment]
> Can you just add the type (mime type, image/png) and sizes options to your icons?

Yes, I just refactored the icons as recommended in [this instructions](https://vite-pwa-org.netlify.app/guide/pwa-minimal-requirements.html#icons-images) and everything worked.
