### ISSUE TITLE
When I access "/notice" to display cached content, it will automatically redirect to "/notice/" by default homepage "/"

### ISSUE THREAD

**Issue by kongyijilafumi** [vite-pwa/vite-plugin-pwa#740]
How do I configure PWA

- When I visit **"/notice"**
![image](https://github.com/user-attachments/assets/91f14675-b9d7-4774-8be2-bc6d1a51f1c9)
![image](https://github.com/user-attachments/assets/77d000ca-a418-4910-82af-e4c701fe31f6)

- When I visit **"/notice/"**, it will redirect to homepage "/"
![image](https://github.com/user-attachments/assets/ab7953e3-5fd8-4333-b2ec-372896934bdb)
![image](https://github.com/user-attachments/assets/120e3f97-1f24-46c9-8d1b-6160d2e8bf09)

so,what can i reslove this problem?

**Comment by userquin** [comment]
using SSR? if so check https://github.com/vite-pwa/sveltekit/issues/65 and https://github.com/vite-pwa/sveltekit/issues/65#issuecomment-2256556810

**Comment by kongyijilafumi** [comment]
> using SSR? if so check [vite-pwa/sveltekit#65](https://github.com/vite-pwa/sveltekit/issues/65) and [vite-pwa/sveltekit#65 (comment)](https://github.com/vite-pwa/sveltekit/issues/65#issuecomment-2256556810)

@userquin 
there is my config file
```ts
// nuxt.config.ts
  pwa: {
    strategies: 'generateSW',
    registerType: "prompt",
    manifest : {
      name: 'xxx',
      short_name: 'xxx',
    },
    workbox: {
      globPatterns: ['**/*.{js,css,html,png,svg,ico,jpg,mp3}'],
      runtimeCaching: [
        {
          urlPattern: new RegExp(`^http.*\.(js|css|html|png|svg|ico|jpg|mp3)\/?$`),
          handler: "CacheFirst",
          options: {
            cacheName: 'assets-cache',
            expiration: {
              maxEntries: 10,
              maxAgeSeconds: 60 * 60 * 24 * 30, // <== 30 days
            },
            cacheableResponse: {
              statuses: [0, 200],
            },
            matchOptions: {
              ignoreSearch: true,
            },
          },
        }
      ]
    },
    client: {
      installPrompt: true,
      // you don't need to include this: only for testing purposes
      // if enabling periodic sync for update use 1 hour or so (periodicSyncForUpdates: 3600)
      periodicSyncForUpdates: 3600,
    },
    devOptions: {
      enabled: true,
      suppressWarnings: true,
      navigateFallback: '/',
      navigateFallbackAllowlist: [/^\/$/],
      type: 'module',
    },
  }
```

I use `nuxt generate` to build static web content, and then I access the `/motion/` question as the title suggests. My website is using static content. How can I configure the `nuxt.config.ts` file to achieve the desired effect?

**Comment by kongyijilafumi** [comment]
I resolved this problem.I configuration `pwa.workbox.navigateFallbackDenylist`.
```ts
// nuxt.config.ts
pwa:{
  workbox: {
    navigateFallbackDenylist: [
      /\/$/,
      /\?\w+/,
    ],
  }
}

```
and then, It will not redirect to homepage "/".
