### ISSUE TITLE
Error: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. Received protocol 'virtual:'

### ISSUE THREAD

**Issue by arnaudambro** [vite-pwa/vite-plugin-pwa#755]
I'm using Remix and I get this error

```
Error: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. Received protocol 'virtual:'
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:239:11)
    at defaultLoad (node:internal/modules/esm/load:130:3)
    at ModuleLoader.load (node:internal/modules/esm/loader:409:13)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:56)
    at new ModuleJob (node:internal/modules/esm/module_job:65:26)
    at #createModuleJob (node:internal/modules/esm/loader:303:17)
    at ModuleLoader.getJobFromResolveResult (node:internal/modules/esm/loader:260:34)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:241:17)
    at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:21)
```

I can give you more info but not sure what ?
maybe the best is to give you my repo as it's open source
https://github.com/betagouv/zacharie/pull/7

**Comment by arnaudambro** [comment]
I actually also opened an issue there -> https://github.com/vite-pwa/remix/issues/14

**Comment by arnaudambro** [comment]
mmm this is closed but my problem isn't solved yet ! 😄
I'll post a message here when I will have solved my problem then :)

@userquin gave me a good advice

> You can use create-pwa for a remix example, check https://vite-pwa-org.netlify.app/guide/scaffolding.html

> Select react then remix in the prompts...

true thing: the template is working well... so I'll keep digging there cause I created the original repo with remix helper, and I can't make it work

so my next task is:
- check what's the diff with the original repo
- find what was wrong
- post it here

**Comment by userquin** [comment]
Any PWA repo in PWA Org. is a `pnpm` monorepo, we use `pnpm` as package manager enabled/installed via `corepack`. Right now all examples dependencies are installed via `workspace:` protocol to test latest changes in the corresponding repository.

In the near future, we're going to switch to `catalog:` protocol for dependencies, we cannot add support for other package managers.

You can use`create-pwa` (https://vite-pwa-org.netlify.app/guide/scaffolding.html), similar to `create-vite`.

If you want to run the examples in `vite-plugin-pwa`, you can:
- run `pnpm install` from root folder
- run `pnpm run examples` and follow the prompts: similar to `create-pwa` CLI wizard

**Comment by arnaudambro** [comment]
ok perfect, thanks a lot for your time ! and your lib :)
