### ISSUE TITLE
I have an issue for new release of registerType: 'prompt',

### ISSUE THREAD

**Issue by samgholipoor** [vite-pwa/vite-plugin-pwa#770]
Hi there.

I have an issue with :
VitePWA({
        registerType: 'prompt',
})

when I wanna release new version to production, a user comes to my web-app after a long time, he can't load the app and the app is empty, because browser can't serve js files of previous releases and gets 404 (new assets overwrite the previous ones), and on the other hand the new service worker is downloaded and gets stuck and waiting for user accept.

I wanna know how to handle new release with prompt registerType?

**Comment by userquin** [comment]
Did you change from auto update to prompt? 

Maybe you've your server serving assets with wrong cache headers, check deployment page in the docs.

**Comment by elvince** [comment]
@samgholipoor 
I have the same issue. Did you solve it?
thanks,

**Comment by samgholipoor** [comment]
you should set correct cache header for assets, checkout this link:
https://github.com/vite-pwa/vite-plugin-pwa/blob/main/docs/deployment/nginx.md

**Comment by userquin** [comment]
@samgholipoor is this issue solved? If so, can we close it?

**Comment by samgholipoor** [comment]
@userquin  yes
