### ISSUE TITLE
`<head>` tag required for the manifest to be correctly injected

### ISSUE THREAD

**Issue by simensol** [vite-pwa/vite-plugin-pwa#782]
I spent several hours debugging why the `<link rel="manifest" href="/manifest.webmanifest">` tag wasn't injected into my app by `vite-plugin-pwa`.

Since I use [`unjs/unhead`](https://github.com/unjs/unhead) to manage all `<head>` tags, my `index.html` entry point didn't have a `<head>` tag:

```html
<!DOCTYPE html>
<html lang="en">
    <body>
        <div id="app"></div>
        <script type="module" src="/src/main.ts"></script>
    </body>
</html>
```

I realized that for `vite-plugin-pwa` to inject the manifest, an empty `<head>` tag is required:

```html
<!DOCTYPE html>
<html lang="en">
    <head>
    </head>
    <body>
        <div id="app"></div>
        <script type="module" src="/src/main.ts"></script>
    </body>
</html>
```

This should probably be documented somewhere.

**Comment by userquin** [comment]
PR welcome :pray: (use the [docs](https://github.com/vite-pwa/docs) repo)

**Comment by simensol** [comment]
Would it be more appropriate to consider this as a bug or to raise a warning instead of just documenting it?

**Comment by userquin** [comment]
@simensol can you check using the version from here https://github.com/vite-pwa/vite-plugin-pwa/pull/784#issuecomment-2473648975 ?

**Comment by simensol** [comment]
@userquin The warning message works as expected:

```bash
PWA WARNING:
</head> and <body> not found in the html, the service worker and web manifest will not be injected.
```

However, in my case, only the `<head>` tag was missing, so no error was raised. Could we also raise an error if only the `<head>` tag is missing?
